// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package httpapi

import (
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ReadinessResponseDatabase.
const (
	Down ReadinessResponseDatabase = "down"
	Up   ReadinessResponseDatabase = "up"
)

// Valid indicates whether the value is a known member of the ReadinessResponseDatabase enum.
func (e ReadinessResponseDatabase) Valid() bool {
	switch e {
	case Down:
		return true
	case Up:
		return true
	default:
		return false
	}
}

// Defines values for ReadinessResponseStatus.
const (
	ReadinessResponseStatusOk          ReadinessResponseStatus = "ok"
	ReadinessResponseStatusUnavailable ReadinessResponseStatus = "unavailable"
)

// Valid indicates whether the value is a known member of the ReadinessResponseStatus enum.
func (e ReadinessResponseStatus) Valid() bool {
	switch e {
	case ReadinessResponseStatusOk:
		return true
	case ReadinessResponseStatusUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for StatusResponseStatus.
const (
	StatusResponseStatusOk StatusResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the StatusResponseStatus enum.
func (e StatusResponseStatus) Valid() bool {
	switch e {
	case StatusResponseStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for TranscriptionTaskStatus.
const (
	Aligning     TranscriptionTaskStatus = "aligning"
	Completed    TranscriptionTaskStatus = "completed"
	Downloading  TranscriptionTaskStatus = "downloading"
	Failed       TranscriptionTaskStatus = "failed"
	Merging      TranscriptionTaskStatus = "merging"
	Preparing    TranscriptionTaskStatus = "preparing"
	Queued       TranscriptionTaskStatus = "queued"
	Resolving    TranscriptionTaskStatus = "resolving"
	Transcribing TranscriptionTaskStatus = "transcribing"
)

// Valid indicates whether the value is a known member of the TranscriptionTaskStatus enum.
func (e TranscriptionTaskStatus) Valid() bool {
	switch e {
	case Aligning:
		return true
	case Completed:
		return true
	case Downloading:
		return true
	case Failed:
		return true
	case Merging:
		return true
	case Preparing:
		return true
	case Queued:
		return true
	case Resolving:
		return true
	case Transcribing:
		return true
	default:
		return false
	}
}

// CreateTranscriptionRequest defines model for CreateTranscriptionRequest.
type CreateTranscriptionRequest struct {
	Url string `json:"url"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// ReadinessResponse defines model for ReadinessResponse.
type ReadinessResponse struct {
	Database ReadinessResponseDatabase `json:"database"`
	Status   ReadinessResponseStatus   `json:"status"`
}

// ReadinessResponseDatabase defines model for ReadinessResponse.Database.
type ReadinessResponseDatabase string

// ReadinessResponseStatus defines model for ReadinessResponse.Status.
type ReadinessResponseStatus string

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	Status StatusResponseStatus `json:"status"`
}

// StatusResponseStatus defines model for StatusResponse.Status.
type StatusResponseStatus string

// TranscriptionError defines model for TranscriptionError.
type TranscriptionError struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// TranscriptionTask defines model for TranscriptionTask.
type TranscriptionTask struct {
	CompletedChunks int                 `json:"completed_chunks"`
	CreatedAt       time.Time           `json:"created_at"`
	Error           *TranscriptionError `json:"error,omitempty"`
	Id              openapi_types.UUID  `json:"id"`

	// Markdown Complete Markdown transcript; only present after completion.
	Markdown    *string                 `json:"markdown,omitempty"`
	SourceUrl   string                  `json:"source_url"`
	Stage       string                  `json:"stage"`
	Status      TranscriptionTaskStatus `json:"status"`
	Title       *string                 `json:"title,omitempty"`
	TotalChunks int                     `json:"total_chunks"`
	UpdatedAt   time.Time               `json:"updated_at"`
}

// TranscriptionTaskStatus defines model for TranscriptionTaskStatus.
type TranscriptionTaskStatus string

// Error defines model for Error.
type Error = ErrorResponse

// CreateTranscriptionJSONRequestBody defines body for CreateTranscription for application/json ContentType.
type CreateTranscriptionJSONRequestBody = CreateTranscriptionRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /api/v1/transcriptions)
	CreateTranscription(w http.ResponseWriter, r *http.Request)

	// (GET /api/v1/transcriptions/{taskId})
	GetTranscription(w http.ResponseWriter, r *http.Request, taskId openapi_types.UUID)

	// (GET /healthz)
	GetLiveness(w http.ResponseWriter, r *http.Request)

	// (GET /readyz)
	GetReadiness(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (POST /api/v1/transcriptions)
func (_ Unimplemented) CreateTranscription(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/transcriptions/{taskId})
func (_ Unimplemented) GetTranscription(w http.ResponseWriter, r *http.Request, taskId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /healthz)
func (_ Unimplemented) GetLiveness(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /readyz)
func (_ Unimplemented) GetReadiness(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateTranscription operation middleware
func (siw *ServerInterfaceWrapper) CreateTranscription(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTranscription(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTranscription operation middleware
func (siw *ServerInterfaceWrapper) GetTranscription(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "taskId" -------------
	var taskId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "taskId", chi.URLParam(r, "taskId"), &taskId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "taskId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTranscription(w, r, taskId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLiveness operation middleware
func (siw *ServerInterfaceWrapper) GetLiveness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLiveness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadiness operation middleware
func (siw *ServerInterfaceWrapper) GetReadiness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadiness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetLiveness)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/readyz", wrapper.GetReadiness)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/transcriptions", wrapper.CreateTranscription)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/transcriptions/{taskId}", wrapper.GetTranscription)
	})

	return r
}
