// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package httpapi

import (
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for AIArtifactStatus.
const (
	AIArtifactStatusFailed     AIArtifactStatus = "failed"
	AIArtifactStatusGenerating AIArtifactStatus = "generating"
	AIArtifactStatusQueued     AIArtifactStatus = "queued"
	AIArtifactStatusReady      AIArtifactStatus = "ready"
	AIArtifactStatusStale      AIArtifactStatus = "stale"
)

// Valid indicates whether the value is a known member of the AIArtifactStatus enum.
func (e AIArtifactStatus) Valid() bool {
	switch e {
	case AIArtifactStatusFailed:
		return true
	case AIArtifactStatusGenerating:
		return true
	case AIArtifactStatusQueued:
		return true
	case AIArtifactStatusReady:
		return true
	case AIArtifactStatusStale:
		return true
	default:
		return false
	}
}

// Defines values for AIArtifactType.
const (
	AIArtifactTypeEpisodeSummary AIArtifactType = "episode_summary"
)

// Valid indicates whether the value is a known member of the AIArtifactType enum.
func (e AIArtifactType) Valid() bool {
	switch e {
	case AIArtifactTypeEpisodeSummary:
		return true
	default:
		return false
	}
}

// Defines values for AICitationSourceType.
const (
	AICitationSourceTypeNote       AICitationSourceType = "note"
	AICitationSourceTypeTranscript AICitationSourceType = "transcript"
)

// Valid indicates whether the value is a known member of the AICitationSourceType enum.
func (e AICitationSourceType) Valid() bool {
	switch e {
	case AICitationSourceTypeNote:
		return true
	case AICitationSourceTypeTranscript:
		return true
	default:
		return false
	}
}

// Defines values for AIMessageRole.
const (
	Assistant AIMessageRole = "assistant"
	User      AIMessageRole = "user"
)

// Valid indicates whether the value is a known member of the AIMessageRole enum.
func (e AIMessageRole) Valid() bool {
	switch e {
	case Assistant:
		return true
	case User:
		return true
	default:
		return false
	}
}

// Defines values for AIMessageStatus.
const (
	AIMessageStatusCompleted AIMessageStatus = "completed"
	AIMessageStatusFailed    AIMessageStatus = "failed"
	AIMessageStatusStreaming AIMessageStatus = "streaming"
)

// Valid indicates whether the value is a known member of the AIMessageStatus enum.
func (e AIMessageStatus) Valid() bool {
	switch e {
	case AIMessageStatusCompleted:
		return true
	case AIMessageStatusFailed:
		return true
	case AIMessageStatusStreaming:
		return true
	default:
		return false
	}
}

// Defines values for ConversationScope.
const (
	ConversationScopeEpisode ConversationScope = "episode"
	ConversationScopeLibrary ConversationScope = "library"
)

// Valid indicates whether the value is a known member of the ConversationScope enum.
func (e ConversationScope) Valid() bool {
	switch e {
	case ConversationScopeEpisode:
		return true
	case ConversationScopeLibrary:
		return true
	default:
		return false
	}
}

// Defines values for ExportMode.
const (
	FullTranscript     ExportMode = "full_transcript"
	NotesOnly          ExportMode = "notes_only"
	OrganizedNote      ExportMode = "organized_note"
	SelectedTranscript ExportMode = "selected_transcript"
)

// Valid indicates whether the value is a known member of the ExportMode enum.
func (e ExportMode) Valid() bool {
	switch e {
	case FullTranscript:
		return true
	case NotesOnly:
		return true
	case OrganizedNote:
		return true
	case SelectedTranscript:
		return true
	default:
		return false
	}
}

// Defines values for ImportResponseStatus.
const (
	ImportResponseStatusCanceled  ImportResponseStatus = "canceled"
	ImportResponseStatusFailed    ImportResponseStatus = "failed"
	ImportResponseStatusQueued    ImportResponseStatus = "queued"
	ImportResponseStatusRunning   ImportResponseStatus = "running"
	ImportResponseStatusSucceeded ImportResponseStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the ImportResponseStatus enum.
func (e ImportResponseStatus) Valid() bool {
	switch e {
	case ImportResponseStatusCanceled:
		return true
	case ImportResponseStatusFailed:
		return true
	case ImportResponseStatusQueued:
		return true
	case ImportResponseStatusRunning:
		return true
	case ImportResponseStatusSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for ProcessingStatus.
const (
	ProcessingStatusCompleted ProcessingStatus = "completed"
	ProcessingStatusFailed    ProcessingStatus = "failed"
	ProcessingStatusQueued    ProcessingStatus = "queued"
	ProcessingStatusRunning   ProcessingStatus = "running"
	ProcessingStatusWaiting   ProcessingStatus = "waiting"
)

// Valid indicates whether the value is a known member of the ProcessingStatus enum.
func (e ProcessingStatus) Valid() bool {
	switch e {
	case ProcessingStatusCompleted:
		return true
	case ProcessingStatusFailed:
		return true
	case ProcessingStatusQueued:
		return true
	case ProcessingStatusRunning:
		return true
	case ProcessingStatusWaiting:
		return true
	default:
		return false
	}
}

// Defines values for ReadinessResponseDatabase.
const (
	Down ReadinessResponseDatabase = "down"
	Up   ReadinessResponseDatabase = "up"
)

// Valid indicates whether the value is a known member of the ReadinessResponseDatabase enum.
func (e ReadinessResponseDatabase) Valid() bool {
	switch e {
	case Down:
		return true
	case Up:
		return true
	default:
		return false
	}
}

// Defines values for ReadinessResponseStatus.
const (
	ReadinessResponseStatusOk          ReadinessResponseStatus = "ok"
	ReadinessResponseStatusUnavailable ReadinessResponseStatus = "unavailable"
)

// Valid indicates whether the value is a known member of the ReadinessResponseStatus enum.
func (e ReadinessResponseStatus) Valid() bool {
	switch e {
	case ReadinessResponseStatusOk:
		return true
	case ReadinessResponseStatusUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for ResolveStatus.
const (
	ResolveStatusCompleted ResolveStatus = "completed"
	ResolveStatusFailed    ResolveStatus = "failed"
	ResolveStatusPending   ResolveStatus = "pending"
)

// Valid indicates whether the value is a known member of the ResolveStatus enum.
func (e ResolveStatus) Valid() bool {
	switch e {
	case ResolveStatusCompleted:
		return true
	case ResolveStatusFailed:
		return true
	case ResolveStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for SearchDocumentType.
const (
	SearchDocumentTypeAiArtifact SearchDocumentType = "ai_artifact"
	SearchDocumentTypeNote       SearchDocumentType = "note"
	SearchDocumentTypeTranscript SearchDocumentType = "transcript"
)

// Valid indicates whether the value is a known member of the SearchDocumentType enum.
func (e SearchDocumentType) Valid() bool {
	switch e {
	case SearchDocumentTypeAiArtifact:
		return true
	case SearchDocumentTypeNote:
		return true
	case SearchDocumentTypeTranscript:
		return true
	default:
		return false
	}
}

// Defines values for SearchMode.
const (
	Hybrid  SearchMode = "hybrid"
	Keyword SearchMode = "keyword"
)

// Valid indicates whether the value is a known member of the SearchMode enum.
func (e SearchMode) Valid() bool {
	switch e {
	case Hybrid:
		return true
	case Keyword:
		return true
	default:
		return false
	}
}

// Defines values for SearchScope.
const (
	SearchScopeEpisode SearchScope = "episode"
	SearchScopeLibrary SearchScope = "library"
)

// Valid indicates whether the value is a known member of the SearchScope enum.
func (e SearchScope) Valid() bool {
	switch e {
	case SearchScopeEpisode:
		return true
	case SearchScopeLibrary:
		return true
	default:
		return false
	}
}

// Defines values for SourceType.
const (
	ApplePodcasts SourceType = "apple_podcasts"
	DirectAudio   SourceType = "direct_audio"
	Rss           SourceType = "rss"
)

// Valid indicates whether the value is a known member of the SourceType enum.
func (e SourceType) Valid() bool {
	switch e {
	case ApplePodcasts:
		return true
	case DirectAudio:
		return true
	case Rss:
		return true
	default:
		return false
	}
}

// Defines values for StatusResponseStatus.
const (
	StatusResponseStatusOk StatusResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the StatusResponseStatus enum.
func (e StatusResponseStatus) Valid() bool {
	switch e {
	case StatusResponseStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for TranscriptionProfile.
const (
	Economy TranscriptionProfile = "economy"
	Quality TranscriptionProfile = "quality"
)

// Valid indicates whether the value is a known member of the TranscriptionProfile enum.
func (e TranscriptionProfile) Valid() bool {
	switch e {
	case Economy:
		return true
	case Quality:
		return true
	default:
		return false
	}
}

// Defines values for TranscriptionRunStatus.
const (
	TranscriptionRunStatusAligning     TranscriptionRunStatus = "aligning"
	TranscriptionRunStatusCanceled     TranscriptionRunStatus = "canceled"
	TranscriptionRunStatusCompleted    TranscriptionRunStatus = "completed"
	TranscriptionRunStatusDownloading  TranscriptionRunStatus = "downloading"
	TranscriptionRunStatusFailed       TranscriptionRunStatus = "failed"
	TranscriptionRunStatusMerging      TranscriptionRunStatus = "merging"
	TranscriptionRunStatusPreparing    TranscriptionRunStatus = "preparing"
	TranscriptionRunStatusQueued       TranscriptionRunStatus = "queued"
	TranscriptionRunStatusTranscribing TranscriptionRunStatus = "transcribing"
)

// Valid indicates whether the value is a known member of the TranscriptionRunStatus enum.
func (e TranscriptionRunStatus) Valid() bool {
	switch e {
	case TranscriptionRunStatusAligning:
		return true
	case TranscriptionRunStatusCanceled:
		return true
	case TranscriptionRunStatusCompleted:
		return true
	case TranscriptionRunStatusDownloading:
		return true
	case TranscriptionRunStatusFailed:
		return true
	case TranscriptionRunStatusMerging:
		return true
	case TranscriptionRunStatusPreparing:
		return true
	case TranscriptionRunStatusQueued:
		return true
	case TranscriptionRunStatusTranscribing:
		return true
	default:
		return false
	}
}

// AIArtifact defines model for AIArtifact.
type AIArtifact struct {
	ArtifactType        AIArtifactType    `json:"artifact_type"`
	CompletedAt         *time.Time        `json:"completed_at,omitempty"`
	CreatedAt           time.Time         `json:"created_at"`
	EpisodeId           string            `json:"episode_id"`
	ErrorCode           *string           `json:"error_code,omitempty"`
	ErrorMessage        *string           `json:"error_message,omitempty"`
	Id                  string            `json:"id"`
	InputTokens         int               `json:"input_tokens"`
	JobId               *string           `json:"job_id,omitempty"`
	Model               string            `json:"model"`
	OutputTokens        int               `json:"output_tokens"`
	PromptVersion       string            `json:"prompt_version"`
	Result              *AIArtifactResult `json:"result,omitempty"`
	Status              AIArtifactStatus  `json:"status"`
	TranscriptVersionId string            `json:"transcript_version_id"`
	UpdatedAt           time.Time         `json:"updated_at"`
}

// AIArtifactList defines model for AIArtifactList.
type AIArtifactList struct {
	Items []AIArtifact `json:"items"`
}

// AIArtifactResult defines model for AIArtifactResult.
type AIArtifactResult struct {
	KeyPoints          []string           `json:"key_points"`
	NoteConnections    []AINoteConnection `json:"note_connections"`
	OneSentenceSummary string             `json:"one_sentence_summary"`
	SpeakerViews       []AISpeakerView    `json:"speaker_views"`
	WorthReviewing     []AIWorthReviewing `json:"worth_reviewing"`
}

// AIArtifactStatus defines model for AIArtifactStatus.
type AIArtifactStatus string

// AIArtifactType defines model for AIArtifactType.
type AIArtifactType string

// AICitation defines model for AICitation.
type AICitation struct {
	EndMs       *int64               `json:"end_ms,omitempty"`
	Excerpt     string               `json:"excerpt"`
	SourceId    string               `json:"source_id"`
	SourceType  AICitationSourceType `json:"source_type"`
	SpeakerId   *string              `json:"speaker_id,omitempty"`
	SpeakerName *string              `json:"speaker_name,omitempty"`
	StartMs     *int64               `json:"start_ms,omitempty"`
}

// AICitationSourceType defines model for AICitation.SourceType.
type AICitationSourceType string

// AIMessageRole defines model for AIMessageRole.
type AIMessageRole string

// AIMessageStatus defines model for AIMessageStatus.
type AIMessageStatus string

// AINoteConnection defines model for AINoteConnection.
type AINoteConnection struct {
	Insight string `json:"insight"`
	Note    string `json:"note"`
	NoteId  string `json:"note_id"`
}

// AISpeakerView defines model for AISpeakerView.
type AISpeakerView struct {
	Points      []string `json:"points"`
	SpeakerId   string   `json:"speaker_id"`
	SpeakerName string   `json:"speaker_name"`
}

// AIWorthReviewing defines model for AIWorthReviewing.
type AIWorthReviewing struct {
	EndMs               int64  `json:"end_ms"`
	Quote               string `json:"quote"`
	Reason              string `json:"reason"`
	SpeakerId           string `json:"speaker_id"`
	SpeakerName         string `json:"speaker_name"`
	StartMs             int64  `json:"start_ms"`
	TranscriptSegmentId string `json:"transcript_segment_id"`
}

// CaptureResponse defines model for CaptureResponse.
type CaptureResponse struct {
	ImportId *string `json:"import_id,omitempty"`
	Note     Note    `json:"note"`
}

// Conversation defines model for Conversation.
type Conversation struct {
	CreatedAt    time.Time             `json:"created_at"`
	EpisodeId    *string               `json:"episode_id,omitempty"`
	EpisodeTitle string                `json:"episode_title"`
	Id           string                `json:"id"`
	Messages     []ConversationMessage `json:"messages"`
	Scope        ConversationScope     `json:"scope"`
	Title        string                `json:"title"`
	UpdatedAt    time.Time             `json:"updated_at"`
}

// ConversationMessage defines model for ConversationMessage.
type ConversationMessage struct {
	Citations        []AICitation    `json:"citations"`
	ClientMessageId  *string         `json:"client_message_id,omitempty"`
	CompletedAt      *time.Time      `json:"completed_at,omitempty"`
	Content          string          `json:"content"`
	CreatedAt        time.Time       `json:"created_at"`
	ErrorCode        *string         `json:"error_code,omitempty"`
	ErrorMessage     *string         `json:"error_message,omitempty"`
	Id               string          `json:"id"`
	InputTokens      int             `json:"input_tokens"`
	Model            *string         `json:"model,omitempty"`
	OutputTokens     int             `json:"output_tokens"`
	ReplyToMessageId *string         `json:"reply_to_message_id,omitempty"`
	Role             AIMessageRole   `json:"role"`
	Status           AIMessageStatus `json:"status"`
	UpdatedAt        time.Time       `json:"updated_at"`
}

// ConversationScope defines model for ConversationScope.
type ConversationScope string

// CreateCaptureRequest Exactly one of episode_id and episode_url must be supplied.
type CreateCaptureRequest struct {
	ClientNoteId string    `json:"client_note_id"`
	Content      string    `json:"content"`
	CreatedAt    time.Time `json:"created_at"`
	EpisodeId    *string   `json:"episode_id,omitempty"`
	EpisodeUrl   *string   `json:"episode_url,omitempty"`
}

// CreateConversationMessageRequest defines model for CreateConversationMessageRequest.
type CreateConversationMessageRequest struct {
	ClientMessageId string `json:"client_message_id"`
	Content         string `json:"content"`
}

// CreateConversationRequest defines model for CreateConversationRequest.
type CreateConversationRequest struct {
	EpisodeId string            `json:"episode_id"`
	Scope     ConversationScope `json:"scope"`
	Title     *string           `json:"title,omitempty"`
}

// CreateExportRequest defines model for CreateExportRequest.
type CreateExportRequest struct {
	// IncludeKeyPoints Organized-note option; defaults to true when omitted.
	IncludeKeyPoints *bool `json:"include_key_points,omitempty"`

	// IncludeSummary Organized-note option; defaults to true when omitted.
	IncludeSummary *bool `json:"include_summary,omitempty"`

	// IncludeTranscript Organized-note option. Includes the selected Segment IDs, or the first four active Transcript Segments when no IDs are supplied.
	IncludeTranscript *bool `json:"include_transcript,omitempty"`

	// IncludeUserNotes Organized-note option; defaults to true when omitted.
	IncludeUserNotes *bool `json:"include_user_notes,omitempty"`

	// IncludeWorthReviewing Organized-note option; defaults to true when omitted.
	IncludeWorthReviewing *bool      `json:"include_worth_reviewing,omitempty"`
	Mode                  ExportMode `json:"mode"`
	TranscriptSegmentIds  *[]string  `json:"transcript_segment_ids,omitempty"`
}

// CreateImportRequest defines model for CreateImportRequest.
type CreateImportRequest struct {
	Url string `json:"url"`
}

// CreateNoteRequest defines model for CreateNoteRequest.
type CreateNoteRequest struct {
	ClientNoteId string    `json:"client_note_id"`
	Content      string    `json:"content"`
	CreatedAt    time.Time `json:"created_at"`
}

// CreateTranscriptionRequest defines model for CreateTranscriptionRequest.
type CreateTranscriptionRequest struct {
	LanguageHint *string              `json:"language_hint,omitempty"`
	Profile      TranscriptionProfile `json:"profile"`
	SpeakerCount *int                 `json:"speaker_count,omitempty"`
}

// EpisodeDetail defines model for EpisodeDetail.
type EpisodeDetail struct {
	AiStatus            ProcessingStatus `json:"ai_status"`
	CoverUrl            string           `json:"cover_url"`
	CreatedAt           time.Time        `json:"created_at"`
	Description         string           `json:"description"`
	DurationMs          int64            `json:"duration_ms"`
	Id                  string           `json:"id"`
	Podcast             *PodcastSummary  `json:"podcast,omitempty"`
	PublishedAt         *time.Time       `json:"published_at,omitempty"`
	ResolveStatus       ResolveStatus    `json:"resolve_status"`
	SourceCount         int64            `json:"source_count"`
	Sources             []EpisodeSource  `json:"sources"`
	Title               string           `json:"title"`
	TranscriptionRunId  *string          `json:"transcription_run_id,omitempty"`
	TranscriptionStatus ProcessingStatus `json:"transcription_status"`
	UpdatedAt           time.Time        `json:"updated_at"`
}

// EpisodeListResponse defines model for EpisodeListResponse.
type EpisodeListResponse struct {
	Items  []EpisodeSummary `json:"items"`
	Limit  int              `json:"limit"`
	Offset int              `json:"offset"`
	Total  int64            `json:"total"`
}

// EpisodeSource defines model for EpisodeSource.
type EpisodeSource struct {
	CanonicalUrl string     `json:"canonical_url"`
	CreatedAt    time.Time  `json:"created_at"`
	ExternalId   *string    `json:"external_id,omitempty"`
	Id           string     `json:"id"`
	RssGuid      *string    `json:"rss_guid,omitempty"`
	SourceType   SourceType `json:"source_type"`
	SourceUrl    string     `json:"source_url"`
}

// EpisodeSummary defines model for EpisodeSummary.
type EpisodeSummary struct {
	AiStatus            ProcessingStatus `json:"ai_status"`
	CoverUrl            string           `json:"cover_url"`
	CreatedAt           time.Time        `json:"created_at"`
	DurationMs          int64            `json:"duration_ms"`
	Id                  string           `json:"id"`
	NoteCount           int64            `json:"note_count"`
	Podcast             *PodcastSummary  `json:"podcast,omitempty"`
	PublishedAt         *time.Time       `json:"published_at,omitempty"`
	ResolveStatus       ResolveStatus    `json:"resolve_status"`
	SourceCount         int64            `json:"source_count"`
	Title               string           `json:"title"`
	TranscriptionRunId  *string          `json:"transcription_run_id,omitempty"`
	TranscriptionStatus ProcessingStatus `json:"transcription_status"`
	UpdatedAt           time.Time        `json:"updated_at"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// ExportContent defines model for ExportContent.
type ExportContent struct {
	Markdown          string `json:"markdown"`
	SuggestedFilename string `json:"suggested_filename"`

	// Text Plain text suitable for Clipboard and the iOS Share Sheet.
	Text  string `json:"text"`
	Title string `json:"title"`
}

// ExportMode defines model for ExportMode.
type ExportMode string

// ImportError defines model for ImportError.
type ImportError struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// ImportResponse defines model for ImportResponse.
type ImportResponse struct {
	CreatedAt time.Time            `json:"created_at"`
	EpisodeId *string              `json:"episode_id,omitempty"`
	Error     *ImportError         `json:"error,omitempty"`
	Id        string               `json:"id"`
	Stage     string               `json:"stage"`
	Status    ImportResponseStatus `json:"status"`
	UpdatedAt time.Time            `json:"updated_at"`
	Url       string               `json:"url"`
}

// ImportResponseStatus defines model for ImportResponse.Status.
type ImportResponseStatus string

// MergeTranscriptSpeakersRequest defines model for MergeTranscriptSpeakersRequest.
type MergeTranscriptSpeakersRequest struct {
	SourceSpeakerId string `json:"source_speaker_id"`
	TargetSpeakerId string `json:"target_speaker_id"`
}

// Note defines model for Note.
type Note struct {
	ClientNoteId string     `json:"client_note_id"`
	Content      string     `json:"content"`
	CreatedAt    time.Time  `json:"created_at"`
	DeletedAt    *time.Time `json:"deleted_at,omitempty"`
	EpisodeId    string     `json:"episode_id"`
	Id           string     `json:"id"`
	UpdatedAt    time.Time  `json:"updated_at"`
}

// NoteListResponse defines model for NoteListResponse.
type NoteListResponse struct {
	Items []Note `json:"items"`
}

// PodcastSummary defines model for PodcastSummary.
type PodcastSummary struct {
	Author      string  `json:"author"`
	CoverUrl    string  `json:"cover_url"`
	Description string  `json:"description"`
	FeedUrl     *string `json:"feed_url,omitempty"`
	Id          string  `json:"id"`
	Title       string  `json:"title"`
}

// ProcessingStatus defines model for ProcessingStatus.
type ProcessingStatus string

// ReadinessResponse defines model for ReadinessResponse.
type ReadinessResponse struct {
	Database ReadinessResponseDatabase `json:"database"`
	Status   ReadinessResponseStatus   `json:"status"`
}

// ReadinessResponseDatabase defines model for ReadinessResponse.Database.
type ReadinessResponseDatabase string

// ReadinessResponseStatus defines model for ReadinessResponse.Status.
type ReadinessResponseStatus string

// ReindexSearchRequest defines model for ReindexSearchRequest.
type ReindexSearchRequest struct {
	EpisodeId *string     `json:"episode_id,omitempty"`
	Scope     SearchScope `json:"scope"`
}

// ReindexSearchResponse defines model for ReindexSearchResponse.
type ReindexSearchResponse struct {
	Queued int `json:"queued"`
}

// ResolveStatus defines model for ResolveStatus.
type ResolveStatus string

// SearchDocumentType defines model for SearchDocumentType.
type SearchDocumentType string

// SearchMode defines model for SearchMode.
type SearchMode string

// SearchResponse defines model for SearchResponse.
type SearchResponse struct {
	Items []SearchResult `json:"items"`
	Mode  SearchMode     `json:"mode"`
}

// SearchResult defines model for SearchResult.
type SearchResult struct {
	DocumentType SearchDocumentType `json:"document_type"`
	EndMs        *int64             `json:"end_ms,omitempty"`
	EpisodeId    string             `json:"episode_id"`
	EpisodeTitle string             `json:"episode_title"`
	Id           string             `json:"id"`
	PodcastTitle string             `json:"podcast_title"`
	Score        float64            `json:"score"`
	Snippet      string             `json:"snippet"`
	SourceId     string             `json:"source_id"`
	SpeakerId    *string            `json:"speaker_id,omitempty"`
	SpeakerName  *string            `json:"speaker_name,omitempty"`
	StartMs      *int64             `json:"start_ms,omitempty"`
}

// SearchScope defines model for SearchScope.
type SearchScope string

// SourceType defines model for SourceType.
type SourceType string

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	Status StatusResponseStatus `json:"status"`
}

// StatusResponseStatus defines model for StatusResponse.Status.
type StatusResponseStatus string

// Transcript defines model for Transcript.
type Transcript struct {
	CreatedAt          time.Time           `json:"created_at"`
	EpisodeId          string              `json:"episode_id"`
	Id                 string              `json:"id"`
	IsActive           bool                `json:"is_active"`
	Speakers           []TranscriptSpeaker `json:"speakers"`
	Status             string              `json:"status"`
	TranscriptionRunId string              `json:"transcription_run_id"`
	Version            int                 `json:"version"`
}

// TranscriptSegment defines model for TranscriptSegment.
type TranscriptSegment struct {
	EndMs         int64            `json:"end_ms"`
	Id            string           `json:"id"`
	Sequence      int              `json:"sequence"`
	SourceChunkId string           `json:"source_chunk_id"`
	SpeakerId     string           `json:"speaker_id"`
	StartMs       int64            `json:"start_ms"`
	Text          string           `json:"text"`
	Words         []TranscriptWord `json:"words"`
}

// TranscriptSegmentList defines model for TranscriptSegmentList.
type TranscriptSegmentList struct {
	Items  []TranscriptSegment `json:"items"`
	Limit  int                 `json:"limit"`
	Offset int                 `json:"offset"`
	Total  int64               `json:"total"`
}

// TranscriptSpeaker defines model for TranscriptSpeaker.
type TranscriptSpeaker struct {
	CreatedAt        time.Time `json:"created_at"`
	DisplayName      string    `json:"display_name"`
	Id               string    `json:"id"`
	Role             string    `json:"role"`
	SpeakerProfileId *string   `json:"speaker_profile_id,omitempty"`
	StableKey        string    `json:"stable_key"`
	UpdatedAt        time.Time `json:"updated_at"`
}

// TranscriptWord defines model for TranscriptWord.
type TranscriptWord struct {
	EndMs       int64   `json:"end_ms"`
	Punctuation *string `json:"punctuation,omitempty"`
	StartMs     int64   `json:"start_ms"`
	Text        string  `json:"text"`
}

// TranscriptionConfig defines model for TranscriptionConfig.
type TranscriptionConfig struct {
	LanguageHint *string `json:"language_hint,omitempty"`
	SpeakerCount *int    `json:"speaker_count,omitempty"`
}

// TranscriptionError defines model for TranscriptionError.
type TranscriptionError struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// TranscriptionProfile defines model for TranscriptionProfile.
type TranscriptionProfile string

// TranscriptionRun defines model for TranscriptionRun.
type TranscriptionRun struct {
	CompletedAt     *time.Time             `json:"completed_at,omitempty"`
	CompletedChunks int                    `json:"completed_chunks"`
	Config          TranscriptionConfig    `json:"config"`
	CreatedAt       time.Time              `json:"created_at"`
	DurationMs      *int64                 `json:"duration_ms,omitempty"`
	EpisodeId       string                 `json:"episode_id"`
	Error           *TranscriptionError    `json:"error,omitempty"`
	Id              string                 `json:"id"`
	Model           string                 `json:"model"`
	Profile         TranscriptionProfile   `json:"profile"`
	Provider        string                 `json:"provider"`
	Stage           string                 `json:"stage"`
	StartedAt       *time.Time             `json:"started_at,omitempty"`
	Status          TranscriptionRunStatus `json:"status"`
	TotalChunks     int                    `json:"total_chunks"`
	UpdatedAt       time.Time              `json:"updated_at"`
	WorkflowVersion int                    `json:"workflow_version"`
}

// TranscriptionRunStatus defines model for TranscriptionRunStatus.
type TranscriptionRunStatus string

// UpdateNoteRequest defines model for UpdateNoteRequest.
type UpdateNoteRequest struct {
	Content string `json:"content"`
}

// UpdateTranscriptSpeakerRequest defines model for UpdateTranscriptSpeakerRequest.
type UpdateTranscriptSpeakerRequest struct {
	DisplayName string  `json:"display_name"`
	Role        *string `json:"role,omitempty"`
}

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// PayloadTooLarge defines model for PayloadTooLarge.
type PayloadTooLarge = ErrorResponse

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = ErrorResponse

// ListEpisodesParams defines parameters for ListEpisodes.
type ListEpisodesParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// SearchContentParams defines parameters for SearchContent.
type SearchContentParams struct {
	Q         string       `form:"q" json:"q"`
	Scope     *SearchScope `form:"scope,omitempty" json:"scope,omitempty"`
	EpisodeId *string      `form:"episode_id,omitempty" json:"episode_id,omitempty"`
	Limit     *int         `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetTranscriptionEventsParams defines parameters for GetTranscriptionEvents.
type GetTranscriptionEventsParams struct {
	// LastEventID Return durable events after this event ID.
	LastEventID *int64 `json:"Last-Event-ID,omitempty"`
}

// ListTranscriptSegmentsParams defines parameters for ListTranscriptSegments.
type ListTranscriptSegmentsParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateCaptureJSONRequestBody defines body for CreateCapture for application/json ContentType.
type CreateCaptureJSONRequestBody = CreateCaptureRequest

// CreateConversationJSONRequestBody defines body for CreateConversation for application/json ContentType.
type CreateConversationJSONRequestBody = CreateConversationRequest

// StreamConversationMessageJSONRequestBody defines body for StreamConversationMessage for application/json ContentType.
type StreamConversationMessageJSONRequestBody = CreateConversationMessageRequest

// CreateEpisodeExportJSONRequestBody defines body for CreateEpisodeExport for application/json ContentType.
type CreateEpisodeExportJSONRequestBody = CreateExportRequest

// CreateEpisodeNoteJSONRequestBody defines body for CreateEpisodeNote for application/json ContentType.
type CreateEpisodeNoteJSONRequestBody = CreateNoteRequest

// CreateTranscriptionJSONRequestBody defines body for CreateTranscription for application/json ContentType.
type CreateTranscriptionJSONRequestBody = CreateTranscriptionRequest

// CreateImportJSONRequestBody defines body for CreateImport for application/json ContentType.
type CreateImportJSONRequestBody = CreateImportRequest

// UpdateNoteJSONRequestBody defines body for UpdateNote for application/json ContentType.
type UpdateNoteJSONRequestBody = UpdateNoteRequest

// ReindexSearchJSONRequestBody defines body for ReindexSearch for application/json ContentType.
type ReindexSearchJSONRequestBody = ReindexSearchRequest

// MergeTranscriptSpeakersJSONRequestBody defines body for MergeTranscriptSpeakers for application/json ContentType.
type MergeTranscriptSpeakersJSONRequestBody = MergeTranscriptSpeakersRequest

// UpdateTranscriptSpeakerJSONRequestBody defines body for UpdateTranscriptSpeaker for application/json ContentType.
type UpdateTranscriptSpeakerJSONRequestBody = UpdateTranscriptSpeakerRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// CreateCapture Capture a note for an Episode or URL
	// (POST /api/v1/captures)
	CreateCapture(w http.ResponseWriter, r *http.Request)
	// CreateConversation Create an Episode-scoped AI Conversation
	// (POST /api/v1/conversations)
	CreateConversation(w http.ResponseWriter, r *http.Request)
	// GetConversation Get a Conversation with durable Messages and Citations
	// (GET /api/v1/conversations/{conversationId})
	GetConversation(w http.ResponseWriter, r *http.Request, conversationId string)
	// StreamConversationMessage Ask an Episode question and stream a citation-validated answer
	// (POST /api/v1/conversations/{conversationId}/messages)
	StreamConversationMessage(w http.ResponseWriter, r *http.Request, conversationId string)
	// ListEpisodes List recently imported episodes
	// (GET /api/v1/episodes)
	ListEpisodes(w http.ResponseWriter, r *http.Request, params ListEpisodesParams)
	// DeleteEpisode Permanently delete an Episode
	// (DELETE /api/v1/episodes/{episodeId})
	DeleteEpisode(w http.ResponseWriter, r *http.Request, episodeId string)
	// GetEpisode Get an Episode with Podcast and Sources
	// (GET /api/v1/episodes/{episodeId})
	GetEpisode(w http.ResponseWriter, r *http.Request, episodeId string)
	// ListEpisodeAIArtifacts List cached and historical AI Artifacts for an Episode
	// (GET /api/v1/episodes/{episodeId}/ai/artifacts)
	ListEpisodeAIArtifacts(w http.ResponseWriter, r *http.Request, episodeId string)
	// RequestEpisodeAIArtifact Return a cached Episode summary or enqueue on-demand generation
	// (POST /api/v1/episodes/{episodeId}/ai/artifacts)
	RequestEpisodeAIArtifact(w http.ResponseWriter, r *http.Request, episodeId string)
	// CreateEpisodeExport Compose an Apple Notes share text and Markdown export
	// (POST /api/v1/episodes/{episodeId}/exports)
	CreateEpisodeExport(w http.ResponseWriter, r *http.Request, episodeId string)
	// ListEpisodeNotes List active Notes for an Episode
	// (GET /api/v1/episodes/{episodeId}/notes)
	ListEpisodeNotes(w http.ResponseWriter, r *http.Request, episodeId string)
	// CreateEpisodeNote Create an idempotent Note for an Episode
	// (POST /api/v1/episodes/{episodeId}/notes)
	CreateEpisodeNote(w http.ResponseWriter, r *http.Request, episodeId string)
	// GetEpisodeTranscript Get the active Transcript Version and Speakers
	// (GET /api/v1/episodes/{episodeId}/transcript)
	GetEpisodeTranscript(w http.ResponseWriter, r *http.Request, episodeId string)
	// CreateTranscription Start a versioned Episode transcription
	// (POST /api/v1/episodes/{episodeId}/transcriptions)
	CreateTranscription(w http.ResponseWriter, r *http.Request, episodeId string)
	// CreateImport Queue an episode import
	// (POST /api/v1/imports)
	CreateImport(w http.ResponseWriter, r *http.Request)
	// GetImport Get an import result
	// (GET /api/v1/imports/{importId})
	GetImport(w http.ResponseWriter, r *http.Request, importId string)
	// DeleteNote Soft-delete a Note
	// (DELETE /api/v1/notes/{noteId})
	DeleteNote(w http.ResponseWriter, r *http.Request, noteId string)
	// UpdateNote Update a Note
	// (PATCH /api/v1/notes/{noteId})
	UpdateNote(w http.ResponseWriter, r *http.Request, noteId string)
	// SearchContent Search Notes, Transcript, and indexed AI content
	// (GET /api/v1/search)
	SearchContent(w http.ResponseWriter, r *http.Request, params SearchContentParams)
	// ReindexSearch Enqueue an explicit Search index rebuild
	// (POST /api/v1/search/reindex)
	ReindexSearch(w http.ResponseWriter, r *http.Request)
	// GetTranscription Get transcription workflow state
	// (GET /api/v1/transcriptions/{runId})
	GetTranscription(w http.ResponseWriter, r *http.Request, runId string)
	// CancelTranscription Cancel local work and request cancellation of queued ASR tasks
	// (POST /api/v1/transcriptions/{runId}/cancel)
	CancelTranscription(w http.ResponseWriter, r *http.Request, runId string)
	// GetTranscriptionEvents Stream durable transcription events
	// (GET /api/v1/transcriptions/{runId}/events)
	GetTranscriptionEvents(w http.ResponseWriter, r *http.Request, runId string, params GetTranscriptionEventsParams)
	// RetryTranscription Retry only the failed transcription stage or chunks
	// (POST /api/v1/transcriptions/{runId}/retry)
	RetryTranscription(w http.ResponseWriter, r *http.Request, runId string)
	// ListTranscriptSegments List ordered Transcript Segments
	// (GET /api/v1/transcripts/{transcriptId}/segments)
	ListTranscriptSegments(w http.ResponseWriter, r *http.Request, transcriptId string, params ListTranscriptSegmentsParams)
	// MergeTranscriptSpeakers Merge one Global Speaker into another
	// (POST /api/v1/transcripts/{transcriptId}/speakers/merge)
	MergeTranscriptSpeakers(w http.ResponseWriter, r *http.Request, transcriptId string)
	// UpdateTranscriptSpeaker Rename a Global Speaker or update its role
	// (PATCH /api/v1/transcripts/{transcriptId}/speakers/{speakerId})
	UpdateTranscriptSpeaker(w http.ResponseWriter, r *http.Request, transcriptId string, speakerId string)
	// GetLiveness Process liveness
	// (GET /healthz)
	GetLiveness(w http.ResponseWriter, r *http.Request)
	// GetReadiness Dependency readiness
	// (GET /readyz)
	GetReadiness(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// CreateCapture Capture a note for an Episode or URL
// (POST /api/v1/captures)
func (_ Unimplemented) CreateCapture(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateConversation Create an Episode-scoped AI Conversation
// (POST /api/v1/conversations)
func (_ Unimplemented) CreateConversation(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetConversation Get a Conversation with durable Messages and Citations
// (GET /api/v1/conversations/{conversationId})
func (_ Unimplemented) GetConversation(w http.ResponseWriter, r *http.Request, conversationId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// StreamConversationMessage Ask an Episode question and stream a citation-validated answer
// (POST /api/v1/conversations/{conversationId}/messages)
func (_ Unimplemented) StreamConversationMessage(w http.ResponseWriter, r *http.Request, conversationId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListEpisodes List recently imported episodes
// (GET /api/v1/episodes)
func (_ Unimplemented) ListEpisodes(w http.ResponseWriter, r *http.Request, params ListEpisodesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteEpisode Permanently delete an Episode
// (DELETE /api/v1/episodes/{episodeId})
func (_ Unimplemented) DeleteEpisode(w http.ResponseWriter, r *http.Request, episodeId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetEpisode Get an Episode with Podcast and Sources
// (GET /api/v1/episodes/{episodeId})
func (_ Unimplemented) GetEpisode(w http.ResponseWriter, r *http.Request, episodeId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListEpisodeAIArtifacts List cached and historical AI Artifacts for an Episode
// (GET /api/v1/episodes/{episodeId}/ai/artifacts)
func (_ Unimplemented) ListEpisodeAIArtifacts(w http.ResponseWriter, r *http.Request, episodeId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// RequestEpisodeAIArtifact Return a cached Episode summary or enqueue on-demand generation
// (POST /api/v1/episodes/{episodeId}/ai/artifacts)
func (_ Unimplemented) RequestEpisodeAIArtifact(w http.ResponseWriter, r *http.Request, episodeId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateEpisodeExport Compose an Apple Notes share text and Markdown export
// (POST /api/v1/episodes/{episodeId}/exports)
func (_ Unimplemented) CreateEpisodeExport(w http.ResponseWriter, r *http.Request, episodeId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListEpisodeNotes List active Notes for an Episode
// (GET /api/v1/episodes/{episodeId}/notes)
func (_ Unimplemented) ListEpisodeNotes(w http.ResponseWriter, r *http.Request, episodeId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateEpisodeNote Create an idempotent Note for an Episode
// (POST /api/v1/episodes/{episodeId}/notes)
func (_ Unimplemented) CreateEpisodeNote(w http.ResponseWriter, r *http.Request, episodeId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetEpisodeTranscript Get the active Transcript Version and Speakers
// (GET /api/v1/episodes/{episodeId}/transcript)
func (_ Unimplemented) GetEpisodeTranscript(w http.ResponseWriter, r *http.Request, episodeId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateTranscription Start a versioned Episode transcription
// (POST /api/v1/episodes/{episodeId}/transcriptions)
func (_ Unimplemented) CreateTranscription(w http.ResponseWriter, r *http.Request, episodeId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateImport Queue an episode import
// (POST /api/v1/imports)
func (_ Unimplemented) CreateImport(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetImport Get an import result
// (GET /api/v1/imports/{importId})
func (_ Unimplemented) GetImport(w http.ResponseWriter, r *http.Request, importId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteNote Soft-delete a Note
// (DELETE /api/v1/notes/{noteId})
func (_ Unimplemented) DeleteNote(w http.ResponseWriter, r *http.Request, noteId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateNote Update a Note
// (PATCH /api/v1/notes/{noteId})
func (_ Unimplemented) UpdateNote(w http.ResponseWriter, r *http.Request, noteId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// SearchContent Search Notes, Transcript, and indexed AI content
// (GET /api/v1/search)
func (_ Unimplemented) SearchContent(w http.ResponseWriter, r *http.Request, params SearchContentParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ReindexSearch Enqueue an explicit Search index rebuild
// (POST /api/v1/search/reindex)
func (_ Unimplemented) ReindexSearch(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetTranscription Get transcription workflow state
// (GET /api/v1/transcriptions/{runId})
func (_ Unimplemented) GetTranscription(w http.ResponseWriter, r *http.Request, runId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CancelTranscription Cancel local work and request cancellation of queued ASR tasks
// (POST /api/v1/transcriptions/{runId}/cancel)
func (_ Unimplemented) CancelTranscription(w http.ResponseWriter, r *http.Request, runId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetTranscriptionEvents Stream durable transcription events
// (GET /api/v1/transcriptions/{runId}/events)
func (_ Unimplemented) GetTranscriptionEvents(w http.ResponseWriter, r *http.Request, runId string, params GetTranscriptionEventsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// RetryTranscription Retry only the failed transcription stage or chunks
// (POST /api/v1/transcriptions/{runId}/retry)
func (_ Unimplemented) RetryTranscription(w http.ResponseWriter, r *http.Request, runId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListTranscriptSegments List ordered Transcript Segments
// (GET /api/v1/transcripts/{transcriptId}/segments)
func (_ Unimplemented) ListTranscriptSegments(w http.ResponseWriter, r *http.Request, transcriptId string, params ListTranscriptSegmentsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// MergeTranscriptSpeakers Merge one Global Speaker into another
// (POST /api/v1/transcripts/{transcriptId}/speakers/merge)
func (_ Unimplemented) MergeTranscriptSpeakers(w http.ResponseWriter, r *http.Request, transcriptId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateTranscriptSpeaker Rename a Global Speaker or update its role
// (PATCH /api/v1/transcripts/{transcriptId}/speakers/{speakerId})
func (_ Unimplemented) UpdateTranscriptSpeaker(w http.ResponseWriter, r *http.Request, transcriptId string, speakerId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetLiveness Process liveness
// (GET /healthz)
func (_ Unimplemented) GetLiveness(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetReadiness Dependency readiness
// (GET /readyz)
func (_ Unimplemented) GetReadiness(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateCapture operation middleware
func (siw *ServerInterfaceWrapper) CreateCapture(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCapture(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateConversation operation middleware
func (siw *ServerInterfaceWrapper) CreateConversation(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateConversation(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetConversation operation middleware
func (siw *ServerInterfaceWrapper) GetConversation(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "conversationId" -------------
	var conversationId string

	err = runtime.BindStyledParameterWithOptions("simple", "conversationId", chi.URLParam(r, "conversationId"), &conversationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "conversationId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetConversation(w, r, conversationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StreamConversationMessage operation middleware
func (siw *ServerInterfaceWrapper) StreamConversationMessage(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "conversationId" -------------
	var conversationId string

	err = runtime.BindStyledParameterWithOptions("simple", "conversationId", chi.URLParam(r, "conversationId"), &conversationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "conversationId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StreamConversationMessage(w, r, conversationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListEpisodes operation middleware
func (siw *ServerInterfaceWrapper) ListEpisodes(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListEpisodesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListEpisodes(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteEpisode operation middleware
func (siw *ServerInterfaceWrapper) DeleteEpisode(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "episodeId" -------------
	var episodeId string

	err = runtime.BindStyledParameterWithOptions("simple", "episodeId", chi.URLParam(r, "episodeId"), &episodeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "episodeId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteEpisode(w, r, episodeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEpisode operation middleware
func (siw *ServerInterfaceWrapper) GetEpisode(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "episodeId" -------------
	var episodeId string

	err = runtime.BindStyledParameterWithOptions("simple", "episodeId", chi.URLParam(r, "episodeId"), &episodeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "episodeId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEpisode(w, r, episodeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListEpisodeAIArtifacts operation middleware
func (siw *ServerInterfaceWrapper) ListEpisodeAIArtifacts(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "episodeId" -------------
	var episodeId string

	err = runtime.BindStyledParameterWithOptions("simple", "episodeId", chi.URLParam(r, "episodeId"), &episodeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "episodeId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListEpisodeAIArtifacts(w, r, episodeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RequestEpisodeAIArtifact operation middleware
func (siw *ServerInterfaceWrapper) RequestEpisodeAIArtifact(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "episodeId" -------------
	var episodeId string

	err = runtime.BindStyledParameterWithOptions("simple", "episodeId", chi.URLParam(r, "episodeId"), &episodeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "episodeId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RequestEpisodeAIArtifact(w, r, episodeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateEpisodeExport operation middleware
func (siw *ServerInterfaceWrapper) CreateEpisodeExport(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "episodeId" -------------
	var episodeId string

	err = runtime.BindStyledParameterWithOptions("simple", "episodeId", chi.URLParam(r, "episodeId"), &episodeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "episodeId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateEpisodeExport(w, r, episodeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListEpisodeNotes operation middleware
func (siw *ServerInterfaceWrapper) ListEpisodeNotes(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "episodeId" -------------
	var episodeId string

	err = runtime.BindStyledParameterWithOptions("simple", "episodeId", chi.URLParam(r, "episodeId"), &episodeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "episodeId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListEpisodeNotes(w, r, episodeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateEpisodeNote operation middleware
func (siw *ServerInterfaceWrapper) CreateEpisodeNote(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "episodeId" -------------
	var episodeId string

	err = runtime.BindStyledParameterWithOptions("simple", "episodeId", chi.URLParam(r, "episodeId"), &episodeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "episodeId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateEpisodeNote(w, r, episodeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEpisodeTranscript operation middleware
func (siw *ServerInterfaceWrapper) GetEpisodeTranscript(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "episodeId" -------------
	var episodeId string

	err = runtime.BindStyledParameterWithOptions("simple", "episodeId", chi.URLParam(r, "episodeId"), &episodeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "episodeId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEpisodeTranscript(w, r, episodeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTranscription operation middleware
func (siw *ServerInterfaceWrapper) CreateTranscription(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "episodeId" -------------
	var episodeId string

	err = runtime.BindStyledParameterWithOptions("simple", "episodeId", chi.URLParam(r, "episodeId"), &episodeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "episodeId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTranscription(w, r, episodeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateImport operation middleware
func (siw *ServerInterfaceWrapper) CreateImport(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateImport(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetImport operation middleware
func (siw *ServerInterfaceWrapper) GetImport(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "importId" -------------
	var importId string

	err = runtime.BindStyledParameterWithOptions("simple", "importId", chi.URLParam(r, "importId"), &importId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "importId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetImport(w, r, importId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteNote operation middleware
func (siw *ServerInterfaceWrapper) DeleteNote(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "noteId" -------------
	var noteId string

	err = runtime.BindStyledParameterWithOptions("simple", "noteId", chi.URLParam(r, "noteId"), &noteId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "noteId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteNote(w, r, noteId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateNote operation middleware
func (siw *ServerInterfaceWrapper) UpdateNote(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "noteId" -------------
	var noteId string

	err = runtime.BindStyledParameterWithOptions("simple", "noteId", chi.URLParam(r, "noteId"), &noteId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "noteId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateNote(w, r, noteId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchContent operation middleware
func (siw *ServerInterfaceWrapper) SearchContent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchContentParams

	// ------------- Required query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "scope" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "scope", r.URL.Query(), &params.Scope, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "scope"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "scope", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "episode_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "episode_id", r.URL.Query(), &params.EpisodeId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "episode_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "episode_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchContent(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReindexSearch operation middleware
func (siw *ServerInterfaceWrapper) ReindexSearch(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReindexSearch(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTranscription operation middleware
func (siw *ServerInterfaceWrapper) GetTranscription(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "runId" -------------
	var runId string

	err = runtime.BindStyledParameterWithOptions("simple", "runId", chi.URLParam(r, "runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "runId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTranscription(w, r, runId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelTranscription operation middleware
func (siw *ServerInterfaceWrapper) CancelTranscription(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "runId" -------------
	var runId string

	err = runtime.BindStyledParameterWithOptions("simple", "runId", chi.URLParam(r, "runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "runId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelTranscription(w, r, runId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTranscriptionEvents operation middleware
func (siw *ServerInterfaceWrapper) GetTranscriptionEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "runId" -------------
	var runId string

	err = runtime.BindStyledParameterWithOptions("simple", "runId", chi.URLParam(r, "runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "runId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTranscriptionEventsParams

	headers := r.Header

	// ------------- Optional header parameter "Last-Event-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Last-Event-ID")]; found {
		var LastEventID int64
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Last-Event-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Last-Event-ID", valueList[0], &LastEventID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "integer", Format: "int64"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Last-Event-ID", Err: err})
			return
		}

		params.LastEventID = &LastEventID

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTranscriptionEvents(w, r, runId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RetryTranscription operation middleware
func (siw *ServerInterfaceWrapper) RetryTranscription(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "runId" -------------
	var runId string

	err = runtime.BindStyledParameterWithOptions("simple", "runId", chi.URLParam(r, "runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "runId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RetryTranscription(w, r, runId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTranscriptSegments operation middleware
func (siw *ServerInterfaceWrapper) ListTranscriptSegments(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "transcriptId" -------------
	var transcriptId string

	err = runtime.BindStyledParameterWithOptions("simple", "transcriptId", chi.URLParam(r, "transcriptId"), &transcriptId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "transcriptId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTranscriptSegmentsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTranscriptSegments(w, r, transcriptId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MergeTranscriptSpeakers operation middleware
func (siw *ServerInterfaceWrapper) MergeTranscriptSpeakers(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "transcriptId" -------------
	var transcriptId string

	err = runtime.BindStyledParameterWithOptions("simple", "transcriptId", chi.URLParam(r, "transcriptId"), &transcriptId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "transcriptId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MergeTranscriptSpeakers(w, r, transcriptId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTranscriptSpeaker operation middleware
func (siw *ServerInterfaceWrapper) UpdateTranscriptSpeaker(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "transcriptId" -------------
	var transcriptId string

	err = runtime.BindStyledParameterWithOptions("simple", "transcriptId", chi.URLParam(r, "transcriptId"), &transcriptId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "transcriptId", Err: err})
		return
	}

	// ------------- Path parameter "speakerId" -------------
	var speakerId string

	err = runtime.BindStyledParameterWithOptions("simple", "speakerId", chi.URLParam(r, "speakerId"), &speakerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "speakerId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTranscriptSpeaker(w, r, transcriptId, speakerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLiveness operation middleware
func (siw *ServerInterfaceWrapper) GetLiveness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLiveness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadiness operation middleware
func (siw *ServerInterfaceWrapper) GetReadiness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadiness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetLiveness)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/readyz", wrapper.GetReadiness)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/imports", wrapper.CreateImport)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/imports/{importId}", wrapper.GetImport)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/episodes", wrapper.ListEpisodes)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/episodes/{episodeId}", wrapper.DeleteEpisode)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/episodes/{episodeId}", wrapper.GetEpisode)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/captures", wrapper.CreateCapture)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/episodes/{episodeId}/notes", wrapper.ListEpisodeNotes)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/episodes/{episodeId}/notes", wrapper.CreateEpisodeNote)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/notes/{noteId}", wrapper.DeleteNote)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/v1/notes/{noteId}", wrapper.UpdateNote)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/search", wrapper.SearchContent)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/search/reindex", wrapper.ReindexSearch)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/episodes/{episodeId}/ai/artifacts", wrapper.ListEpisodeAIArtifacts)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/episodes/{episodeId}/ai/artifacts", wrapper.RequestEpisodeAIArtifact)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/episodes/{episodeId}/exports", wrapper.CreateEpisodeExport)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/conversations", wrapper.CreateConversation)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/conversations/{conversationId}", wrapper.GetConversation)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/conversations/{conversationId}/messages", wrapper.StreamConversationMessage)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/episodes/{episodeId}/transcriptions", wrapper.CreateTranscription)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/transcriptions/{runId}", wrapper.GetTranscription)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/transcriptions/{runId}/events", wrapper.GetTranscriptionEvents)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/transcriptions/{runId}/retry", wrapper.RetryTranscription)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/transcriptions/{runId}/cancel", wrapper.CancelTranscription)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/episodes/{episodeId}/transcript", wrapper.GetEpisodeTranscript)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/transcripts/{transcriptId}/segments", wrapper.ListTranscriptSegments)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/v1/transcripts/{transcriptId}/speakers/{speakerId}", wrapper.UpdateTranscriptSpeaker)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/transcripts/{transcriptId}/speakers/merge", wrapper.MergeTranscriptSpeakers)
	})

	return r
}
