/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Process liveness */
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dependency readiness */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a server-side session */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated user */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue an episode import */
        post: operations["createImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/{importId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an import result */
        get: operations["getImport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/episodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List recently imported episodes */
        get: operations["listEpisodes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/episodes/{episodeId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                episodeId: string;
            };
            cookie?: never;
        };
        /** Get an Episode with Podcast and Sources */
        get: operations["getEpisode"];
        put?: never;
        post?: never;
        /** Permanently delete an Episode */
        delete: operations["deleteEpisode"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/captures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Capture a note for an Episode or URL */
        post: operations["createCapture"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/episodes/{episodeId}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                episodeId: string;
            };
            cookie?: never;
        };
        /** List active Notes for an Episode */
        get: operations["listEpisodeNotes"];
        put?: never;
        /** Create an idempotent Note for an Episode */
        post: operations["createEpisodeNote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notes/{noteId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                noteId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Soft-delete a Note */
        delete: operations["deleteNote"];
        options?: never;
        head?: never;
        /** Update a Note */
        patch: operations["updateNote"];
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Notes, Transcript, and indexed AI content */
        get: operations["searchContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enqueue an explicit Search index rebuild */
        post: operations["reindexSearch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/episodes/{episodeId}/ai/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                episodeId: string;
            };
            cookie?: never;
        };
        /** List cached and historical AI Artifacts for an Episode */
        get: operations["listEpisodeAIArtifacts"];
        put?: never;
        /** Return a cached Episode summary or enqueue on-demand generation */
        post: operations["requestEpisodeAIArtifact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/episodes/{episodeId}/exports": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                episodeId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compose an Apple Notes share text and Markdown export */
        post: operations["createEpisodeExport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an Episode-scoped AI Conversation */
        post: operations["createConversation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{conversationId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversationId: string;
            };
            cookie?: never;
        };
        /** Get a Conversation with durable Messages and Citations */
        get: operations["getConversation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{conversationId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversationId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask an Episode question and stream a citation-validated answer */
        post: operations["streamConversationMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/episodes/{episodeId}/transcriptions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                episodeId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a versioned Episode transcription */
        post: operations["createTranscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transcriptions/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        /** Get transcription workflow state */
        get: operations["getTranscription"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transcriptions/{runId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        /** Stream durable transcription events */
        get: operations["getTranscriptionEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transcriptions/{runId}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry only the failed transcription stage or chunks */
        post: operations["retryTranscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transcriptions/{runId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel local work and request cancellation of queued ASR tasks */
        post: operations["cancelTranscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/episodes/{episodeId}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                episodeId: string;
            };
            cookie?: never;
        };
        /** Get the active Transcript Version and Speakers */
        get: operations["getEpisodeTranscript"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transcripts/{transcriptId}/segments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transcriptId: string;
            };
            cookie?: never;
        };
        /** List ordered Transcript Segments */
        get: operations["listTranscriptSegments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transcripts/{transcriptId}/speakers/{speakerId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transcriptId: string;
                speakerId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rename a Global Speaker or update its role */
        patch: operations["updateTranscriptSpeaker"];
        trace?: never;
    };
    "/api/v1/transcripts/{transcriptId}/speakers/merge": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transcriptId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Merge one Global Speaker into another */
        post: operations["mergeTranscriptSpeakers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginRequest: {
            username: string;
            password: string;
        };
        LoginResponse: {
            user: components["schemas"]["UserResponse"];
            /** Format: date-time */
            expires_at: string;
        };
        UserResponse: {
            id: string;
            username: string;
        };
        CreateImportRequest: {
            url: string;
        };
        ImportResponse: {
            id: string;
            url: string;
            /** @enum {string} */
            status: "queued" | "running" | "succeeded" | "failed" | "canceled";
            stage: string;
            episode_id?: string;
            error?: components["schemas"]["ImportError"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ImportError: {
            code: string;
            message: string;
        };
        ErrorResponse: {
            code: string;
            message: string;
        };
        /** @description Exactly one of episode_id and episode_url must be supplied. */
        CreateCaptureRequest: {
            client_note_id: string;
            episode_id?: string;
            episode_url?: string;
            content: string;
            /** Format: date-time */
            created_at: string;
        };
        CreateNoteRequest: {
            client_note_id: string;
            content: string;
            /** Format: date-time */
            created_at: string;
        };
        UpdateNoteRequest: {
            content: string;
        };
        Note: {
            id: string;
            episode_id: string;
            client_note_id: string;
            content: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            deleted_at?: string;
        };
        CaptureResponse: {
            note: components["schemas"]["Note"];
            import_id?: string;
        };
        NoteListResponse: {
            items: components["schemas"]["Note"][];
        };
        /** @enum {string} */
        SearchScope: "library" | "episode";
        /** @enum {string} */
        SearchMode: "keyword" | "hybrid";
        /** @enum {string} */
        SearchDocumentType: "note" | "transcript" | "ai_artifact";
        SearchResult: {
            id: string;
            document_type: components["schemas"]["SearchDocumentType"];
            source_id: string;
            episode_id: string;
            episode_title: string;
            podcast_title: string;
            speaker_id?: string;
            speaker_name?: string;
            /** Format: int64 */
            start_ms?: number;
            /** Format: int64 */
            end_ms?: number;
            snippet: string;
            /** Format: double */
            score: number;
        };
        SearchResponse: {
            items: components["schemas"]["SearchResult"][];
            mode: components["schemas"]["SearchMode"];
        };
        ReindexSearchRequest: {
            scope: components["schemas"]["SearchScope"];
            episode_id?: string;
        };
        ReindexSearchResponse: {
            queued: number;
        };
        /** @enum {string} */
        AIArtifactStatus: "queued" | "generating" | "ready" | "stale" | "failed";
        /** @enum {string} */
        AIArtifactType: "episode_summary";
        AISpeakerView: {
            speaker_id: string;
            speaker_name: string;
            points: string[];
        };
        AIWorthReviewing: {
            transcript_segment_id: string;
            speaker_id: string;
            speaker_name: string;
            /** Format: int64 */
            start_ms: number;
            /** Format: int64 */
            end_ms: number;
            quote: string;
            reason: string;
        };
        AINoteConnection: {
            note_id: string;
            note: string;
            insight: string;
        };
        AIArtifactResult: {
            one_sentence_summary: string;
            key_points: string[];
            speaker_views: components["schemas"]["AISpeakerView"][];
            worth_reviewing: components["schemas"]["AIWorthReviewing"][];
            note_connections: components["schemas"]["AINoteConnection"][];
        };
        AIArtifact: {
            id: string;
            episode_id: string;
            transcript_version_id: string;
            job_id?: string;
            artifact_type: components["schemas"]["AIArtifactType"];
            model: string;
            prompt_version: string;
            status: components["schemas"]["AIArtifactStatus"];
            result?: components["schemas"]["AIArtifactResult"];
            error_code?: string;
            error_message?: string;
            input_tokens: number;
            output_tokens: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            completed_at?: string;
        };
        AIArtifactList: {
            items: components["schemas"]["AIArtifact"][];
        };
        /** @enum {string} */
        ConversationScope: "episode" | "library";
        CreateConversationRequest: {
            scope: components["schemas"]["ConversationScope"];
            episode_id: string;
            title?: string;
        };
        CreateConversationMessageRequest: {
            client_message_id: string;
            content: string;
        };
        /** @enum {string} */
        AIMessageStatus: "streaming" | "completed" | "failed";
        /** @enum {string} */
        AIMessageRole: "user" | "assistant";
        AICitation: {
            /** @enum {string} */
            source_type: "transcript" | "note";
            source_id: string;
            excerpt: string;
            speaker_id?: string;
            speaker_name?: string;
            /** Format: int64 */
            start_ms?: number;
            /** Format: int64 */
            end_ms?: number;
        };
        ConversationMessage: {
            id: string;
            reply_to_message_id?: string;
            client_message_id?: string;
            role: components["schemas"]["AIMessageRole"];
            status: components["schemas"]["AIMessageStatus"];
            content: string;
            model?: string;
            error_code?: string;
            error_message?: string;
            citations: components["schemas"]["AICitation"][];
            input_tokens: number;
            output_tokens: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            completed_at?: string;
        };
        Conversation: {
            id: string;
            episode_id?: string;
            scope: components["schemas"]["ConversationScope"];
            title: string;
            episode_title: string;
            messages: components["schemas"]["ConversationMessage"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** @enum {string} */
        ExportMode: "notes_only" | "organized_note" | "selected_transcript" | "full_transcript";
        CreateExportRequest: {
            mode: components["schemas"]["ExportMode"];
            /** @description Organized-note option; defaults to true when omitted. */
            include_user_notes?: boolean;
            /** @description Organized-note option; defaults to true when omitted. */
            include_summary?: boolean;
            /** @description Organized-note option; defaults to true when omitted. */
            include_key_points?: boolean;
            /** @description Organized-note option; defaults to true when omitted. */
            include_worth_reviewing?: boolean;
            /** @description Organized-note option. Includes the selected Segment IDs, or the first four active Transcript Segments when no IDs are supplied. */
            include_transcript?: boolean;
            transcript_segment_ids?: string[];
        };
        ExportContent: {
            title: string;
            /** @description Plain text suitable for Clipboard and the iOS Share Sheet. */
            text: string;
            markdown: string;
            suggested_filename: string;
        };
        /** @enum {string} */
        TranscriptionProfile: "economy" | "quality";
        CreateTranscriptionRequest: {
            profile: components["schemas"]["TranscriptionProfile"];
            language_hint?: string;
            speaker_count?: number;
        };
        TranscriptionConfig: {
            language_hint?: string;
            speaker_count?: number;
        };
        /** @enum {string} */
        TranscriptionRunStatus: "queued" | "downloading" | "preparing" | "transcribing" | "aligning" | "merging" | "completed" | "failed" | "canceled";
        TranscriptionError: {
            code: string;
            message: string;
        };
        TranscriptionRun: {
            id: string;
            episode_id: string;
            profile: components["schemas"]["TranscriptionProfile"];
            provider: string;
            model: string;
            status: components["schemas"]["TranscriptionRunStatus"];
            stage: string;
            workflow_version: number;
            config: components["schemas"]["TranscriptionConfig"];
            /** Format: int64 */
            duration_ms?: number;
            total_chunks: number;
            completed_chunks: number;
            /** Format: date-time */
            started_at?: string;
            /** Format: date-time */
            completed_at?: string;
            error?: components["schemas"]["TranscriptionError"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        TranscriptSpeaker: {
            id: string;
            stable_key: string;
            display_name: string;
            role: string;
            speaker_profile_id?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Transcript: {
            id: string;
            episode_id: string;
            transcription_run_id: string;
            version: number;
            is_active: boolean;
            status: string;
            speakers: components["schemas"]["TranscriptSpeaker"][];
            /** Format: date-time */
            created_at: string;
        };
        TranscriptWord: {
            /** Format: int64 */
            start_ms: number;
            /** Format: int64 */
            end_ms: number;
            text: string;
            punctuation?: string;
        };
        TranscriptSegment: {
            id: string;
            speaker_id: string;
            sequence: number;
            /** Format: int64 */
            start_ms: number;
            /** Format: int64 */
            end_ms: number;
            text: string;
            words: components["schemas"]["TranscriptWord"][];
            source_chunk_id: string;
        };
        TranscriptSegmentList: {
            items: components["schemas"]["TranscriptSegment"][];
            /** Format: int64 */
            total: number;
            limit: number;
            offset: number;
        };
        UpdateTranscriptSpeakerRequest: {
            display_name: string;
            role?: string;
        };
        MergeTranscriptSpeakersRequest: {
            source_speaker_id: string;
            target_speaker_id: string;
        };
        /** @enum {string} */
        ResolveStatus: "pending" | "completed" | "failed";
        /** @enum {string} */
        ProcessingStatus: "waiting" | "queued" | "running" | "completed" | "failed";
        /** @enum {string} */
        SourceType: "apple_podcasts" | "rss" | "direct_audio";
        PodcastSummary: {
            id: string;
            title: string;
            author: string;
            description: string;
            cover_url: string;
            feed_url?: string;
        };
        EpisodeSummary: {
            id: string;
            podcast?: components["schemas"]["PodcastSummary"];
            title: string;
            /** Format: date-time */
            published_at?: string;
            /** Format: int64 */
            duration_ms: number;
            cover_url: string;
            resolve_status: components["schemas"]["ResolveStatus"];
            transcription_status: components["schemas"]["ProcessingStatus"];
            transcription_run_id?: string;
            ai_status: components["schemas"]["ProcessingStatus"];
            /** Format: int64 */
            source_count: number;
            /** Format: int64 */
            note_count: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        EpisodeSource: {
            id: string;
            source_type: components["schemas"]["SourceType"];
            external_id?: string;
            source_url: string;
            canonical_url: string;
            rss_guid?: string;
            /** Format: date-time */
            created_at: string;
        };
        EpisodeDetail: {
            id: string;
            podcast?: components["schemas"]["PodcastSummary"];
            title: string;
            description: string;
            /** Format: date-time */
            published_at?: string;
            /** Format: int64 */
            duration_ms: number;
            cover_url: string;
            resolve_status: components["schemas"]["ResolveStatus"];
            transcription_status: components["schemas"]["ProcessingStatus"];
            transcription_run_id?: string;
            ai_status: components["schemas"]["ProcessingStatus"];
            /** Format: int64 */
            source_count: number;
            sources: components["schemas"]["EpisodeSource"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        EpisodeListResponse: {
            items: components["schemas"]["EpisodeSummary"][];
            /** Format: int64 */
            total: number;
            limit: number;
            offset: number;
        };
        StatusResponse: {
            /** @enum {string} */
            status: "ok";
        };
        ReadinessResponse: {
            /** @enum {string} */
            status: "ok" | "unavailable";
            /** @enum {string} */
            database: "up" | "down";
        };
    };
    responses: {
        /** @description Invalid request. */
        BadRequest: {
            headers: {
                "X-Request-ID": components["headers"]["RequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description A valid Session is required. */
        Unauthorized: {
            headers: {
                "X-Request-ID": components["headers"]["RequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The request Origin is not allowed. */
        Forbidden: {
            headers: {
                "X-Request-ID": components["headers"]["RequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                "X-Request-ID": components["headers"]["RequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource state conflicts with the request. */
        Conflict: {
            headers: {
                "X-Request-ID": components["headers"]["RequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Generated content exceeds the synchronous export limit. */
        PayloadTooLarge: {
            headers: {
                "X-Request-ID": components["headers"]["RequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Required provider configuration is unavailable. */
        ServiceUnavailable: {
            headers: {
                "X-Request-ID": components["headers"]["RequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Internal server error. */
        InternalError: {
            headers: {
                "X-Request-ID": components["headers"]["RequestID"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: {
        /** @description Request correlation identifier. */
        RequestID: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The API process is running. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The API and PostgreSQL are ready. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description PostgreSQL is unavailable. */
            503: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login succeeded and a Session Cookie was set. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked and Cookie cleared. */
            204: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user and Session expiry. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createImport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateImportRequest"];
            };
        };
        responses: {
            /** @description Import queued. */
            202: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    getImport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                importId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Import state and resolved Episode when available. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listEpisodes: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User-scoped Episode page. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EpisodeListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    getEpisode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                episodeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Episode detail. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EpisodeDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteEpisode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                episodeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Episode deleted. */
            204: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    createCapture: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCaptureRequest"];
            };
        };
        responses: {
            /** @description Idempotent replay of an existing capture. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureResponse"];
                };
            };
            /** @description Capture created; URL captures also queue an Import. */
            201: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listEpisodeNotes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                episodeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Notes ordered by client creation time, newest first. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    createEpisodeNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                episodeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateNoteRequest"];
            };
        };
        responses: {
            /** @description Idempotent replay of an existing Note. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
            /** @description Note created. */
            201: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                noteId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Note deleted or already deleted. */
            204: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    updateNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                noteId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNoteRequest"];
            };
        };
        responses: {
            /** @description Note updated. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    searchContent: {
        parameters: {
            query: {
                q: string;
                scope?: components["schemas"]["SearchScope"];
                episode_id?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ranked keyword or hybrid search results. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    reindexSearch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReindexSearchRequest"];
            };
        };
        responses: {
            /** @description Rebuild Jobs were queued. */
            202: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReindexSearchResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listEpisodeAIArtifacts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                episodeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description AI Artifact history, newest first. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIArtifactList"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    requestEpisodeAIArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                episodeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description An input-identical cached Artifact was returned. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIArtifact"];
                };
            };
            /** @description Generation is queued or already in progress. */
            202: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIArtifact"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    createEpisodeExport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                episodeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateExportRequest"];
            };
        };
        responses: {
            /** @description Stateless export content generated from a consistent Episode snapshot. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportContent"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["PayloadTooLarge"];
            500: components["responses"]["InternalError"];
        };
    };
    createConversation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConversationRequest"];
            };
        };
        responses: {
            /** @description Conversation created. */
            201: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    getConversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conversation detail. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    streamConversationMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConversationMessageRequest"];
            };
        };
        responses: {
            /** @description SSE events. delta data is {"text":"..."}; citation data is an AICitation; done data is {"message_id":"...","replayed":false}; error data is the standard APIError object. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    createTranscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                episodeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTranscriptionRequest"];
            };
        };
        responses: {
            /** @description Transcription queued. */
            202: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptionRun"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getTranscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transcription workflow state. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptionRun"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getTranscriptionEvents: {
        parameters: {
            query?: never;
            header?: {
                /** @description Return durable events after this event ID. */
                "Last-Event-ID"?: number;
            };
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE events. Event IDs can be resumed with Last-Event-ID. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    retryTranscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Failed work queued again. */
            202: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptionRun"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    cancelTranscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current run state after cancellation request. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptionRun"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getEpisodeTranscript: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                episodeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active Transcript Version. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transcript"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listTranscriptSegments: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                transcriptId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ordered Segment page. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptSegmentList"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    updateTranscriptSpeaker: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transcriptId: string;
                speakerId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTranscriptSpeakerRequest"];
            };
        };
        responses: {
            /** @description Updated Speaker. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptSpeaker"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    mergeTranscriptSpeakers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transcriptId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MergeTranscriptSpeakersRequest"];
            };
        };
        responses: {
            /** @description Target Speaker after merge. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptSpeaker"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
}
