// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ai.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachAIArtifactJob = `-- name: AttachAIArtifactJob :one
UPDATE ai_artifacts
SET job_id = $1,
    updated_at = now()
WHERE id = $2
  AND user_id = $3
  AND status = 'queued'
RETURNING id, user_id, episode_id, transcript_version_id, job_id, artifact_type, model, prompt_version, notes_revision, input_hash, status, result, search_text, error_code, error_message, input_tokens, output_tokens, created_at, updated_at, completed_at
`

type AttachAIArtifactJobParams struct {
	JobID      pgtype.UUID `json:"job_id"`
	ArtifactID pgtype.UUID `json:"artifact_id"`
	UserID     pgtype.UUID `json:"user_id"`
}

func (q *Queries) AttachAIArtifactJob(ctx context.Context, arg AttachAIArtifactJobParams) (AiArtifact, error) {
	row := q.db.QueryRow(ctx, attachAIArtifactJob, arg.JobID, arg.ArtifactID, arg.UserID)
	var i AiArtifact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EpisodeID,
		&i.TranscriptVersionID,
		&i.JobID,
		&i.ArtifactType,
		&i.Model,
		&i.PromptVersion,
		&i.NotesRevision,
		&i.InputHash,
		&i.Status,
		&i.Result,
		&i.SearchText,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const cancelEpisodeAIJobsExcept = `-- name: CancelEpisodeAIJobsExcept :many
UPDATE jobs AS job
SET status = 'canceled',
    stage = 'canceled',
    locked_by = NULL,
    locked_at = NULL,
    error_code = NULL,
    error_message = NULL,
    updated_at = now(),
    completed_at = now()
WHERE job.user_id = $1
  AND job.type = 'generate_ai_artifact'
  AND job.status IN ('queued', 'running')
  AND job.entity_type = 'ai_artifact'
  AND job.entity_id IN (
      SELECT artifact.id
      FROM ai_artifacts AS artifact
      WHERE artifact.user_id = $1
        AND artifact.episode_id = $2
        AND ($3::uuid IS NULL OR artifact.id <> $3::uuid)
  )
RETURNING job.id, job.user_id, job.type, job.entity_type, job.entity_id, job.payload, job.status, job.stage, job.priority, job.attempt, job.max_attempts, job.run_after, job.locked_by, job.locked_at, job.error_code, job.error_message, job.created_at, job.updated_at, job.completed_at
`

type CancelEpisodeAIJobsExceptParams struct {
	UserID           pgtype.UUID `json:"user_id"`
	EpisodeID        pgtype.UUID `json:"episode_id"`
	ExceptArtifactID pgtype.UUID `json:"except_artifact_id"`
}

func (q *Queries) CancelEpisodeAIJobsExcept(ctx context.Context, arg CancelEpisodeAIJobsExceptParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, cancelEpisodeAIJobsExcept, arg.UserID, arg.EpisodeID, arg.ExceptArtifactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.EntityType,
			&i.EntityID,
			&i.Payload,
			&i.Status,
			&i.Stage,
			&i.Priority,
			&i.Attempt,
			&i.MaxAttempts,
			&i.RunAfter,
			&i.LockedBy,
			&i.LockedAt,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeAIArtifact = `-- name: CompleteAIArtifact :one
UPDATE ai_artifacts
SET status = 'ready',
    result = $1::jsonb,
    search_text = $2,
    error_code = NULL,
    error_message = NULL,
    input_tokens = $3,
    output_tokens = $4,
    completed_at = now(),
    updated_at = now()
WHERE id = $5
  AND user_id = $6
  AND input_hash = $7
  AND status = 'generating'
RETURNING id, user_id, episode_id, transcript_version_id, job_id, artifact_type, model, prompt_version, notes_revision, input_hash, status, result, search_text, error_code, error_message, input_tokens, output_tokens, created_at, updated_at, completed_at
`

type CompleteAIArtifactParams struct {
	Result       []byte      `json:"result"`
	SearchText   string      `json:"search_text"`
	InputTokens  int32       `json:"input_tokens"`
	OutputTokens int32       `json:"output_tokens"`
	ArtifactID   pgtype.UUID `json:"artifact_id"`
	UserID       pgtype.UUID `json:"user_id"`
	InputHash    string      `json:"input_hash"`
}

func (q *Queries) CompleteAIArtifact(ctx context.Context, arg CompleteAIArtifactParams) (AiArtifact, error) {
	row := q.db.QueryRow(ctx, completeAIArtifact,
		arg.Result,
		arg.SearchText,
		arg.InputTokens,
		arg.OutputTokens,
		arg.ArtifactID,
		arg.UserID,
		arg.InputHash,
	)
	var i AiArtifact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EpisodeID,
		&i.TranscriptVersionID,
		&i.JobID,
		&i.ArtifactType,
		&i.Model,
		&i.PromptVersion,
		&i.NotesRevision,
		&i.InputHash,
		&i.Status,
		&i.Result,
		&i.SearchText,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const completeAssistantMessage = `-- name: CompleteAssistantMessage :one
UPDATE messages AS message
SET status = 'completed',
    content = $1,
    input_tokens = $2,
    output_tokens = $3,
    error_code = NULL,
    error_message = NULL,
    completed_at = now(),
    updated_at = now()
FROM conversations AS conversation
WHERE message.id = $4
  AND conversation.id = message.conversation_id
  AND conversation.user_id = $5
  AND message.status = 'streaming'
RETURNING message.id, message.conversation_id, message.reply_to_message_id, message.client_message_id, message.role, message.status, message.content, message.model, message.error_code, message.error_message, message.input_tokens, message.output_tokens, message.created_at, message.updated_at, message.completed_at
`

type CompleteAssistantMessageParams struct {
	Content      string      `json:"content"`
	InputTokens  int32       `json:"input_tokens"`
	OutputTokens int32       `json:"output_tokens"`
	MessageID    pgtype.UUID `json:"message_id"`
	UserID       pgtype.UUID `json:"user_id"`
}

func (q *Queries) CompleteAssistantMessage(ctx context.Context, arg CompleteAssistantMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, completeAssistantMessage,
		arg.Content,
		arg.InputTokens,
		arg.OutputTokens,
		arg.MessageID,
		arg.UserID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.ReplyToMessageID,
		&i.ClientMessageID,
		&i.Role,
		&i.Status,
		&i.Content,
		&i.Model,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createAIArtifact = `-- name: CreateAIArtifact :one
INSERT INTO ai_artifacts (
    user_id,
    episode_id,
    transcript_version_id,
    artifact_type,
    model,
    prompt_version,
    notes_revision,
    input_hash
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, user_id, episode_id, transcript_version_id, job_id, artifact_type, model, prompt_version, notes_revision, input_hash, status, result, search_text, error_code, error_message, input_tokens, output_tokens, created_at, updated_at, completed_at
`

type CreateAIArtifactParams struct {
	UserID              pgtype.UUID `json:"user_id"`
	EpisodeID           pgtype.UUID `json:"episode_id"`
	TranscriptVersionID pgtype.UUID `json:"transcript_version_id"`
	ArtifactType        string      `json:"artifact_type"`
	Model               string      `json:"model"`
	PromptVersion       string      `json:"prompt_version"`
	NotesRevision       string      `json:"notes_revision"`
	InputHash           string      `json:"input_hash"`
}

func (q *Queries) CreateAIArtifact(ctx context.Context, arg CreateAIArtifactParams) (AiArtifact, error) {
	row := q.db.QueryRow(ctx, createAIArtifact,
		arg.UserID,
		arg.EpisodeID,
		arg.TranscriptVersionID,
		arg.ArtifactType,
		arg.Model,
		arg.PromptVersion,
		arg.NotesRevision,
		arg.InputHash,
	)
	var i AiArtifact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EpisodeID,
		&i.TranscriptVersionID,
		&i.JobID,
		&i.ArtifactType,
		&i.Model,
		&i.PromptVersion,
		&i.NotesRevision,
		&i.InputHash,
		&i.Status,
		&i.Result,
		&i.SearchText,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createAssistantMessage = `-- name: CreateAssistantMessage :one
INSERT INTO messages (
    conversation_id, reply_to_message_id, role, status, model
) VALUES (
    $1, $2, 'assistant', 'streaming', $3
)
RETURNING id, conversation_id, reply_to_message_id, client_message_id, role, status, content, model, error_code, error_message, input_tokens, output_tokens, created_at, updated_at, completed_at
`

type CreateAssistantMessageParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	UserMessageID  pgtype.UUID `json:"user_message_id"`
	Model          *string     `json:"model"`
}

func (q *Queries) CreateAssistantMessage(ctx context.Context, arg CreateAssistantMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createAssistantMessage, arg.ConversationID, arg.UserMessageID, arg.Model)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.ReplyToMessageID,
		&i.ClientMessageID,
		&i.Role,
		&i.Status,
		&i.Content,
		&i.Model,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (user_id, episode_id, scope, title)
VALUES ($1, $2::uuid, $3, $4)
RETURNING id, user_id, episode_id, scope, title, created_at, updated_at
`

type CreateConversationParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	EpisodeID pgtype.UUID `json:"episode_id"`
	Scope     string      `json:"scope"`
	Title     string      `json:"title"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation,
		arg.UserID,
		arg.EpisodeID,
		arg.Scope,
		arg.Title,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EpisodeID,
		&i.Scope,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMessageCitation = `-- name: CreateMessageCitation :one
INSERT INTO message_citations (
    message_id, position, transcript_segment_id, note_id, excerpt
) VALUES (
    $1,
    $2,
    $3::uuid,
    $4::uuid,
    $5
)
RETURNING id, message_id, position, transcript_segment_id, note_id, excerpt, created_at
`

type CreateMessageCitationParams struct {
	MessageID           pgtype.UUID `json:"message_id"`
	Position            int32       `json:"position"`
	TranscriptSegmentID pgtype.UUID `json:"transcript_segment_id"`
	NoteID              pgtype.UUID `json:"note_id"`
	Excerpt             string      `json:"excerpt"`
}

func (q *Queries) CreateMessageCitation(ctx context.Context, arg CreateMessageCitationParams) (MessageCitation, error) {
	row := q.db.QueryRow(ctx, createMessageCitation,
		arg.MessageID,
		arg.Position,
		arg.TranscriptSegmentID,
		arg.NoteID,
		arg.Excerpt,
	)
	var i MessageCitation
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.Position,
		&i.TranscriptSegmentID,
		&i.NoteID,
		&i.Excerpt,
		&i.CreatedAt,
	)
	return i, err
}

const createUserMessage = `-- name: CreateUserMessage :one
INSERT INTO messages (
    conversation_id, client_message_id, role, status, content, completed_at
) VALUES (
    $1, $2, 'user', 'completed', $3, now()
)
RETURNING id, conversation_id, reply_to_message_id, client_message_id, role, status, content, model, error_code, error_message, input_tokens, output_tokens, created_at, updated_at, completed_at
`

type CreateUserMessageParams struct {
	ConversationID  pgtype.UUID `json:"conversation_id"`
	ClientMessageID pgtype.UUID `json:"client_message_id"`
	Content         string      `json:"content"`
}

func (q *Queries) CreateUserMessage(ctx context.Context, arg CreateUserMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createUserMessage, arg.ConversationID, arg.ClientMessageID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.ReplyToMessageID,
		&i.ClientMessageID,
		&i.Role,
		&i.Status,
		&i.Content,
		&i.Model,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const failAIArtifact = `-- name: FailAIArtifact :one
UPDATE ai_artifacts
SET status = 'failed',
    error_code = $1,
    error_message = $2,
    completed_at = now(),
    updated_at = now()
WHERE id = $3
  AND user_id = $4
  AND status = 'generating'
RETURNING id, user_id, episode_id, transcript_version_id, job_id, artifact_type, model, prompt_version, notes_revision, input_hash, status, result, search_text, error_code, error_message, input_tokens, output_tokens, created_at, updated_at, completed_at
`

type FailAIArtifactParams struct {
	ErrorCode    *string     `json:"error_code"`
	ErrorMessage *string     `json:"error_message"`
	ArtifactID   pgtype.UUID `json:"artifact_id"`
	UserID       pgtype.UUID `json:"user_id"`
}

func (q *Queries) FailAIArtifact(ctx context.Context, arg FailAIArtifactParams) (AiArtifact, error) {
	row := q.db.QueryRow(ctx, failAIArtifact,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.ArtifactID,
		arg.UserID,
	)
	var i AiArtifact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EpisodeID,
		&i.TranscriptVersionID,
		&i.JobID,
		&i.ArtifactType,
		&i.Model,
		&i.PromptVersion,
		&i.NotesRevision,
		&i.InputHash,
		&i.Status,
		&i.Result,
		&i.SearchText,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const failAssistantMessage = `-- name: FailAssistantMessage :execrows
UPDATE messages AS message
SET status = 'failed',
    content = '',
    error_code = $1,
    error_message = $2,
    completed_at = now(),
    updated_at = now()
FROM conversations AS conversation
WHERE message.id = $3
  AND conversation.id = message.conversation_id
  AND conversation.user_id = $4
  AND message.status = 'streaming'
`

type FailAssistantMessageParams struct {
	ErrorCode    *string     `json:"error_code"`
	ErrorMessage *string     `json:"error_message"`
	MessageID    pgtype.UUID `json:"message_id"`
	UserID       pgtype.UUID `json:"user_id"`
}

func (q *Queries) FailAssistantMessage(ctx context.Context, arg FailAssistantMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, failAssistantMessage,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.MessageID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAIArtifactForJob = `-- name: GetAIArtifactForJob :one
SELECT id, user_id, episode_id, transcript_version_id, job_id, artifact_type, model, prompt_version, notes_revision, input_hash, status, result, search_text, error_code, error_message, input_tokens, output_tokens, created_at, updated_at, completed_at
FROM ai_artifacts
WHERE id = $1
  AND user_id = $2
  AND job_id = $3
`

type GetAIArtifactForJobParams struct {
	ArtifactID pgtype.UUID `json:"artifact_id"`
	UserID     pgtype.UUID `json:"user_id"`
	JobID      pgtype.UUID `json:"job_id"`
}

func (q *Queries) GetAIArtifactForJob(ctx context.Context, arg GetAIArtifactForJobParams) (AiArtifact, error) {
	row := q.db.QueryRow(ctx, getAIArtifactForJob, arg.ArtifactID, arg.UserID, arg.JobID)
	var i AiArtifact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EpisodeID,
		&i.TranscriptVersionID,
		&i.JobID,
		&i.ArtifactType,
		&i.Model,
		&i.PromptVersion,
		&i.NotesRevision,
		&i.InputHash,
		&i.Status,
		&i.Result,
		&i.SearchText,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getAssistantReply = `-- name: GetAssistantReply :one
SELECT message.id, message.conversation_id, message.reply_to_message_id, message.client_message_id, message.role, message.status, message.content, message.model, message.error_code, message.error_message, message.input_tokens, message.output_tokens, message.created_at, message.updated_at, message.completed_at
FROM messages AS message
JOIN conversations AS conversation ON conversation.id = message.conversation_id
WHERE message.reply_to_message_id = $1
  AND conversation.user_id = $2
  AND message.role = 'assistant'
`

type GetAssistantReplyParams struct {
	UserMessageID pgtype.UUID `json:"user_message_id"`
	UserID        pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetAssistantReply(ctx context.Context, arg GetAssistantReplyParams) (Message, error) {
	row := q.db.QueryRow(ctx, getAssistantReply, arg.UserMessageID, arg.UserID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.ReplyToMessageID,
		&i.ClientMessageID,
		&i.Role,
		&i.Status,
		&i.Content,
		&i.Model,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getCachedAIArtifact = `-- name: GetCachedAIArtifact :one
SELECT id, user_id, episode_id, transcript_version_id, job_id, artifact_type, model, prompt_version, notes_revision, input_hash, status, result, search_text, error_code, error_message, input_tokens, output_tokens, created_at, updated_at, completed_at
FROM ai_artifacts
WHERE user_id = $1
  AND episode_id = $2
  AND artifact_type = $3
  AND transcript_version_id = $4
  AND notes_revision = $5
  AND input_hash = $6
  AND model = $7
  AND prompt_version = $8
`

type GetCachedAIArtifactParams struct {
	UserID              pgtype.UUID `json:"user_id"`
	EpisodeID           pgtype.UUID `json:"episode_id"`
	ArtifactType        string      `json:"artifact_type"`
	TranscriptVersionID pgtype.UUID `json:"transcript_version_id"`
	NotesRevision       string      `json:"notes_revision"`
	InputHash           string      `json:"input_hash"`
	Model               string      `json:"model"`
	PromptVersion       string      `json:"prompt_version"`
}

func (q *Queries) GetCachedAIArtifact(ctx context.Context, arg GetCachedAIArtifactParams) (AiArtifact, error) {
	row := q.db.QueryRow(ctx, getCachedAIArtifact,
		arg.UserID,
		arg.EpisodeID,
		arg.ArtifactType,
		arg.TranscriptVersionID,
		arg.NotesRevision,
		arg.InputHash,
		arg.Model,
		arg.PromptVersion,
	)
	var i AiArtifact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EpisodeID,
		&i.TranscriptVersionID,
		&i.JobID,
		&i.ArtifactType,
		&i.Model,
		&i.PromptVersion,
		&i.NotesRevision,
		&i.InputHash,
		&i.Status,
		&i.Result,
		&i.SearchText,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getOwnedConversation = `-- name: GetOwnedConversation :one
SELECT conversation.id, conversation.user_id, conversation.episode_id, conversation.scope, conversation.title, conversation.created_at, conversation.updated_at, episode.title AS episode_title
FROM conversations AS conversation
LEFT JOIN episodes AS episode
    ON episode.id = conversation.episode_id
   AND episode.user_id = conversation.user_id
WHERE conversation.id = $1
  AND conversation.user_id = $2
`

type GetOwnedConversationParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

type GetOwnedConversationRow struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	EpisodeID    pgtype.UUID        `json:"episode_id"`
	Scope        string             `json:"scope"`
	Title        string             `json:"title"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	EpisodeTitle *string            `json:"episode_title"`
}

func (q *Queries) GetOwnedConversation(ctx context.Context, arg GetOwnedConversationParams) (GetOwnedConversationRow, error) {
	row := q.db.QueryRow(ctx, getOwnedConversation, arg.ConversationID, arg.UserID)
	var i GetOwnedConversationRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EpisodeID,
		&i.Scope,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EpisodeTitle,
	)
	return i, err
}

const getOwnedNoteEpisodeForAI = `-- name: GetOwnedNoteEpisodeForAI :one
SELECT episode_id
FROM notes
WHERE id = $1
  AND user_id = $2
`

type GetOwnedNoteEpisodeForAIParams struct {
	NoteID pgtype.UUID `json:"note_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetOwnedNoteEpisodeForAI(ctx context.Context, arg GetOwnedNoteEpisodeForAIParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getOwnedNoteEpisodeForAI, arg.NoteID, arg.UserID)
	var episode_id pgtype.UUID
	err := row.Scan(&episode_id)
	return episode_id, err
}

const getReadyAIArtifactForSearch = `-- name: GetReadyAIArtifactForSearch :one
SELECT id, search_text
FROM ai_artifacts
WHERE user_id = $1
  AND episode_id = $2
  AND artifact_type = 'episode_summary'
  AND status = 'ready'
ORDER BY updated_at DESC, id DESC
LIMIT 1
`

type GetReadyAIArtifactForSearchParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	EpisodeID pgtype.UUID `json:"episode_id"`
}

type GetReadyAIArtifactForSearchRow struct {
	ID         pgtype.UUID `json:"id"`
	SearchText string      `json:"search_text"`
}

func (q *Queries) GetReadyAIArtifactForSearch(ctx context.Context, arg GetReadyAIArtifactForSearchParams) (GetReadyAIArtifactForSearchRow, error) {
	row := q.db.QueryRow(ctx, getReadyAIArtifactForSearch, arg.UserID, arg.EpisodeID)
	var i GetReadyAIArtifactForSearchRow
	err := row.Scan(&i.ID, &i.SearchText)
	return i, err
}

const getUserMessageByClientID = `-- name: GetUserMessageByClientID :one
SELECT message.id, message.conversation_id, message.reply_to_message_id, message.client_message_id, message.role, message.status, message.content, message.model, message.error_code, message.error_message, message.input_tokens, message.output_tokens, message.created_at, message.updated_at, message.completed_at
FROM messages AS message
JOIN conversations AS conversation ON conversation.id = message.conversation_id
WHERE message.conversation_id = $1
  AND conversation.user_id = $2
  AND message.client_message_id = $3
  AND message.role = 'user'
`

type GetUserMessageByClientIDParams struct {
	ConversationID  pgtype.UUID `json:"conversation_id"`
	UserID          pgtype.UUID `json:"user_id"`
	ClientMessageID pgtype.UUID `json:"client_message_id"`
}

func (q *Queries) GetUserMessageByClientID(ctx context.Context, arg GetUserMessageByClientIDParams) (Message, error) {
	row := q.db.QueryRow(ctx, getUserMessageByClientID, arg.ConversationID, arg.UserID, arg.ClientMessageID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.ReplyToMessageID,
		&i.ClientMessageID,
		&i.Role,
		&i.Status,
		&i.Content,
		&i.Model,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listAINotesByIDs = `-- name: ListAINotesByIDs :many
SELECT note.id, note.user_id, note.episode_id, note.client_note_id, note.content, note.created_at, note.updated_at, note.deleted_at
FROM notes AS note
WHERE note.id = ANY($1::uuid[])
  AND note.user_id = $2
  AND note.episode_id = $3
  AND note.deleted_at IS NULL
ORDER BY note.created_at, note.id
`

type ListAINotesByIDsParams struct {
	NoteIds   []pgtype.UUID `json:"note_ids"`
	UserID    pgtype.UUID   `json:"user_id"`
	EpisodeID pgtype.UUID   `json:"episode_id"`
}

func (q *Queries) ListAINotesByIDs(ctx context.Context, arg ListAINotesByIDsParams) ([]Note, error) {
	rows, err := q.db.Query(ctx, listAINotesByIDs, arg.NoteIds, arg.UserID, arg.EpisodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EpisodeID,
			&i.ClientNoteID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAISegmentsForSearchChunks = `-- name: ListAISegmentsForSearchChunks :many
SELECT
    chunk.id AS search_chunk_id,
    segment.id,
    segment.speaker_id,
    speaker.display_name AS speaker_name,
    segment.start_ms,
    segment.end_ms,
    segment.text,
    segment.sequence
FROM search_chunks AS chunk
JOIN search_documents AS document ON document.id = chunk.search_document_id
JOIN transcript_segments AS segment
    ON segment.transcript_version_id = document.source_id
   AND segment.start_ms >= chunk.start_ms
   AND segment.end_ms <= chunk.end_ms
   AND segment.speaker_id = chunk.speaker_id
JOIN transcript_speakers AS speaker ON speaker.id = segment.speaker_id
WHERE chunk.id = ANY($1::uuid[])
  AND document.user_id = $2
  AND document.episode_id = $3
  AND document.document_type = 'transcript'
ORDER BY chunk.chunk_index, segment.sequence
`

type ListAISegmentsForSearchChunksParams struct {
	SearchChunkIds []pgtype.UUID `json:"search_chunk_ids"`
	UserID         pgtype.UUID   `json:"user_id"`
	EpisodeID      pgtype.UUID   `json:"episode_id"`
}

type ListAISegmentsForSearchChunksRow struct {
	SearchChunkID pgtype.UUID `json:"search_chunk_id"`
	ID            pgtype.UUID `json:"id"`
	SpeakerID     pgtype.UUID `json:"speaker_id"`
	SpeakerName   string      `json:"speaker_name"`
	StartMs       int64       `json:"start_ms"`
	EndMs         int64       `json:"end_ms"`
	Text          string      `json:"text"`
	Sequence      int32       `json:"sequence"`
}

func (q *Queries) ListAISegmentsForSearchChunks(ctx context.Context, arg ListAISegmentsForSearchChunksParams) ([]ListAISegmentsForSearchChunksRow, error) {
	rows, err := q.db.Query(ctx, listAISegmentsForSearchChunks, arg.SearchChunkIds, arg.UserID, arg.EpisodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAISegmentsForSearchChunksRow{}
	for rows.Next() {
		var i ListAISegmentsForSearchChunksRow
		if err := rows.Scan(
			&i.SearchChunkID,
			&i.ID,
			&i.SpeakerID,
			&i.SpeakerName,
			&i.StartMs,
			&i.EndMs,
			&i.Text,
			&i.Sequence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationCitations = `-- name: ListConversationCitations :many
SELECT
    citation.id, citation.message_id, citation.position, citation.transcript_segment_id, citation.note_id, citation.excerpt, citation.created_at,
    COALESCE(speaker.id, '00000000-0000-0000-0000-000000000000'::uuid) AS speaker_id,
    COALESCE(speaker.display_name, '') AS speaker_name,
    segment.start_ms,
    segment.end_ms
FROM message_citations AS citation
JOIN messages AS message ON message.id = citation.message_id
JOIN conversations AS conversation ON conversation.id = message.conversation_id
LEFT JOIN transcript_segments AS segment ON segment.id = citation.transcript_segment_id
LEFT JOIN transcript_speakers AS speaker ON speaker.id = segment.speaker_id
WHERE conversation.id = $1
  AND conversation.user_id = $2
ORDER BY message.created_at, citation.position
`

type ListConversationCitationsParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

type ListConversationCitationsRow struct {
	ID                  pgtype.UUID        `json:"id"`
	MessageID           pgtype.UUID        `json:"message_id"`
	Position            int32              `json:"position"`
	TranscriptSegmentID pgtype.UUID        `json:"transcript_segment_id"`
	NoteID              pgtype.UUID        `json:"note_id"`
	Excerpt             string             `json:"excerpt"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	SpeakerID           pgtype.UUID        `json:"speaker_id"`
	SpeakerName         string             `json:"speaker_name"`
	StartMs             *int64             `json:"start_ms"`
	EndMs               *int64             `json:"end_ms"`
}

func (q *Queries) ListConversationCitations(ctx context.Context, arg ListConversationCitationsParams) ([]ListConversationCitationsRow, error) {
	rows, err := q.db.Query(ctx, listConversationCitations, arg.ConversationID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConversationCitationsRow{}
	for rows.Next() {
		var i ListConversationCitationsRow
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.Position,
			&i.TranscriptSegmentID,
			&i.NoteID,
			&i.Excerpt,
			&i.CreatedAt,
			&i.SpeakerID,
			&i.SpeakerName,
			&i.StartMs,
			&i.EndMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationHistory = `-- name: ListConversationHistory :many
SELECT message.role, message.content
FROM messages AS message
JOIN conversations AS conversation ON conversation.id = message.conversation_id
LEFT JOIN messages AS parent ON parent.id = message.reply_to_message_id
WHERE message.conversation_id = $1
  AND conversation.user_id = $2
  AND message.status = 'completed'
  AND message.id <> $3
  AND (
      message.role = 'assistant'
      OR EXISTS (
          SELECT 1
          FROM messages AS reply
          WHERE reply.reply_to_message_id = message.id
            AND reply.role = 'assistant'
            AND reply.status = 'completed'
      )
  )
ORDER BY
    COALESCE(parent.created_at, message.created_at) DESC,
    CASE WHEN message.role = 'assistant' THEN 1 ELSE 0 END DESC,
    message.id DESC
LIMIT 20
`

type ListConversationHistoryParams struct {
	ConversationID       pgtype.UUID `json:"conversation_id"`
	UserID               pgtype.UUID `json:"user_id"`
	CurrentUserMessageID pgtype.UUID `json:"current_user_message_id"`
}

type ListConversationHistoryRow struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

func (q *Queries) ListConversationHistory(ctx context.Context, arg ListConversationHistoryParams) ([]ListConversationHistoryRow, error) {
	rows, err := q.db.Query(ctx, listConversationHistory, arg.ConversationID, arg.UserID, arg.CurrentUserMessageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConversationHistoryRow{}
	for rows.Next() {
		var i ListConversationHistoryRow
		if err := rows.Scan(&i.Role, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationMessages = `-- name: ListConversationMessages :many
SELECT message.id, message.conversation_id, message.reply_to_message_id, message.client_message_id, message.role, message.status, message.content, message.model, message.error_code, message.error_message, message.input_tokens, message.output_tokens, message.created_at, message.updated_at, message.completed_at
FROM messages AS message
JOIN conversations AS conversation ON conversation.id = message.conversation_id
LEFT JOIN messages AS parent ON parent.id = message.reply_to_message_id
WHERE message.conversation_id = $1
  AND conversation.user_id = $2
ORDER BY
    COALESCE(parent.created_at, message.created_at),
    CASE WHEN message.role = 'user' THEN 0 ELSE 1 END,
    message.id
`

type ListConversationMessagesParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

func (q *Queries) ListConversationMessages(ctx context.Context, arg ListConversationMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listConversationMessages, arg.ConversationID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.ReplyToMessageID,
			&i.ClientMessageID,
			&i.Role,
			&i.Status,
			&i.Content,
			&i.Model,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEpisodeAIArtifacts = `-- name: ListEpisodeAIArtifacts :many
SELECT id, user_id, episode_id, transcript_version_id, job_id, artifact_type, model, prompt_version, notes_revision, input_hash, status, result, search_text, error_code, error_message, input_tokens, output_tokens, created_at, updated_at, completed_at
FROM ai_artifacts
WHERE user_id = $1
  AND episode_id = $2
ORDER BY created_at DESC, id DESC
LIMIT 20
`

type ListEpisodeAIArtifactsParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	EpisodeID pgtype.UUID `json:"episode_id"`
}

func (q *Queries) ListEpisodeAIArtifacts(ctx context.Context, arg ListEpisodeAIArtifactsParams) ([]AiArtifact, error) {
	rows, err := q.db.Query(ctx, listEpisodeAIArtifacts, arg.UserID, arg.EpisodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiArtifact{}
	for rows.Next() {
		var i AiArtifact
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EpisodeID,
			&i.TranscriptVersionID,
			&i.JobID,
			&i.ArtifactType,
			&i.Model,
			&i.PromptVersion,
			&i.NotesRevision,
			&i.InputHash,
			&i.Status,
			&i.Result,
			&i.SearchText,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFallbackAINotes = `-- name: ListFallbackAINotes :many
SELECT note.id, note.user_id, note.episode_id, note.client_note_id, note.content, note.created_at, note.updated_at, note.deleted_at
FROM notes AS note
WHERE note.user_id = $1
  AND note.episode_id = $2
  AND note.deleted_at IS NULL
ORDER BY note.created_at DESC, note.id DESC
LIMIT $3::int
`

type ListFallbackAINotesParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	EpisodeID      pgtype.UUID `json:"episode_id"`
	CandidateLimit int32       `json:"candidate_limit"`
}

func (q *Queries) ListFallbackAINotes(ctx context.Context, arg ListFallbackAINotesParams) ([]Note, error) {
	rows, err := q.db.Query(ctx, listFallbackAINotes, arg.UserID, arg.EpisodeID, arg.CandidateLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EpisodeID,
			&i.ClientNoteID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFallbackAISegments = `-- name: ListFallbackAISegments :many
SELECT
    segment.id,
    segment.speaker_id,
    speaker.display_name AS speaker_name,
    segment.start_ms,
    segment.end_ms,
    segment.text,
    segment.sequence
FROM transcript_segments AS segment
JOIN transcript_versions AS version ON version.id = segment.transcript_version_id
JOIN transcript_speakers AS speaker ON speaker.id = segment.speaker_id
WHERE version.user_id = $1
  AND version.episode_id = $2
  AND version.is_active
ORDER BY segment.sequence
LIMIT $3::int
`

type ListFallbackAISegmentsParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	EpisodeID      pgtype.UUID `json:"episode_id"`
	CandidateLimit int32       `json:"candidate_limit"`
}

type ListFallbackAISegmentsRow struct {
	ID          pgtype.UUID `json:"id"`
	SpeakerID   pgtype.UUID `json:"speaker_id"`
	SpeakerName string      `json:"speaker_name"`
	StartMs     int64       `json:"start_ms"`
	EndMs       int64       `json:"end_ms"`
	Text        string      `json:"text"`
	Sequence    int32       `json:"sequence"`
}

func (q *Queries) ListFallbackAISegments(ctx context.Context, arg ListFallbackAISegmentsParams) ([]ListFallbackAISegmentsRow, error) {
	rows, err := q.db.Query(ctx, listFallbackAISegments, arg.UserID, arg.EpisodeID, arg.CandidateLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFallbackAISegmentsRow{}
	for rows.Next() {
		var i ListFallbackAISegmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.SpeakerID,
			&i.SpeakerName,
			&i.StartMs,
			&i.EndMs,
			&i.Text,
			&i.Sequence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOwnedConversation = `-- name: LockOwnedConversation :one
SELECT conversation.id, conversation.user_id, conversation.episode_id, conversation.scope, conversation.title, conversation.created_at, conversation.updated_at, episode.title AS episode_title
FROM conversations AS conversation
LEFT JOIN episodes AS episode
    ON episode.id = conversation.episode_id
   AND episode.user_id = conversation.user_id
WHERE conversation.id = $1
  AND conversation.user_id = $2
FOR UPDATE OF conversation
`

type LockOwnedConversationParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

type LockOwnedConversationRow struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	EpisodeID    pgtype.UUID        `json:"episode_id"`
	Scope        string             `json:"scope"`
	Title        string             `json:"title"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	EpisodeTitle *string            `json:"episode_title"`
}

func (q *Queries) LockOwnedConversation(ctx context.Context, arg LockOwnedConversationParams) (LockOwnedConversationRow, error) {
	row := q.db.QueryRow(ctx, lockOwnedConversation, arg.ConversationID, arg.UserID)
	var i LockOwnedConversationRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EpisodeID,
		&i.Scope,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EpisodeTitle,
	)
	return i, err
}

const lockOwnedEpisodeForAI = `-- name: LockOwnedEpisodeForAI :one
SELECT id, title
FROM episodes
WHERE id = $1
  AND user_id = $2
FOR UPDATE
`

type LockOwnedEpisodeForAIParams struct {
	EpisodeID pgtype.UUID `json:"episode_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

type LockOwnedEpisodeForAIRow struct {
	ID    pgtype.UUID `json:"id"`
	Title string      `json:"title"`
}

func (q *Queries) LockOwnedEpisodeForAI(ctx context.Context, arg LockOwnedEpisodeForAIParams) (LockOwnedEpisodeForAIRow, error) {
	row := q.db.QueryRow(ctx, lockOwnedEpisodeForAI, arg.EpisodeID, arg.UserID)
	var i LockOwnedEpisodeForAIRow
	err := row.Scan(&i.ID, &i.Title)
	return i, err
}

const markAIArtifactStale = `-- name: MarkAIArtifactStale :exec
UPDATE ai_artifacts
SET status = 'stale',
    updated_at = now()
WHERE id = $1
  AND user_id = $2
  AND status IN ('queued', 'generating', 'ready')
`

type MarkAIArtifactStaleParams struct {
	ArtifactID pgtype.UUID `json:"artifact_id"`
	UserID     pgtype.UUID `json:"user_id"`
}

func (q *Queries) MarkAIArtifactStale(ctx context.Context, arg MarkAIArtifactStaleParams) error {
	_, err := q.db.Exec(ctx, markAIArtifactStale, arg.ArtifactID, arg.UserID)
	return err
}

const markEpisodeAIArtifactsStale = `-- name: MarkEpisodeAIArtifactsStale :execrows
UPDATE ai_artifacts
SET status = 'stale',
    updated_at = now()
WHERE user_id = $1
  AND episode_id = $2
  AND status IN ('queued', 'generating', 'ready')
`

type MarkEpisodeAIArtifactsStaleParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	EpisodeID pgtype.UUID `json:"episode_id"`
}

func (q *Queries) MarkEpisodeAIArtifactsStale(ctx context.Context, arg MarkEpisodeAIArtifactsStaleParams) (int64, error) {
	result, err := q.db.Exec(ctx, markEpisodeAIArtifactsStale, arg.UserID, arg.EpisodeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markOtherAIArtifactsStale = `-- name: MarkOtherAIArtifactsStale :exec
UPDATE ai_artifacts
SET status = 'stale',
    updated_at = now()
WHERE user_id = $1
  AND episode_id = $2
  AND artifact_type = $3
  AND status IN ('queued', 'generating', 'ready')
  AND ($4::uuid IS NULL OR id <> $4::uuid)
`

type MarkOtherAIArtifactsStaleParams struct {
	UserID           pgtype.UUID `json:"user_id"`
	EpisodeID        pgtype.UUID `json:"episode_id"`
	ArtifactType     string      `json:"artifact_type"`
	ExceptArtifactID pgtype.UUID `json:"except_artifact_id"`
}

func (q *Queries) MarkOtherAIArtifactsStale(ctx context.Context, arg MarkOtherAIArtifactsStaleParams) error {
	_, err := q.db.Exec(ctx, markOtherAIArtifactsStale,
		arg.UserID,
		arg.EpisodeID,
		arg.ArtifactType,
		arg.ExceptArtifactID,
	)
	return err
}

const reactivateCachedAIArtifact = `-- name: ReactivateCachedAIArtifact :one
UPDATE ai_artifacts
SET status = 'ready',
    error_code = NULL,
    error_message = NULL,
    updated_at = now()
WHERE id = $1
  AND user_id = $2
  AND status = 'stale'
  AND result IS NOT NULL
  AND btrim(search_text) <> ''
RETURNING id, user_id, episode_id, transcript_version_id, job_id, artifact_type, model, prompt_version, notes_revision, input_hash, status, result, search_text, error_code, error_message, input_tokens, output_tokens, created_at, updated_at, completed_at
`

type ReactivateCachedAIArtifactParams struct {
	ArtifactID pgtype.UUID `json:"artifact_id"`
	UserID     pgtype.UUID `json:"user_id"`
}

func (q *Queries) ReactivateCachedAIArtifact(ctx context.Context, arg ReactivateCachedAIArtifactParams) (AiArtifact, error) {
	row := q.db.QueryRow(ctx, reactivateCachedAIArtifact, arg.ArtifactID, arg.UserID)
	var i AiArtifact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EpisodeID,
		&i.TranscriptVersionID,
		&i.JobID,
		&i.ArtifactType,
		&i.Model,
		&i.PromptVersion,
		&i.NotesRevision,
		&i.InputHash,
		&i.Status,
		&i.Result,
		&i.SearchText,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const reconcileFailedAIArtifacts = `-- name: ReconcileFailedAIArtifacts :execrows
UPDATE ai_artifacts AS artifact
SET status = 'failed',
    error_code = COALESCE(job.error_code, 'AI_JOB_FAILED'),
    error_message = COALESCE(job.error_message, 'AI generation job failed'),
    completed_at = COALESCE(job.completed_at, now()),
    updated_at = now()
FROM jobs AS job
WHERE artifact.user_id = $1
  AND artifact.episode_id = $2
  AND artifact.status IN ('queued', 'generating')
  AND job.id = artifact.job_id
  AND job.status = 'failed'
`

type ReconcileFailedAIArtifactsParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	EpisodeID pgtype.UUID `json:"episode_id"`
}

func (q *Queries) ReconcileFailedAIArtifacts(ctx context.Context, arg ReconcileFailedAIArtifactsParams) (int64, error) {
	result, err := q.db.Exec(ctx, reconcileFailedAIArtifacts, arg.UserID, arg.EpisodeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resetAIArtifactForGeneration = `-- name: ResetAIArtifactForGeneration :one
UPDATE ai_artifacts
SET status = 'queued',
    job_id = NULL,
    result = NULL,
    search_text = '',
    error_code = NULL,
    error_message = NULL,
    input_tokens = 0,
    output_tokens = 0,
    completed_at = NULL,
    updated_at = now()
WHERE id = $1
  AND user_id = $2
  AND status IN ('failed', 'stale')
RETURNING id, user_id, episode_id, transcript_version_id, job_id, artifact_type, model, prompt_version, notes_revision, input_hash, status, result, search_text, error_code, error_message, input_tokens, output_tokens, created_at, updated_at, completed_at
`

type ResetAIArtifactForGenerationParams struct {
	ArtifactID pgtype.UUID `json:"artifact_id"`
	UserID     pgtype.UUID `json:"user_id"`
}

func (q *Queries) ResetAIArtifactForGeneration(ctx context.Context, arg ResetAIArtifactForGenerationParams) (AiArtifact, error) {
	row := q.db.QueryRow(ctx, resetAIArtifactForGeneration, arg.ArtifactID, arg.UserID)
	var i AiArtifact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EpisodeID,
		&i.TranscriptVersionID,
		&i.JobID,
		&i.ArtifactType,
		&i.Model,
		&i.PromptVersion,
		&i.NotesRevision,
		&i.InputHash,
		&i.Status,
		&i.Result,
		&i.SearchText,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const setEpisodeAIStatus = `-- name: SetEpisodeAIStatus :exec
UPDATE episodes
SET ai_status = $1,
    updated_at = now()
WHERE id = $2
  AND user_id = $3
`

type SetEpisodeAIStatusParams struct {
	Status    string      `json:"status"`
	EpisodeID pgtype.UUID `json:"episode_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) SetEpisodeAIStatus(ctx context.Context, arg SetEpisodeAIStatusParams) error {
	_, err := q.db.Exec(ctx, setEpisodeAIStatus, arg.Status, arg.EpisodeID, arg.UserID)
	return err
}

const startAIArtifactGeneration = `-- name: StartAIArtifactGeneration :one
UPDATE ai_artifacts
SET status = 'generating',
    error_code = NULL,
    error_message = NULL,
    updated_at = now()
WHERE id = $1
  AND user_id = $2
  AND job_id = $3
  AND status IN ('queued', 'generating')
RETURNING id, user_id, episode_id, transcript_version_id, job_id, artifact_type, model, prompt_version, notes_revision, input_hash, status, result, search_text, error_code, error_message, input_tokens, output_tokens, created_at, updated_at, completed_at
`

type StartAIArtifactGenerationParams struct {
	ArtifactID pgtype.UUID `json:"artifact_id"`
	UserID     pgtype.UUID `json:"user_id"`
	JobID      pgtype.UUID `json:"job_id"`
}

func (q *Queries) StartAIArtifactGeneration(ctx context.Context, arg StartAIArtifactGenerationParams) (AiArtifact, error) {
	row := q.db.QueryRow(ctx, startAIArtifactGeneration, arg.ArtifactID, arg.UserID, arg.JobID)
	var i AiArtifact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EpisodeID,
		&i.TranscriptVersionID,
		&i.JobID,
		&i.ArtifactType,
		&i.Model,
		&i.PromptVersion,
		&i.NotesRevision,
		&i.InputHash,
		&i.Status,
		&i.Result,
		&i.SearchText,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const touchConversation = `-- name: TouchConversation :exec
UPDATE conversations
SET updated_at = now()
WHERE id = $1
  AND user_id = $2
`

type TouchConversationParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

func (q *Queries) TouchConversation(ctx context.Context, arg TouchConversationParams) error {
	_, err := q.db.Exec(ctx, touchConversation, arg.ConversationID, arg.UserID)
	return err
}
