// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const authenticateSession = `-- name: AuthenticateSession :one
UPDATE sessions AS session
SET last_seen_at = now()
FROM users AS app_user
WHERE session.token_hash = $1
  AND session.revoked_at IS NULL
  AND session.expires_at > now()
  AND app_user.id = session.user_id
  AND app_user.status = 'active'
RETURNING app_user.id AS user_id, app_user.username, session.expires_at
`

type AuthenticateSessionRow struct {
	UserID    pgtype.UUID        `json:"user_id"`
	Username  *string            `json:"username"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) AuthenticateSession(ctx context.Context, tokenHash []byte) (AuthenticateSessionRow, error) {
	row := q.db.QueryRow(ctx, authenticateSession, tokenHash)
	var i AuthenticateSessionRow
	err := row.Scan(&i.UserID, &i.Username, &i.ExpiresAt)
	return i, err
}

const claimUser = `-- name: ClaimUser :one
UPDATE users
SET username = $1,
    username_normalized = $2,
    password_hash = $3,
    status = 'active',
    updated_at = now()
WHERE id = $4
  AND status = 'placeholder'
RETURNING id, username, username_normalized, password_hash, status, created_at, updated_at
`

type ClaimUserParams struct {
	Username           *string     `json:"username"`
	UsernameNormalized *string     `json:"username_normalized"`
	PasswordHash       *string     `json:"password_hash"`
	UserID             pgtype.UUID `json:"user_id"`
}

func (q *Queries) ClaimUser(ctx context.Context, arg ClaimUserParams) (User, error) {
	row := q.db.QueryRow(ctx, claimUser,
		arg.Username,
		arg.UsernameNormalized,
		arg.PasswordHash,
		arg.UserID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.UsernameNormalized,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token_hash, expires_at)
VALUES (
    $1,
    $2,
    now() + ($3::bigint * interval '1 millisecond')
)
RETURNING id, user_id, token_hash, expires_at, revoked_at, created_at, last_seen_at
`

type CreateSessionParams struct {
	UserID                 pgtype.UUID `json:"user_id"`
	TokenHash              []byte      `json:"token_hash"`
	SessionTtlMilliseconds int64       `json:"session_ttl_milliseconds"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.TokenHash, arg.SessionTtlMilliseconds)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, username_normalized, password_hash, status)
VALUES ($1, $2, $3, 'active')
RETURNING id, username, username_normalized, password_hash, status, created_at, updated_at
`

type CreateUserParams struct {
	Username           *string `json:"username"`
	UsernameNormalized *string `json:"username_normalized"`
	PasswordHash       *string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.UsernameNormalized, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.UsernameNormalized,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ensurePlaceholderUser = `-- name: EnsurePlaceholderUser :exec
INSERT INTO users (id)
VALUES ($1)
ON CONFLICT (id) DO NOTHING
`

func (q *Queries) EnsurePlaceholderUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, ensurePlaceholderUser, userID)
	return err
}

const getUserForLogin = `-- name: GetUserForLogin :one
SELECT id, username, username_normalized, password_hash, status, created_at, updated_at
FROM users
WHERE username_normalized = $1
  AND status = 'active'
`

func (q *Queries) GetUserForLogin(ctx context.Context, usernameNormalized *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserForLogin, usernameNormalized)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.UsernameNormalized,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET revoked_at = COALESCE(revoked_at, now())
WHERE token_hash = $1
`

func (q *Queries) RevokeSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, revokeSession, tokenHash)
	return err
}

const revokeUserSessions = `-- name: RevokeUserSessions :exec
UPDATE sessions
SET revoked_at = COALESCE(revoked_at, now())
WHERE user_id = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeUserSessions(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeUserSessions, userID)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users
SET password_hash = $1,
    updated_at = now()
WHERE username_normalized = $2
  AND status = 'active'
RETURNING id, username, username_normalized, password_hash, status, created_at, updated_at
`

type UpdateUserPasswordParams struct {
	PasswordHash       *string `json:"password_hash"`
	UsernameNormalized *string `json:"username_normalized"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.PasswordHash, arg.UsernameNormalized)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.UsernameNormalized,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
