// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: export.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getReadyAIArtifactForExport = `-- name: GetReadyAIArtifactForExport :one
SELECT result
FROM ai_artifacts
WHERE user_id = $1
  AND episode_id = $2
  AND artifact_type = 'episode_summary'
  AND status = 'ready'
ORDER BY updated_at DESC, id DESC
LIMIT 1
`

type GetReadyAIArtifactForExportParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	EpisodeID pgtype.UUID `json:"episode_id"`
}

func (q *Queries) GetReadyAIArtifactForExport(ctx context.Context, arg GetReadyAIArtifactForExportParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getReadyAIArtifactForExport, arg.UserID, arg.EpisodeID)
	var result []byte
	err := row.Scan(&result)
	return result, err
}

const getTranscriptExportStats = `-- name: GetTranscriptExportStats :one
SELECT
    count(*)::int AS segment_count,
    COALESCE(sum(octet_length(candidate.text)), 0)::bigint AS content_bytes
FROM (
    SELECT segment.text
    FROM transcript_segments AS segment
    JOIN transcript_versions AS version ON version.id = segment.transcript_version_id
    WHERE segment.transcript_version_id = $1
      AND version.user_id = $2
      AND (
          cardinality($3::uuid[]) = 0
          OR segment.id = ANY($3::uuid[])
      )
    ORDER BY segment.sequence
    LIMIT $4::int
) AS candidate
`

type GetTranscriptExportStatsParams struct {
	TranscriptID pgtype.UUID   `json:"transcript_id"`
	UserID       pgtype.UUID   `json:"user_id"`
	SegmentIds   []pgtype.UUID `json:"segment_ids"`
	SegmentLimit int32         `json:"segment_limit"`
}

type GetTranscriptExportStatsRow struct {
	SegmentCount int32 `json:"segment_count"`
	ContentBytes int64 `json:"content_bytes"`
}

func (q *Queries) GetTranscriptExportStats(ctx context.Context, arg GetTranscriptExportStatsParams) (GetTranscriptExportStatsRow, error) {
	row := q.db.QueryRow(ctx, getTranscriptExportStats,
		arg.TranscriptID,
		arg.UserID,
		arg.SegmentIds,
		arg.SegmentLimit,
	)
	var i GetTranscriptExportStatsRow
	err := row.Scan(&i.SegmentCount, &i.ContentBytes)
	return i, err
}

const listTranscriptSegmentsForExport = `-- name: ListTranscriptSegmentsForExport :many
SELECT
    segment.id,
    speaker.display_name AS speaker_name,
    segment.start_ms,
    segment.text
FROM transcript_segments AS segment
JOIN transcript_versions AS version ON version.id = segment.transcript_version_id
JOIN transcript_speakers AS speaker ON speaker.id = segment.speaker_id
WHERE segment.transcript_version_id = $1
  AND version.user_id = $2
  AND (
      cardinality($3::uuid[]) = 0
      OR segment.id = ANY($3::uuid[])
  )
ORDER BY segment.sequence
LIMIT $4::int
`

type ListTranscriptSegmentsForExportParams struct {
	TranscriptID pgtype.UUID   `json:"transcript_id"`
	UserID       pgtype.UUID   `json:"user_id"`
	SegmentIds   []pgtype.UUID `json:"segment_ids"`
	SegmentLimit int32         `json:"segment_limit"`
}

type ListTranscriptSegmentsForExportRow struct {
	ID          pgtype.UUID `json:"id"`
	SpeakerName string      `json:"speaker_name"`
	StartMs     int64       `json:"start_ms"`
	Text        string      `json:"text"`
}

func (q *Queries) ListTranscriptSegmentsForExport(ctx context.Context, arg ListTranscriptSegmentsForExportParams) ([]ListTranscriptSegmentsForExportRow, error) {
	rows, err := q.db.Query(ctx, listTranscriptSegmentsForExport,
		arg.TranscriptID,
		arg.UserID,
		arg.SegmentIds,
		arg.SegmentLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTranscriptSegmentsForExportRow{}
	for rows.Next() {
		var i ListTranscriptSegmentsForExportRow
		if err := rows.Scan(
			&i.ID,
			&i.SpeakerName,
			&i.StartMs,
			&i.Text,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
