// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: imports.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireEpisodeIdentityLock = `-- name: AcquireEpisodeIdentityLock :exec
SELECT pg_advisory_xact_lock(hashtextextended($1, 0))
`

func (q *Queries) AcquireEpisodeIdentityLock(ctx context.Context, identityKey string) error {
	_, err := q.db.Exec(ctx, acquireEpisodeIdentityLock, identityKey)
	return err
}

const addEpisodeIdentityKey = `-- name: AddEpisodeIdentityKey :exec
INSERT INTO episode_identity_keys (user_id, identity_key, episode_id)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, identity_key) DO NOTHING
`

type AddEpisodeIdentityKeyParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	IdentityKey string      `json:"identity_key"`
	EpisodeID   pgtype.UUID `json:"episode_id"`
}

func (q *Queries) AddEpisodeIdentityKey(ctx context.Context, arg AddEpisodeIdentityKeyParams) error {
	_, err := q.db.Exec(ctx, addEpisodeIdentityKey, arg.UserID, arg.IdentityKey, arg.EpisodeID)
	return err
}

const addEpisodeSource = `-- name: AddEpisodeSource :exec
INSERT INTO episode_sources (
    user_id,
    episode_id,
    source_type,
    external_id,
    source_url,
    canonical_url,
    audio_url,
    rss_guid
) VALUES (
    $1,
    $2,
    $3,
    $4::text,
    $5,
    $6,
    $7,
    $8::text
)
ON CONFLICT (user_id, episode_id, source_type, source_url) DO NOTHING
`

type AddEpisodeSourceParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	EpisodeID    pgtype.UUID `json:"episode_id"`
	SourceType   string      `json:"source_type"`
	ExternalID   *string     `json:"external_id"`
	SourceUrl    string      `json:"source_url"`
	CanonicalUrl string      `json:"canonical_url"`
	AudioUrl     string      `json:"audio_url"`
	RssGuid      *string     `json:"rss_guid"`
}

func (q *Queries) AddEpisodeSource(ctx context.Context, arg AddEpisodeSourceParams) error {
	_, err := q.db.Exec(ctx, addEpisodeSource,
		arg.UserID,
		arg.EpisodeID,
		arg.SourceType,
		arg.ExternalID,
		arg.SourceUrl,
		arg.CanonicalUrl,
		arg.AudioUrl,
		arg.RssGuid,
	)
	return err
}

const createEpisode = `-- name: CreateEpisode :one
INSERT INTO episodes (
    user_id,
    podcast_id,
    title,
    description,
    published_at,
    duration_ms,
    cover_url,
    resolve_status
) VALUES (
    $1,
    $2::uuid,
    $3,
    $4,
    $5::timestamptz,
    $6,
    $7,
    'completed'
)
RETURNING id, user_id, podcast_id, title, description, published_at, duration_ms, cover_url, resolve_status, transcription_status, ai_status, created_at, updated_at
`

type CreateEpisodeParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	PodcastID   pgtype.UUID        `json:"podcast_id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	DurationMs  int64              `json:"duration_ms"`
	CoverUrl    string             `json:"cover_url"`
}

func (q *Queries) CreateEpisode(ctx context.Context, arg CreateEpisodeParams) (Episode, error) {
	row := q.db.QueryRow(ctx, createEpisode,
		arg.UserID,
		arg.PodcastID,
		arg.Title,
		arg.Description,
		arg.PublishedAt,
		arg.DurationMs,
		arg.CoverUrl,
	)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PodcastID,
		&i.Title,
		&i.Description,
		&i.PublishedAt,
		&i.DurationMs,
		&i.CoverUrl,
		&i.ResolveStatus,
		&i.TranscriptionStatus,
		&i.AiStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createImport = `-- name: CreateImport :one
INSERT INTO imports (user_id, submitted_url)
VALUES ($1, $2)
RETURNING id, user_id, submitted_url, job_id, episode_id, created_at, updated_at
`

type CreateImportParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	SubmittedUrl string      `json:"submitted_url"`
}

func (q *Queries) CreateImport(ctx context.Context, arg CreateImportParams) (Import, error) {
	row := q.db.QueryRow(ctx, createImport, arg.UserID, arg.SubmittedUrl)
	var i Import
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubmittedUrl,
		&i.JobID,
		&i.EpisodeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const enrichEpisode = `-- name: EnrichEpisode :one
UPDATE episodes
SET podcast_id = COALESCE(episodes.podcast_id, $1::uuid),
    title = CASE
        WHEN episodes.podcast_id IS NULL AND $1::uuid IS NOT NULL
        THEN $2
        ELSE episodes.title
    END,
    description = CASE WHEN episodes.description = '' THEN $3 ELSE episodes.description END,
    published_at = COALESCE(episodes.published_at, $4::timestamptz),
    duration_ms = CASE WHEN episodes.duration_ms = 0 THEN $5 ELSE episodes.duration_ms END,
    cover_url = CASE WHEN episodes.cover_url = '' THEN $6 ELSE episodes.cover_url END,
    resolve_status = 'completed',
    updated_at = now()
WHERE episodes.id = $7
  AND episodes.user_id = $8
RETURNING id, user_id, podcast_id, title, description, published_at, duration_ms, cover_url, resolve_status, transcription_status, ai_status, created_at, updated_at
`

type EnrichEpisodeParams struct {
	PodcastID   pgtype.UUID        `json:"podcast_id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	DurationMs  int64              `json:"duration_ms"`
	CoverUrl    string             `json:"cover_url"`
	EpisodeID   pgtype.UUID        `json:"episode_id"`
	UserID      pgtype.UUID        `json:"user_id"`
}

func (q *Queries) EnrichEpisode(ctx context.Context, arg EnrichEpisodeParams) (Episode, error) {
	row := q.db.QueryRow(ctx, enrichEpisode,
		arg.PodcastID,
		arg.Title,
		arg.Description,
		arg.PublishedAt,
		arg.DurationMs,
		arg.CoverUrl,
		arg.EpisodeID,
		arg.UserID,
	)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PodcastID,
		&i.Title,
		&i.Description,
		&i.PublishedAt,
		&i.DurationMs,
		&i.CoverUrl,
		&i.ResolveStatus,
		&i.TranscriptionStatus,
		&i.AiStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findEpisodeByIdentityKeys = `-- name: FindEpisodeByIdentityKeys :one
WITH requested AS (
    SELECT identity_key, ordinality
    FROM unnest($2::text[]) WITH ORDINALITY AS input(identity_key, ordinality)
)
SELECT stored.episode_id
FROM requested
JOIN episode_identity_keys AS stored
  ON stored.user_id = $1
 AND stored.identity_key = requested.identity_key
ORDER BY requested.ordinality
LIMIT 1
`

type FindEpisodeByIdentityKeysParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	IdentityKeys []string    `json:"identity_keys"`
}

func (q *Queries) FindEpisodeByIdentityKeys(ctx context.Context, arg FindEpisodeByIdentityKeysParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findEpisodeByIdentityKeys, arg.UserID, arg.IdentityKeys)
	var episode_id pgtype.UUID
	err := row.Scan(&episode_id)
	return episode_id, err
}

const getImportForResolve = `-- name: GetImportForResolve :one
SELECT import_record.id, import_record.user_id, import_record.submitted_url, import_record.job_id, import_record.episode_id, import_record.created_at, import_record.updated_at, job.status AS job_status
FROM imports AS import_record
JOIN jobs AS job ON job.id = import_record.job_id
WHERE import_record.id = $1
  AND import_record.user_id = $2
FOR UPDATE OF import_record
`

type GetImportForResolveParams struct {
	ImportID pgtype.UUID `json:"import_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

type GetImportForResolveRow struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	SubmittedUrl string             `json:"submitted_url"`
	JobID        pgtype.UUID        `json:"job_id"`
	EpisodeID    pgtype.UUID        `json:"episode_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	JobStatus    string             `json:"job_status"`
}

func (q *Queries) GetImportForResolve(ctx context.Context, arg GetImportForResolveParams) (GetImportForResolveRow, error) {
	row := q.db.QueryRow(ctx, getImportForResolve, arg.ImportID, arg.UserID)
	var i GetImportForResolveRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubmittedUrl,
		&i.JobID,
		&i.EpisodeID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.JobStatus,
	)
	return i, err
}

const getImportStatus = `-- name: GetImportStatus :one
SELECT
    import_record.id,
    import_record.submitted_url,
    import_record.episode_id,
    episode.resolve_status AS episode_resolve_status,
    COALESCE(job.status, CASE WHEN episode.resolve_status = 'completed' THEN 'succeeded' ELSE 'failed' END)::text AS status,
    COALESCE(job.stage, CASE WHEN episode.resolve_status = 'completed' THEN 'completed' ELSE 'expired' END)::text AS stage,
    job.error_code,
    job.error_message,
    import_record.created_at,
    GREATEST(import_record.updated_at, COALESCE(job.updated_at, import_record.updated_at))::timestamptz AS updated_at
FROM imports AS import_record
LEFT JOIN jobs AS job ON job.id = import_record.job_id
LEFT JOIN episodes AS episode
  ON episode.id = import_record.episode_id
 AND episode.user_id = import_record.user_id
WHERE import_record.id = $1
  AND import_record.user_id = $2
`

type GetImportStatusParams struct {
	ImportID pgtype.UUID `json:"import_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

type GetImportStatusRow struct {
	ID                   pgtype.UUID        `json:"id"`
	SubmittedUrl         string             `json:"submitted_url"`
	EpisodeID            pgtype.UUID        `json:"episode_id"`
	EpisodeResolveStatus *string            `json:"episode_resolve_status"`
	Status               string             `json:"status"`
	Stage                string             `json:"stage"`
	ErrorCode            *string            `json:"error_code"`
	ErrorMessage         *string            `json:"error_message"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetImportStatus(ctx context.Context, arg GetImportStatusParams) (GetImportStatusRow, error) {
	row := q.db.QueryRow(ctx, getImportStatus, arg.ImportID, arg.UserID)
	var i GetImportStatusRow
	err := row.Scan(
		&i.ID,
		&i.SubmittedUrl,
		&i.EpisodeID,
		&i.EpisodeResolveStatus,
		&i.Status,
		&i.Stage,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setImportEpisode = `-- name: SetImportEpisode :exec
UPDATE imports
SET episode_id = $1,
    updated_at = now()
WHERE id = $2
  AND user_id = $3
`

type SetImportEpisodeParams struct {
	EpisodeID pgtype.UUID `json:"episode_id"`
	ImportID  pgtype.UUID `json:"import_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) SetImportEpisode(ctx context.Context, arg SetImportEpisodeParams) error {
	_, err := q.db.Exec(ctx, setImportEpisode, arg.EpisodeID, arg.ImportID, arg.UserID)
	return err
}

const setImportJob = `-- name: SetImportJob :exec
UPDATE imports
SET job_id = $1,
    updated_at = now()
WHERE id = $2
  AND user_id = $3
`

type SetImportJobParams struct {
	JobID    pgtype.UUID `json:"job_id"`
	ImportID pgtype.UUID `json:"import_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) SetImportJob(ctx context.Context, arg SetImportJobParams) error {
	_, err := q.db.Exec(ctx, setImportJob, arg.JobID, arg.ImportID, arg.UserID)
	return err
}

const upsertPodcast = `-- name: UpsertPodcast :one
INSERT INTO podcasts (
    user_id,
    title,
    author,
    description,
    cover_url,
    feed_url
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
ON CONFLICT (user_id, feed_url) WHERE feed_url IS NOT NULL
DO UPDATE SET
    title = EXCLUDED.title,
    author = CASE WHEN EXCLUDED.author <> '' THEN EXCLUDED.author ELSE podcasts.author END,
    description = CASE WHEN EXCLUDED.description <> '' THEN EXCLUDED.description ELSE podcasts.description END,
    cover_url = CASE WHEN EXCLUDED.cover_url <> '' THEN EXCLUDED.cover_url ELSE podcasts.cover_url END,
    updated_at = now()
RETURNING id, user_id, title, author, description, cover_url, feed_url, created_at, updated_at
`

type UpsertPodcastParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	Title       string      `json:"title"`
	Author      string      `json:"author"`
	Description string      `json:"description"`
	CoverUrl    string      `json:"cover_url"`
	FeedUrl     *string     `json:"feed_url"`
}

func (q *Queries) UpsertPodcast(ctx context.Context, arg UpsertPodcastParams) (Podcast, error) {
	row := q.db.QueryRow(ctx, upsertPodcast,
		arg.UserID,
		arg.Title,
		arg.Author,
		arg.Description,
		arg.CoverUrl,
		arg.FeedUrl,
	)
	var i Podcast
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Author,
		&i.Description,
		&i.CoverUrl,
		&i.FeedUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
