// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: imports.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireEpisodeIdentityLock = `-- name: AcquireEpisodeIdentityLock :exec
SELECT pg_advisory_xact_lock(hashtextextended($1, 0))
`

func (q *Queries) AcquireEpisodeIdentityLock(ctx context.Context, identityKey string) error {
	_, err := q.db.Exec(ctx, acquireEpisodeIdentityLock, identityKey)
	return err
}

const addEpisodeIdentityKey = `-- name: AddEpisodeIdentityKey :exec
INSERT INTO episode_identity_keys (user_id, identity_key, episode_id)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, identity_key) DO NOTHING
`

type AddEpisodeIdentityKeyParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	IdentityKey string      `json:"identity_key"`
	EpisodeID   pgtype.UUID `json:"episode_id"`
}

func (q *Queries) AddEpisodeIdentityKey(ctx context.Context, arg AddEpisodeIdentityKeyParams) error {
	_, err := q.db.Exec(ctx, addEpisodeIdentityKey, arg.UserID, arg.IdentityKey, arg.EpisodeID)
	return err
}

const addEpisodeSource = `-- name: AddEpisodeSource :exec
INSERT INTO episode_sources (
    user_id,
    episode_id,
    source_type,
    external_id,
    source_url,
    canonical_url,
    audio_url,
    download_headers,
    rss_guid
) VALUES (
    $1,
    $2,
    $3,
    $4::text,
    $5,
    $6,
    $7,
    $8::jsonb,
    $9::text
)
ON CONFLICT (user_id, episode_id, source_type, source_url) DO UPDATE
SET external_id = EXCLUDED.external_id,
    canonical_url = EXCLUDED.canonical_url,
    audio_url = EXCLUDED.audio_url,
    download_headers = EXCLUDED.download_headers,
    rss_guid = EXCLUDED.rss_guid,
    created_at = now()
`

type AddEpisodeSourceParams struct {
	UserID          pgtype.UUID `json:"user_id"`
	EpisodeID       pgtype.UUID `json:"episode_id"`
	SourceType      string      `json:"source_type"`
	ExternalID      *string     `json:"external_id"`
	SourceUrl       string      `json:"source_url"`
	CanonicalUrl    string      `json:"canonical_url"`
	AudioUrl        string      `json:"audio_url"`
	DownloadHeaders []byte      `json:"download_headers"`
	RssGuid         *string     `json:"rss_guid"`
}

func (q *Queries) AddEpisodeSource(ctx context.Context, arg AddEpisodeSourceParams) error {
	_, err := q.db.Exec(ctx, addEpisodeSource,
		arg.UserID,
		arg.EpisodeID,
		arg.SourceType,
		arg.ExternalID,
		arg.SourceUrl,
		arg.CanonicalUrl,
		arg.AudioUrl,
		arg.DownloadHeaders,
		arg.RssGuid,
	)
	return err
}

const createEpisode = `-- name: CreateEpisode :one
INSERT INTO episodes (
    user_id,
    title,
    description,
    published_at,
    duration_ms,
    cover_url,
    resolve_status
) VALUES (
    $1,
    $2,
    $3,
    $4::timestamptz,
    $5,
    $6,
    'completed'
)
RETURNING id, user_id, title, description, published_at, duration_ms, cover_url, resolve_status, transcription_status, created_at, updated_at
`

type CreateEpisodeParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	DurationMs  int64              `json:"duration_ms"`
	CoverUrl    string             `json:"cover_url"`
}

func (q *Queries) CreateEpisode(ctx context.Context, arg CreateEpisodeParams) (Episode, error) {
	row := q.db.QueryRow(ctx, createEpisode,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.PublishedAt,
		arg.DurationMs,
		arg.CoverUrl,
	)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.PublishedAt,
		&i.DurationMs,
		&i.CoverUrl,
		&i.ResolveStatus,
		&i.TranscriptionStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createImport = `-- name: CreateImport :one
INSERT INTO imports (user_id, submitted_url)
VALUES ($1, $2)
RETURNING id, user_id, submitted_url, job_id, episode_id, created_at, updated_at
`

type CreateImportParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	SubmittedUrl string      `json:"submitted_url"`
}

func (q *Queries) CreateImport(ctx context.Context, arg CreateImportParams) (Import, error) {
	row := q.db.QueryRow(ctx, createImport, arg.UserID, arg.SubmittedUrl)
	var i Import
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubmittedUrl,
		&i.JobID,
		&i.EpisodeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const enrichEpisode = `-- name: EnrichEpisode :one
UPDATE episodes
SET title = CASE WHEN episodes.title = '' THEN $1 ELSE episodes.title END,
    description = CASE WHEN episodes.description = '' THEN $2 ELSE episodes.description END,
    published_at = COALESCE(episodes.published_at, $3::timestamptz),
    duration_ms = CASE WHEN episodes.duration_ms = 0 THEN $4 ELSE episodes.duration_ms END,
    cover_url = CASE WHEN episodes.cover_url = '' THEN $5 ELSE episodes.cover_url END,
    resolve_status = 'completed',
    updated_at = now()
WHERE episodes.id = $6
  AND episodes.user_id = $7
RETURNING id, user_id, title, description, published_at, duration_ms, cover_url, resolve_status, transcription_status, created_at, updated_at
`

type EnrichEpisodeParams struct {
	Title       string             `json:"title"`
	Description string             `json:"description"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	DurationMs  int64              `json:"duration_ms"`
	CoverUrl    string             `json:"cover_url"`
	EpisodeID   pgtype.UUID        `json:"episode_id"`
	UserID      pgtype.UUID        `json:"user_id"`
}

func (q *Queries) EnrichEpisode(ctx context.Context, arg EnrichEpisodeParams) (Episode, error) {
	row := q.db.QueryRow(ctx, enrichEpisode,
		arg.Title,
		arg.Description,
		arg.PublishedAt,
		arg.DurationMs,
		arg.CoverUrl,
		arg.EpisodeID,
		arg.UserID,
	)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.PublishedAt,
		&i.DurationMs,
		&i.CoverUrl,
		&i.ResolveStatus,
		&i.TranscriptionStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findEpisodeByIdentityKeys = `-- name: FindEpisodeByIdentityKeys :one
WITH requested AS (
    SELECT identity_key, ordinality
    FROM unnest($2::text[]) WITH ORDINALITY AS input(identity_key, ordinality)
)
SELECT stored.episode_id
FROM requested
JOIN episode_identity_keys AS stored
  ON stored.user_id = $1
 AND stored.identity_key = requested.identity_key
ORDER BY requested.ordinality
LIMIT 1
`

type FindEpisodeByIdentityKeysParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	IdentityKeys []string    `json:"identity_keys"`
}

func (q *Queries) FindEpisodeByIdentityKeys(ctx context.Context, arg FindEpisodeByIdentityKeysParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findEpisodeByIdentityKeys, arg.UserID, arg.IdentityKeys)
	var episode_id pgtype.UUID
	err := row.Scan(&episode_id)
	return episode_id, err
}

const getImportForResolve = `-- name: GetImportForResolve :one
SELECT import_record.id, import_record.user_id, import_record.submitted_url, import_record.job_id, import_record.episode_id, import_record.created_at, import_record.updated_at, job.status AS job_status
FROM imports AS import_record
JOIN jobs AS job ON job.id = import_record.job_id
WHERE import_record.id = $1
  AND import_record.user_id = $2
FOR UPDATE OF import_record
`

type GetImportForResolveParams struct {
	ImportID pgtype.UUID `json:"import_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

type GetImportForResolveRow struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	SubmittedUrl string             `json:"submitted_url"`
	JobID        pgtype.UUID        `json:"job_id"`
	EpisodeID    pgtype.UUID        `json:"episode_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	JobStatus    string             `json:"job_status"`
}

func (q *Queries) GetImportForResolve(ctx context.Context, arg GetImportForResolveParams) (GetImportForResolveRow, error) {
	row := q.db.QueryRow(ctx, getImportForResolve, arg.ImportID, arg.UserID)
	var i GetImportForResolveRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubmittedUrl,
		&i.JobID,
		&i.EpisodeID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.JobStatus,
	)
	return i, err
}

const getImportStatus = `-- name: GetImportStatus :one
SELECT
    import_record.id,
    import_record.submitted_url,
    import_record.episode_id,
    episode.title,
    episode.duration_ms,
    COALESCE(job.status, CASE WHEN episode.resolve_status = 'completed' THEN 'succeeded' ELSE 'failed' END)::text AS import_status,
    COALESCE(job.stage, CASE WHEN episode.resolve_status = 'completed' THEN 'completed' ELSE 'expired' END)::text AS import_stage,
    job.error_code,
    job.error_message,
    run.id AS transcription_run_id,
    COALESCE(run.status, '')::text AS transcription_status,
    COALESCE(run.stage, '')::text AS transcription_stage,
    COALESCE(run.total_chunks, 0)::integer AS total_chunks,
    COALESCE(run.completed_chunks, 0)::integer AS completed_chunks,
    run.error_code AS transcription_error_code,
    run.error_message AS transcription_error_message,
    transcript.id AS transcript_id,
    import_record.created_at,
    GREATEST(
        import_record.updated_at,
        COALESCE(job.updated_at, import_record.updated_at),
        COALESCE(run.updated_at, import_record.updated_at)
    )::timestamptz AS updated_at
FROM imports AS import_record
LEFT JOIN jobs AS job ON job.id = import_record.job_id
LEFT JOIN episodes AS episode
  ON episode.id = import_record.episode_id
 AND episode.user_id = import_record.user_id
LEFT JOIN LATERAL (
    SELECT candidate.id, candidate.user_id, candidate.episode_id, candidate.profile, candidate.provider, candidate.model, candidate.status, candidate.stage, candidate.version, candidate.config, candidate.source_object_key, candidate.source_audio_hash, candidate.prepared_object_key, candidate.prepared_audio_hash, candidate.duration_ms, candidate.total_chunks, candidate.completed_chunks, candidate.started_at, candidate.completed_at, candidate.error_code, candidate.error_message, candidate.audio_cleaned_at, candidate.chunks_cleaned_at, candidate.created_at, candidate.updated_at
    FROM transcription_runs AS candidate
    WHERE candidate.episode_id = import_record.episode_id
      AND candidate.user_id = import_record.user_id
    ORDER BY candidate.created_at DESC, candidate.id DESC
    LIMIT 1
) AS run ON true
LEFT JOIN transcript_versions AS transcript
  ON transcript.transcription_run_id = run.id
 AND transcript.user_id = import_record.user_id
WHERE import_record.id = $1
  AND import_record.user_id = $2
`

type GetImportStatusParams struct {
	ImportID pgtype.UUID `json:"import_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

type GetImportStatusRow struct {
	ID                        pgtype.UUID        `json:"id"`
	SubmittedUrl              string             `json:"submitted_url"`
	EpisodeID                 pgtype.UUID        `json:"episode_id"`
	Title                     *string            `json:"title"`
	DurationMs                *int64             `json:"duration_ms"`
	ImportStatus              string             `json:"import_status"`
	ImportStage               string             `json:"import_stage"`
	ErrorCode                 *string            `json:"error_code"`
	ErrorMessage              *string            `json:"error_message"`
	TranscriptionRunID        pgtype.UUID        `json:"transcription_run_id"`
	TranscriptionStatus       string             `json:"transcription_status"`
	TranscriptionStage        string             `json:"transcription_stage"`
	TotalChunks               int32              `json:"total_chunks"`
	CompletedChunks           int32              `json:"completed_chunks"`
	TranscriptionErrorCode    *string            `json:"transcription_error_code"`
	TranscriptionErrorMessage *string            `json:"transcription_error_message"`
	TranscriptID              pgtype.UUID        `json:"transcript_id"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetImportStatus(ctx context.Context, arg GetImportStatusParams) (GetImportStatusRow, error) {
	row := q.db.QueryRow(ctx, getImportStatus, arg.ImportID, arg.UserID)
	var i GetImportStatusRow
	err := row.Scan(
		&i.ID,
		&i.SubmittedUrl,
		&i.EpisodeID,
		&i.Title,
		&i.DurationMs,
		&i.ImportStatus,
		&i.ImportStage,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.TranscriptionRunID,
		&i.TranscriptionStatus,
		&i.TranscriptionStage,
		&i.TotalChunks,
		&i.CompletedChunks,
		&i.TranscriptionErrorCode,
		&i.TranscriptionErrorMessage,
		&i.TranscriptID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTranscriptionTaskSegments = `-- name: ListTranscriptionTaskSegments :many
SELECT
    segment.start_ms,
    segment.text,
    speaker.display_name AS speaker_name
FROM transcript_segments AS segment
JOIN transcript_speakers AS speaker ON speaker.id = segment.speaker_id
JOIN transcript_versions AS transcript ON transcript.id = segment.transcript_version_id
JOIN imports AS import_record ON import_record.episode_id = transcript.episode_id
WHERE import_record.id = $1
  AND import_record.user_id = $2
  AND transcript.is_active
ORDER BY segment.sequence
`

type ListTranscriptionTaskSegmentsParams struct {
	ImportID pgtype.UUID `json:"import_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

type ListTranscriptionTaskSegmentsRow struct {
	StartMs     int64  `json:"start_ms"`
	Text        string `json:"text"`
	SpeakerName string `json:"speaker_name"`
}

func (q *Queries) ListTranscriptionTaskSegments(ctx context.Context, arg ListTranscriptionTaskSegmentsParams) ([]ListTranscriptionTaskSegmentsRow, error) {
	rows, err := q.db.Query(ctx, listTranscriptionTaskSegments, arg.ImportID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTranscriptionTaskSegmentsRow{}
	for rows.Next() {
		var i ListTranscriptionTaskSegmentsRow
		if err := rows.Scan(&i.StartMs, &i.Text, &i.SpeakerName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setImportEpisode = `-- name: SetImportEpisode :exec
UPDATE imports
SET episode_id = $1,
    updated_at = now()
WHERE id = $2
  AND user_id = $3
`

type SetImportEpisodeParams struct {
	EpisodeID pgtype.UUID `json:"episode_id"`
	ImportID  pgtype.UUID `json:"import_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) SetImportEpisode(ctx context.Context, arg SetImportEpisodeParams) error {
	_, err := q.db.Exec(ctx, setImportEpisode, arg.EpisodeID, arg.ImportID, arg.UserID)
	return err
}

const setImportJob = `-- name: SetImportJob :exec
UPDATE imports
SET job_id = $1,
    updated_at = now()
WHERE id = $2
  AND user_id = $3
`

type SetImportJobParams struct {
	JobID    pgtype.UUID `json:"job_id"`
	ImportID pgtype.UUID `json:"import_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) SetImportJob(ctx context.Context, arg SetImportJobParams) error {
	_, err := q.db.Exec(ctx, setImportJob, arg.JobID, arg.ImportID, arg.UserID)
	return err
}
