// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimJob = `-- name: ClaimJob :one
WITH next_job AS (
    SELECT id
    FROM jobs
    WHERE status = 'queued'
      AND run_after <= now()
      AND attempt < max_attempts
      AND type = ANY($2::text[])
    ORDER BY priority DESC, run_after, created_at
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE jobs AS job
SET status = 'running',
    stage = 'running',
    attempt = job.attempt + 1,
    locked_by = $1,
    locked_at = now(),
    error_code = NULL,
    error_message = NULL,
    updated_at = now()
FROM next_job
WHERE job.id = next_job.id
RETURNING job.id, job.user_id, job.type, job.entity_type, job.entity_id, job.payload, job.status, job.stage, job.priority, job.attempt, job.max_attempts, job.run_after, job.locked_by, job.locked_at, job.error_code, job.error_message, job.created_at, job.updated_at, job.completed_at
`

type ClaimJobParams struct {
	WorkerID *string  `json:"worker_id"`
	JobTypes []string `json:"job_types"`
}

func (q *Queries) ClaimJob(ctx context.Context, arg ClaimJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, claimJob, arg.WorkerID, arg.JobTypes)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.EntityType,
		&i.EntityID,
		&i.Payload,
		&i.Status,
		&i.Stage,
		&i.Priority,
		&i.Attempt,
		&i.MaxAttempts,
		&i.RunAfter,
		&i.LockedBy,
		&i.LockedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const completeJob = `-- name: CompleteJob :one
UPDATE jobs
SET status = 'succeeded',
    stage = 'completed',
    locked_by = NULL,
    locked_at = NULL,
    error_code = NULL,
    error_message = NULL,
    updated_at = now(),
    completed_at = now()
WHERE id = $1
  AND status = 'running'
  AND locked_by = $2
RETURNING id, user_id, type, entity_type, entity_id, payload, status, stage, priority, attempt, max_attempts, run_after, locked_by, locked_at, error_code, error_message, created_at, updated_at, completed_at
`

type CompleteJobParams struct {
	JobID    pgtype.UUID `json:"job_id"`
	WorkerID *string     `json:"worker_id"`
}

func (q *Queries) CompleteJob(ctx context.Context, arg CompleteJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, completeJob, arg.JobID, arg.WorkerID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.EntityType,
		&i.EntityID,
		&i.Payload,
		&i.Status,
		&i.Stage,
		&i.Priority,
		&i.Attempt,
		&i.MaxAttempts,
		&i.RunAfter,
		&i.LockedBy,
		&i.LockedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createJobEvent = `-- name: CreateJobEvent :one
INSERT INTO job_events (job_id, event_type, stage, data)
VALUES (
    $1,
    $2,
    $3,
    $4::jsonb
)
RETURNING id, job_id, event_type, stage, data, created_at
`

type CreateJobEventParams struct {
	JobID     pgtype.UUID `json:"job_id"`
	EventType string      `json:"event_type"`
	Stage     string      `json:"stage"`
	Data      []byte      `json:"data"`
}

func (q *Queries) CreateJobEvent(ctx context.Context, arg CreateJobEventParams) (JobEvent, error) {
	row := q.db.QueryRow(ctx, createJobEvent,
		arg.JobID,
		arg.EventType,
		arg.Stage,
		arg.Data,
	)
	var i JobEvent
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.EventType,
		&i.Stage,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const enqueueJob = `-- name: EnqueueJob :one
INSERT INTO jobs (
    user_id,
    type,
    entity_type,
    entity_id,
    payload,
    stage,
    priority,
    max_attempts,
    run_after
) VALUES (
    $1::uuid,
    $2,
    $3,
    $4,
    $5::jsonb,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, user_id, type, entity_type, entity_id, payload, status, stage, priority, attempt, max_attempts, run_after, locked_by, locked_at, error_code, error_message, created_at, updated_at, completed_at
`

type EnqueueJobParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	JobType     string             `json:"job_type"`
	EntityType  string             `json:"entity_type"`
	EntityID    pgtype.UUID        `json:"entity_id"`
	Payload     []byte             `json:"payload"`
	Stage       string             `json:"stage"`
	Priority    int16              `json:"priority"`
	MaxAttempts int32              `json:"max_attempts"`
	RunAfter    pgtype.Timestamptz `json:"run_after"`
}

func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, enqueueJob,
		arg.UserID,
		arg.JobType,
		arg.EntityType,
		arg.EntityID,
		arg.Payload,
		arg.Stage,
		arg.Priority,
		arg.MaxAttempts,
		arg.RunAfter,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.EntityType,
		&i.EntityID,
		&i.Payload,
		&i.Status,
		&i.Stage,
		&i.Priority,
		&i.Attempt,
		&i.MaxAttempts,
		&i.RunAfter,
		&i.LockedBy,
		&i.LockedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT id, user_id, type, entity_type, entity_id, payload, status, stage, priority, attempt, max_attempts, run_after, locked_by, locked_at, error_code, error_message, created_at, updated_at, completed_at
FROM jobs
WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, jobID pgtype.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, jobID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.EntityType,
		&i.EntityID,
		&i.Payload,
		&i.Status,
		&i.Stage,
		&i.Priority,
		&i.Attempt,
		&i.MaxAttempts,
		&i.RunAfter,
		&i.LockedBy,
		&i.LockedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const heartbeatJob = `-- name: HeartbeatJob :execrows
UPDATE jobs
SET locked_at = now(),
    updated_at = now()
WHERE id = $1
  AND status = 'running'
  AND locked_by = $2
`

type HeartbeatJobParams struct {
	JobID    pgtype.UUID `json:"job_id"`
	WorkerID *string     `json:"worker_id"`
}

func (q *Queries) HeartbeatJob(ctx context.Context, arg HeartbeatJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, heartbeatJob, arg.JobID, arg.WorkerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listJobEvents = `-- name: ListJobEvents :many
SELECT id, job_id, event_type, stage, data, created_at
FROM job_events
WHERE job_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListJobEvents(ctx context.Context, jobID pgtype.UUID) ([]JobEvent, error) {
	rows, err := q.db.Query(ctx, listJobEvents, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobEvent{}
	for rows.Next() {
		var i JobEvent
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.EventType,
			&i.Stage,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requeueStaleJobs = `-- name: RequeueStaleJobs :many
UPDATE jobs
SET status = CASE WHEN attempt < max_attempts THEN 'queued' ELSE 'failed' END,
    stage = CASE WHEN attempt < max_attempts THEN 'retry_wait' ELSE 'failed' END,
    run_after = CASE WHEN attempt < max_attempts THEN now() ELSE run_after END,
    locked_by = NULL,
    locked_at = NULL,
    error_code = 'JOB_LEASE_EXPIRED',
    error_message = 'worker lease expired before completion',
    updated_at = now(),
    completed_at = CASE WHEN attempt < max_attempts THEN NULL ELSE now() END
WHERE status = 'running'
  AND locked_at < now() - ($1::bigint * interval '1 millisecond')
RETURNING id, user_id, type, entity_type, entity_id, payload, status, stage, priority, attempt, max_attempts, run_after, locked_by, locked_at, error_code, error_message, created_at, updated_at, completed_at
`

func (q *Queries) RequeueStaleJobs(ctx context.Context, leaseMilliseconds int64) ([]Job, error) {
	rows, err := q.db.Query(ctx, requeueStaleJobs, leaseMilliseconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.EntityType,
			&i.EntityID,
			&i.Payload,
			&i.Status,
			&i.Stage,
			&i.Priority,
			&i.Attempt,
			&i.MaxAttempts,
			&i.RunAfter,
			&i.LockedBy,
			&i.LockedAt,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retryOrFailJob = `-- name: RetryOrFailJob :one
UPDATE jobs
SET status = CASE WHEN attempt < max_attempts THEN 'queued' ELSE 'failed' END,
    stage = CASE WHEN attempt < max_attempts THEN 'retry_wait' ELSE 'failed' END,
    run_after = CASE
        WHEN attempt < max_attempts
        THEN now() + ($1::bigint * interval '1 millisecond')
        ELSE run_after
    END,
    locked_by = NULL,
    locked_at = NULL,
    error_code = $2,
    error_message = $3,
    updated_at = now(),
    completed_at = CASE WHEN attempt < max_attempts THEN NULL ELSE now() END
WHERE id = $4
  AND status = 'running'
  AND locked_by = $5
RETURNING id, user_id, type, entity_type, entity_id, payload, status, stage, priority, attempt, max_attempts, run_after, locked_by, locked_at, error_code, error_message, created_at, updated_at, completed_at
`

type RetryOrFailJobParams struct {
	RetryDelayMilliseconds int64       `json:"retry_delay_milliseconds"`
	ErrorCode              *string     `json:"error_code"`
	ErrorMessage           *string     `json:"error_message"`
	JobID                  pgtype.UUID `json:"job_id"`
	WorkerID               *string     `json:"worker_id"`
}

func (q *Queries) RetryOrFailJob(ctx context.Context, arg RetryOrFailJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, retryOrFailJob,
		arg.RetryDelayMilliseconds,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.JobID,
		arg.WorkerID,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.EntityType,
		&i.EntityID,
		&i.Payload,
		&i.Status,
		&i.Stage,
		&i.Priority,
		&i.Attempt,
		&i.MaxAttempts,
		&i.RunAfter,
		&i.LockedBy,
		&i.LockedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}
