// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: library.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelEpisodeImportJobs = `-- name: CancelEpisodeImportJobs :many
UPDATE jobs AS job
SET status = 'canceled',
    stage = 'canceled',
    locked_by = NULL,
    locked_at = NULL,
    error_code = NULL,
    error_message = NULL,
    updated_at = now(),
    completed_at = now()
WHERE job.id IN (
    SELECT import_record.job_id
    FROM imports AS import_record
    WHERE import_record.episode_id = $1
      AND import_record.user_id = $2
)
  AND job.status IN ('queued', 'running')
RETURNING job.id, job.user_id, job.type, job.entity_type, job.entity_id, job.payload, job.status, job.stage, job.priority, job.attempt, job.max_attempts, job.run_after, job.locked_by, job.locked_at, job.error_code, job.error_message, job.created_at, job.updated_at, job.completed_at
`

type CancelEpisodeImportJobsParams struct {
	EpisodeID pgtype.UUID `json:"episode_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) CancelEpisodeImportJobs(ctx context.Context, arg CancelEpisodeImportJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, cancelEpisodeImportJobs, arg.EpisodeID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.EntityType,
			&i.EntityID,
			&i.Payload,
			&i.Status,
			&i.Stage,
			&i.Priority,
			&i.Attempt,
			&i.MaxAttempts,
			&i.RunAfter,
			&i.LockedBy,
			&i.LockedAt,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cancelEpisodeTranscriptionJobs = `-- name: CancelEpisodeTranscriptionJobs :many
UPDATE jobs AS job
SET status = 'canceled',
    stage = 'canceled',
    locked_by = NULL,
    locked_at = NULL,
    error_code = NULL,
    error_message = NULL,
    updated_at = now(),
    completed_at = now()
WHERE job.user_id = $1
  AND job.status IN ('queued', 'running')
  AND (
      (job.entity_type = 'transcription_run' AND job.entity_id IN (
          SELECT run.id FROM transcription_runs AS run WHERE run.episode_id = $2
      ))
      OR
      (job.entity_type = 'transcription_chunk' AND job.entity_id IN (
          SELECT chunk.id
          FROM transcription_chunks AS chunk
          JOIN transcription_runs AS run ON run.id = chunk.transcription_run_id
          WHERE run.episode_id = $2
      ))
  )
RETURNING job.id, job.user_id, job.type, job.entity_type, job.entity_id, job.payload, job.status, job.stage, job.priority, job.attempt, job.max_attempts, job.run_after, job.locked_by, job.locked_at, job.error_code, job.error_message, job.created_at, job.updated_at, job.completed_at
`

type CancelEpisodeTranscriptionJobsParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	EpisodeID pgtype.UUID `json:"episode_id"`
}

func (q *Queries) CancelEpisodeTranscriptionJobs(ctx context.Context, arg CancelEpisodeTranscriptionJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, cancelEpisodeTranscriptionJobs, arg.UserID, arg.EpisodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.EntityType,
			&i.EntityID,
			&i.Payload,
			&i.Status,
			&i.Stage,
			&i.Priority,
			&i.Attempt,
			&i.MaxAttempts,
			&i.RunAfter,
			&i.LockedBy,
			&i.LockedAt,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countLibraryEpisodes = `-- name: CountLibraryEpisodes :one
SELECT count(*)
FROM episodes
WHERE user_id = $1
`

func (q *Queries) CountLibraryEpisodes(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLibraryEpisodes, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteLibraryEpisode = `-- name: DeleteLibraryEpisode :one
DELETE FROM episodes
WHERE id = $1
  AND user_id = $2
RETURNING podcast_id
`

type DeleteLibraryEpisodeParams struct {
	EpisodeID pgtype.UUID `json:"episode_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteLibraryEpisode(ctx context.Context, arg DeleteLibraryEpisodeParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteLibraryEpisode, arg.EpisodeID, arg.UserID)
	var podcast_id pgtype.UUID
	err := row.Scan(&podcast_id)
	return podcast_id, err
}

const deleteOrphanPodcast = `-- name: DeleteOrphanPodcast :exec
DELETE FROM podcasts AS podcast
WHERE podcast.id = $1
  AND podcast.user_id = $2
  AND NOT EXISTS (
      SELECT 1
      FROM episodes AS episode
      WHERE episode.podcast_id = podcast.id
        AND episode.user_id = podcast.user_id
  )
`

type DeleteOrphanPodcastParams struct {
	PodcastID pgtype.UUID `json:"podcast_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteOrphanPodcast(ctx context.Context, arg DeleteOrphanPodcastParams) error {
	_, err := q.db.Exec(ctx, deleteOrphanPodcast, arg.PodcastID, arg.UserID)
	return err
}

const getLibraryEpisode = `-- name: GetLibraryEpisode :one
SELECT
    episode.id,
    episode.title,
    episode.description,
    episode.published_at,
    episode.duration_ms,
    episode.cover_url,
    episode.resolve_status,
    episode.transcription_status,
    episode.ai_status,
    episode.created_at,
    episode.updated_at,
    podcast.id AS podcast_id,
    podcast.title AS podcast_title,
    podcast.author AS podcast_author,
    podcast.description AS podcast_description,
    podcast.cover_url AS podcast_cover_url,
    podcast.feed_url AS podcast_feed_url,
    (
        SELECT count(*)
        FROM episode_sources AS source
        WHERE source.episode_id = episode.id
          AND source.user_id = episode.user_id
    )::bigint AS source_count
FROM episodes AS episode
LEFT JOIN podcasts AS podcast
  ON podcast.id = episode.podcast_id
 AND podcast.user_id = episode.user_id
WHERE episode.id = $1
  AND episode.user_id = $2
`

type GetLibraryEpisodeParams struct {
	EpisodeID pgtype.UUID `json:"episode_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

type GetLibraryEpisodeRow struct {
	ID                  pgtype.UUID        `json:"id"`
	Title               string             `json:"title"`
	Description         string             `json:"description"`
	PublishedAt         pgtype.Timestamptz `json:"published_at"`
	DurationMs          int64              `json:"duration_ms"`
	CoverUrl            string             `json:"cover_url"`
	ResolveStatus       string             `json:"resolve_status"`
	TranscriptionStatus string             `json:"transcription_status"`
	AiStatus            string             `json:"ai_status"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	PodcastID           pgtype.UUID        `json:"podcast_id"`
	PodcastTitle        *string            `json:"podcast_title"`
	PodcastAuthor       *string            `json:"podcast_author"`
	PodcastDescription  *string            `json:"podcast_description"`
	PodcastCoverUrl     *string            `json:"podcast_cover_url"`
	PodcastFeedUrl      *string            `json:"podcast_feed_url"`
	SourceCount         int64              `json:"source_count"`
}

func (q *Queries) GetLibraryEpisode(ctx context.Context, arg GetLibraryEpisodeParams) (GetLibraryEpisodeRow, error) {
	row := q.db.QueryRow(ctx, getLibraryEpisode, arg.EpisodeID, arg.UserID)
	var i GetLibraryEpisodeRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.PublishedAt,
		&i.DurationMs,
		&i.CoverUrl,
		&i.ResolveStatus,
		&i.TranscriptionStatus,
		&i.AiStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PodcastID,
		&i.PodcastTitle,
		&i.PodcastAuthor,
		&i.PodcastDescription,
		&i.PodcastCoverUrl,
		&i.PodcastFeedUrl,
		&i.SourceCount,
	)
	return i, err
}

const listEpisodeTranscriptionObjectKeys = `-- name: ListEpisodeTranscriptionObjectKeys :many
SELECT object_key::text
FROM (
    SELECT source_object_key AS object_key
    FROM transcription_runs AS run
    WHERE run.episode_id = $1
      AND run.user_id = $2
    UNION ALL
    SELECT prepared_object_key AS object_key
    FROM transcription_runs AS run
    WHERE run.episode_id = $1
      AND run.user_id = $2
    UNION ALL
    SELECT chunk.object_key
    FROM transcription_chunks AS chunk
    JOIN transcription_runs AS run ON run.id = chunk.transcription_run_id
    WHERE run.episode_id = $1
      AND run.user_id = $2
    UNION ALL
    SELECT chunk.raw_result_object_key
    FROM transcription_chunks AS chunk
    JOIN transcription_runs AS run ON run.id = chunk.transcription_run_id
    WHERE run.episode_id = $1
      AND run.user_id = $2
) AS objects
WHERE object_key IS NOT NULL
`

type ListEpisodeTranscriptionObjectKeysParams struct {
	EpisodeID pgtype.UUID `json:"episode_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) ListEpisodeTranscriptionObjectKeys(ctx context.Context, arg ListEpisodeTranscriptionObjectKeysParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listEpisodeTranscriptionObjectKeys, arg.EpisodeID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var object_key string
		if err := rows.Scan(&object_key); err != nil {
			return nil, err
		}
		items = append(items, object_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLibraryEpisodeSources = `-- name: ListLibraryEpisodeSources :many
SELECT
    id,
    source_type,
    external_id,
    source_url,
    canonical_url,
    rss_guid,
    created_at
FROM episode_sources
WHERE episode_id = $1
  AND user_id = $2
ORDER BY created_at, id
`

type ListLibraryEpisodeSourcesParams struct {
	EpisodeID pgtype.UUID `json:"episode_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

type ListLibraryEpisodeSourcesRow struct {
	ID           pgtype.UUID        `json:"id"`
	SourceType   string             `json:"source_type"`
	ExternalID   *string            `json:"external_id"`
	SourceUrl    string             `json:"source_url"`
	CanonicalUrl string             `json:"canonical_url"`
	RssGuid      *string            `json:"rss_guid"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListLibraryEpisodeSources(ctx context.Context, arg ListLibraryEpisodeSourcesParams) ([]ListLibraryEpisodeSourcesRow, error) {
	rows, err := q.db.Query(ctx, listLibraryEpisodeSources, arg.EpisodeID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLibraryEpisodeSourcesRow{}
	for rows.Next() {
		var i ListLibraryEpisodeSourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceType,
			&i.ExternalID,
			&i.SourceUrl,
			&i.CanonicalUrl,
			&i.RssGuid,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLibraryEpisodes = `-- name: ListLibraryEpisodes :many
SELECT
    episode.id,
    episode.title,
    episode.published_at,
    episode.duration_ms,
    episode.cover_url,
    episode.resolve_status,
    episode.transcription_status,
    episode.ai_status,
    episode.created_at,
    episode.updated_at,
    podcast.id AS podcast_id,
    podcast.title AS podcast_title,
    podcast.author AS podcast_author,
    podcast.description AS podcast_description,
    podcast.cover_url AS podcast_cover_url,
    podcast.feed_url AS podcast_feed_url,
    (
        SELECT count(*)
        FROM episode_sources AS source
        WHERE source.episode_id = episode.id
          AND source.user_id = episode.user_id
    )::bigint AS source_count,
    (
        SELECT count(*)
        FROM notes AS note
        WHERE note.episode_id = episode.id
          AND note.user_id = episode.user_id
          AND note.deleted_at IS NULL
    )::bigint AS note_count
FROM episodes AS episode
LEFT JOIN podcasts AS podcast
  ON podcast.id = episode.podcast_id
 AND podcast.user_id = episode.user_id
WHERE episode.user_id = $1
ORDER BY episode.created_at DESC, episode.id DESC
LIMIT $3::int
OFFSET $2::int
`

type ListLibraryEpisodesParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	PageOffset int32       `json:"page_offset"`
	PageLimit  int32       `json:"page_limit"`
}

type ListLibraryEpisodesRow struct {
	ID                  pgtype.UUID        `json:"id"`
	Title               string             `json:"title"`
	PublishedAt         pgtype.Timestamptz `json:"published_at"`
	DurationMs          int64              `json:"duration_ms"`
	CoverUrl            string             `json:"cover_url"`
	ResolveStatus       string             `json:"resolve_status"`
	TranscriptionStatus string             `json:"transcription_status"`
	AiStatus            string             `json:"ai_status"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	PodcastID           pgtype.UUID        `json:"podcast_id"`
	PodcastTitle        *string            `json:"podcast_title"`
	PodcastAuthor       *string            `json:"podcast_author"`
	PodcastDescription  *string            `json:"podcast_description"`
	PodcastCoverUrl     *string            `json:"podcast_cover_url"`
	PodcastFeedUrl      *string            `json:"podcast_feed_url"`
	SourceCount         int64              `json:"source_count"`
	NoteCount           int64              `json:"note_count"`
}

func (q *Queries) ListLibraryEpisodes(ctx context.Context, arg ListLibraryEpisodesParams) ([]ListLibraryEpisodesRow, error) {
	rows, err := q.db.Query(ctx, listLibraryEpisodes, arg.UserID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLibraryEpisodesRow{}
	for rows.Next() {
		var i ListLibraryEpisodesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.PublishedAt,
			&i.DurationMs,
			&i.CoverUrl,
			&i.ResolveStatus,
			&i.TranscriptionStatus,
			&i.AiStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PodcastID,
			&i.PodcastTitle,
			&i.PodcastAuthor,
			&i.PodcastDescription,
			&i.PodcastCoverUrl,
			&i.PodcastFeedUrl,
			&i.SourceCount,
			&i.NoteCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
