// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Job struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Type         string             `json:"type"`
	EntityType   string             `json:"entity_type"`
	EntityID     pgtype.UUID        `json:"entity_id"`
	Payload      []byte             `json:"payload"`
	Status       string             `json:"status"`
	Stage        string             `json:"stage"`
	Priority     int16              `json:"priority"`
	Attempt      int32              `json:"attempt"`
	MaxAttempts  int32              `json:"max_attempts"`
	RunAfter     pgtype.Timestamptz `json:"run_after"`
	LockedBy     *string            `json:"locked_by"`
	LockedAt     pgtype.Timestamptz `json:"locked_at"`
	ErrorCode    *string            `json:"error_code"`
	ErrorMessage *string            `json:"error_message"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
}

type JobEvent struct {
	ID        int64              `json:"id"`
	JobID     pgtype.UUID        `json:"job_id"`
	EventType string             `json:"event_type"`
	Stage     string             `json:"stage"`
	Data      []byte             `json:"data"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
