// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AiArtifact struct {
	ID                  pgtype.UUID        `json:"id"`
	UserID              pgtype.UUID        `json:"user_id"`
	EpisodeID           pgtype.UUID        `json:"episode_id"`
	TranscriptVersionID pgtype.UUID        `json:"transcript_version_id"`
	JobID               pgtype.UUID        `json:"job_id"`
	ArtifactType        string             `json:"artifact_type"`
	Model               string             `json:"model"`
	PromptVersion       string             `json:"prompt_version"`
	NotesRevision       string             `json:"notes_revision"`
	InputHash           string             `json:"input_hash"`
	Status              string             `json:"status"`
	Result              []byte             `json:"result"`
	SearchText          string             `json:"search_text"`
	ErrorCode           *string            `json:"error_code"`
	ErrorMessage        *string            `json:"error_message"`
	InputTokens         int32              `json:"input_tokens"`
	OutputTokens        int32              `json:"output_tokens"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	CompletedAt         pgtype.Timestamptz `json:"completed_at"`
}

type Conversation struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	EpisodeID pgtype.UUID        `json:"episode_id"`
	Scope     string             `json:"scope"`
	Title     string             `json:"title"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Episode struct {
	ID                  pgtype.UUID        `json:"id"`
	UserID              pgtype.UUID        `json:"user_id"`
	PodcastID           pgtype.UUID        `json:"podcast_id"`
	Title               string             `json:"title"`
	Description         string             `json:"description"`
	PublishedAt         pgtype.Timestamptz `json:"published_at"`
	DurationMs          int64              `json:"duration_ms"`
	CoverUrl            string             `json:"cover_url"`
	ResolveStatus       string             `json:"resolve_status"`
	TranscriptionStatus string             `json:"transcription_status"`
	AiStatus            string             `json:"ai_status"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type EpisodeIdentityKey struct {
	UserID      pgtype.UUID        `json:"user_id"`
	IdentityKey string             `json:"identity_key"`
	EpisodeID   pgtype.UUID        `json:"episode_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type EpisodeSource struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	EpisodeID    pgtype.UUID        `json:"episode_id"`
	SourceType   string             `json:"source_type"`
	ExternalID   *string            `json:"external_id"`
	SourceUrl    string             `json:"source_url"`
	CanonicalUrl string             `json:"canonical_url"`
	AudioUrl     string             `json:"audio_url"`
	RssGuid      *string            `json:"rss_guid"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Import struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	SubmittedUrl string             `json:"submitted_url"`
	JobID        pgtype.UUID        `json:"job_id"`
	EpisodeID    pgtype.UUID        `json:"episode_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Job struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Type         string             `json:"type"`
	EntityType   string             `json:"entity_type"`
	EntityID     pgtype.UUID        `json:"entity_id"`
	Payload      []byte             `json:"payload"`
	Status       string             `json:"status"`
	Stage        string             `json:"stage"`
	Priority     int16              `json:"priority"`
	Attempt      int32              `json:"attempt"`
	MaxAttempts  int32              `json:"max_attempts"`
	RunAfter     pgtype.Timestamptz `json:"run_after"`
	LockedBy     *string            `json:"locked_by"`
	LockedAt     pgtype.Timestamptz `json:"locked_at"`
	ErrorCode    *string            `json:"error_code"`
	ErrorMessage *string            `json:"error_message"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
}

type JobEvent struct {
	ID        int64              `json:"id"`
	JobID     pgtype.UUID        `json:"job_id"`
	EventType string             `json:"event_type"`
	Stage     string             `json:"stage"`
	Data      []byte             `json:"data"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Message struct {
	ID               pgtype.UUID        `json:"id"`
	ConversationID   pgtype.UUID        `json:"conversation_id"`
	ReplyToMessageID pgtype.UUID        `json:"reply_to_message_id"`
	ClientMessageID  pgtype.UUID        `json:"client_message_id"`
	Role             string             `json:"role"`
	Status           string             `json:"status"`
	Content          string             `json:"content"`
	Model            *string            `json:"model"`
	ErrorCode        *string            `json:"error_code"`
	ErrorMessage     *string            `json:"error_message"`
	InputTokens      int32              `json:"input_tokens"`
	OutputTokens     int32              `json:"output_tokens"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
}

type MessageCitation struct {
	ID                  pgtype.UUID        `json:"id"`
	MessageID           pgtype.UUID        `json:"message_id"`
	Position            int32              `json:"position"`
	TranscriptSegmentID pgtype.UUID        `json:"transcript_segment_id"`
	NoteID              pgtype.UUID        `json:"note_id"`
	Excerpt             string             `json:"excerpt"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type Note struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	EpisodeID    pgtype.UUID        `json:"episode_id"`
	ClientNoteID pgtype.UUID        `json:"client_note_id"`
	Content      string             `json:"content"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type Podcast struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Title       string             `json:"title"`
	Author      string             `json:"author"`
	Description string             `json:"description"`
	CoverUrl    string             `json:"cover_url"`
	FeedUrl     *string            `json:"feed_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type SearchChunk struct {
	ID               pgtype.UUID        `json:"id"`
	SearchDocumentID pgtype.UUID        `json:"search_document_id"`
	ChunkIndex       int32              `json:"chunk_index"`
	Text             string             `json:"text"`
	StartMs          *int64             `json:"start_ms"`
	EndMs            *int64             `json:"end_ms"`
	SpeakerID        pgtype.UUID        `json:"speaker_id"`
	Embedding        *string            `json:"embedding"`
	EmbeddingModel   *string            `json:"embedding_model"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type SearchDocument struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	EpisodeID    pgtype.UUID        `json:"episode_id"`
	DocumentType string             `json:"document_type"`
	SourceID     pgtype.UUID        `json:"source_id"`
	Content      string             `json:"content"`
	ContentHash  string             `json:"content_hash"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type TranscriptSegment struct {
	ID                  pgtype.UUID        `json:"id"`
	TranscriptVersionID pgtype.UUID        `json:"transcript_version_id"`
	SpeakerID           pgtype.UUID        `json:"speaker_id"`
	Sequence            int32              `json:"sequence"`
	StartMs             int64              `json:"start_ms"`
	EndMs               int64              `json:"end_ms"`
	Text                string             `json:"text"`
	Words               []byte             `json:"words"`
	SourceChunkID       pgtype.UUID        `json:"source_chunk_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type TranscriptSpeaker struct {
	ID                  pgtype.UUID        `json:"id"`
	TranscriptVersionID pgtype.UUID        `json:"transcript_version_id"`
	StableKey           string             `json:"stable_key"`
	DisplayName         string             `json:"display_name"`
	Role                string             `json:"role"`
	SpeakerProfileID    pgtype.UUID        `json:"speaker_profile_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type TranscriptVersion struct {
	ID                 pgtype.UUID        `json:"id"`
	UserID             pgtype.UUID        `json:"user_id"`
	EpisodeID          pgtype.UUID        `json:"episode_id"`
	TranscriptionRunID pgtype.UUID        `json:"transcription_run_id"`
	Version            int32              `json:"version"`
	IsActive           bool               `json:"is_active"`
	Status             string             `json:"status"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type TranscriptionChunk struct {
	ID                     pgtype.UUID        `json:"id"`
	TranscriptionRunID     pgtype.UUID        `json:"transcription_run_id"`
	Sequence               int32              `json:"sequence"`
	CoreStartMs            int64              `json:"core_start_ms"`
	CoreEndMs              int64              `json:"core_end_ms"`
	RenderStartMs          int64              `json:"render_start_ms"`
	RenderEndMs            int64              `json:"render_end_ms"`
	Status                 string             `json:"status"`
	ObjectKey              *string            `json:"object_key"`
	AudioHash              *string            `json:"audio_hash"`
	Fingerprint            *string            `json:"fingerprint"`
	ExternalTaskID         *string            `json:"external_task_id"`
	ResultUrl              *string            `json:"result_url"`
	RawResultObjectKey     *string            `json:"raw_result_object_key"`
	NormalizedResult       []byte             `json:"normalized_result"`
	SpeakerMap             []byte             `json:"speaker_map"`
	AlignmentLowConfidence bool               `json:"alignment_low_confidence"`
	ErrorCode              *string            `json:"error_code"`
	ErrorMessage           *string            `json:"error_message"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	CompletedAt            pgtype.Timestamptz `json:"completed_at"`
}

type TranscriptionEvent struct {
	ID                 int64              `json:"id"`
	TranscriptionRunID pgtype.UUID        `json:"transcription_run_id"`
	EventType          string             `json:"event_type"`
	Data               []byte             `json:"data"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type TranscriptionRun struct {
	ID                pgtype.UUID        `json:"id"`
	UserID            pgtype.UUID        `json:"user_id"`
	EpisodeID         pgtype.UUID        `json:"episode_id"`
	Profile           string             `json:"profile"`
	Provider          string             `json:"provider"`
	Model             string             `json:"model"`
	Status            string             `json:"status"`
	Stage             string             `json:"stage"`
	Version           int32              `json:"version"`
	Config            []byte             `json:"config"`
	SourceObjectKey   *string            `json:"source_object_key"`
	SourceAudioHash   *string            `json:"source_audio_hash"`
	PreparedObjectKey *string            `json:"prepared_object_key"`
	PreparedAudioHash *string            `json:"prepared_audio_hash"`
	DurationMs        *int64             `json:"duration_ms"`
	TotalChunks       int32              `json:"total_chunks"`
	CompletedChunks   int32              `json:"completed_chunks"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
	ErrorCode         *string            `json:"error_code"`
	ErrorMessage      *string            `json:"error_message"`
	AudioCleanedAt    pgtype.Timestamptz `json:"audio_cleaned_at"`
	ChunksCleanedAt   pgtype.Timestamptz `json:"chunks_cleaned_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
