// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireNoteClientIDLock = `-- name: AcquireNoteClientIDLock :exec
SELECT pg_advisory_xact_lock(hashtextextended($1, 0))
`

func (q *Queries) AcquireNoteClientIDLock(ctx context.Context, lockKey string) error {
	_, err := q.db.Exec(ctx, acquireNoteClientIDLock, lockKey)
	return err
}

const createNoteForEpisode = `-- name: CreateNoteForEpisode :one
INSERT INTO notes (user_id, episode_id, client_note_id, content, created_at)
SELECT
    $1,
    episode.id,
    $2,
    $3,
    $4
FROM episodes AS episode
WHERE episode.id = $5
  AND episode.user_id = $1
RETURNING notes.id, notes.user_id, notes.episode_id, notes.client_note_id, notes.content, notes.created_at, notes.updated_at, notes.deleted_at
`

type CreateNoteForEpisodeParams struct {
	UserID       pgtype.UUID        `json:"user_id"`
	ClientNoteID pgtype.UUID        `json:"client_note_id"`
	Content      string             `json:"content"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	EpisodeID    pgtype.UUID        `json:"episode_id"`
}

func (q *Queries) CreateNoteForEpisode(ctx context.Context, arg CreateNoteForEpisodeParams) (Note, error) {
	row := q.db.QueryRow(ctx, createNoteForEpisode,
		arg.UserID,
		arg.ClientNoteID,
		arg.Content,
		arg.CreatedAt,
		arg.EpisodeID,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EpisodeID,
		&i.ClientNoteID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createPendingEpisode = `-- name: CreatePendingEpisode :one
INSERT INTO episodes (user_id, title, resolve_status)
VALUES ($1, $2, 'pending')
RETURNING id, user_id, podcast_id, title, description, published_at, duration_ms, cover_url, resolve_status, transcription_status, ai_status, created_at, updated_at
`

type CreatePendingEpisodeParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Title  string      `json:"title"`
}

func (q *Queries) CreatePendingEpisode(ctx context.Context, arg CreatePendingEpisodeParams) (Episode, error) {
	row := q.db.QueryRow(ctx, createPendingEpisode, arg.UserID, arg.Title)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PodcastID,
		&i.Title,
		&i.Description,
		&i.PublishedAt,
		&i.DurationMs,
		&i.CoverUrl,
		&i.ResolveStatus,
		&i.TranscriptionStatus,
		&i.AiStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNote = `-- name: DeleteNote :one
UPDATE notes
SET deleted_at = COALESCE(deleted_at, now()),
    updated_at = CASE WHEN deleted_at IS NULL THEN now() ELSE updated_at END
WHERE id = $1
  AND user_id = $2
RETURNING id
`

type DeleteNoteParams struct {
	NoteID pgtype.UUID `json:"note_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteNote(ctx context.Context, arg DeleteNoteParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteNote, arg.NoteID, arg.UserID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deletePendingEpisode = `-- name: DeletePendingEpisode :exec
DELETE FROM episodes
WHERE id = $1
  AND user_id = $2
  AND resolve_status = 'pending'
`

type DeletePendingEpisodeParams struct {
	EpisodeID pgtype.UUID `json:"episode_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeletePendingEpisode(ctx context.Context, arg DeletePendingEpisodeParams) error {
	_, err := q.db.Exec(ctx, deletePendingEpisode, arg.EpisodeID, arg.UserID)
	return err
}

const getCaptureImport = `-- name: GetCaptureImport :one
SELECT import_record.id
FROM imports AS import_record
WHERE import_record.user_id = $1
  AND import_record.episode_id = $2
  AND import_record.submitted_url = $3
ORDER BY import_record.created_at DESC, import_record.id DESC
LIMIT 1
`

type GetCaptureImportParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	EpisodeID    pgtype.UUID `json:"episode_id"`
	SubmittedUrl string      `json:"submitted_url"`
}

func (q *Queries) GetCaptureImport(ctx context.Context, arg GetCaptureImportParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getCaptureImport, arg.UserID, arg.EpisodeID, arg.SubmittedUrl)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getEpisodeForResolve = `-- name: GetEpisodeForResolve :one
SELECT id, resolve_status
FROM episodes
WHERE id = $1
  AND user_id = $2
FOR UPDATE
`

type GetEpisodeForResolveParams struct {
	EpisodeID pgtype.UUID `json:"episode_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

type GetEpisodeForResolveRow struct {
	ID            pgtype.UUID `json:"id"`
	ResolveStatus string      `json:"resolve_status"`
}

func (q *Queries) GetEpisodeForResolve(ctx context.Context, arg GetEpisodeForResolveParams) (GetEpisodeForResolveRow, error) {
	row := q.db.QueryRow(ctx, getEpisodeForResolve, arg.EpisodeID, arg.UserID)
	var i GetEpisodeForResolveRow
	err := row.Scan(&i.ID, &i.ResolveStatus)
	return i, err
}

const getNoteByClientID = `-- name: GetNoteByClientID :one
SELECT id, user_id, episode_id, client_note_id, content, created_at, updated_at, deleted_at
FROM notes
WHERE user_id = $1
  AND client_note_id = $2
`

type GetNoteByClientIDParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	ClientNoteID pgtype.UUID `json:"client_note_id"`
}

func (q *Queries) GetNoteByClientID(ctx context.Context, arg GetNoteByClientIDParams) (Note, error) {
	row := q.db.QueryRow(ctx, getNoteByClientID, arg.UserID, arg.ClientNoteID)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EpisodeID,
		&i.ClientNoteID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOwnedEpisodeID = `-- name: GetOwnedEpisodeID :one
SELECT id
FROM episodes
WHERE id = $1
  AND user_id = $2
`

type GetOwnedEpisodeIDParams struct {
	EpisodeID pgtype.UUID `json:"episode_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetOwnedEpisodeID(ctx context.Context, arg GetOwnedEpisodeIDParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getOwnedEpisodeID, arg.EpisodeID, arg.UserID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listEpisodeNotes = `-- name: ListEpisodeNotes :many
SELECT id, user_id, episode_id, client_note_id, content, created_at, updated_at, deleted_at
FROM notes
WHERE episode_id = $1
  AND user_id = $2
  AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
`

type ListEpisodeNotesParams struct {
	EpisodeID pgtype.UUID `json:"episode_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) ListEpisodeNotes(ctx context.Context, arg ListEpisodeNotesParams) ([]Note, error) {
	rows, err := q.db.Query(ctx, listEpisodeNotes, arg.EpisodeID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EpisodeID,
			&i.ClientNoteID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOwnedEpisodeForNote = `-- name: LockOwnedEpisodeForNote :one
SELECT id
FROM episodes
WHERE id = $1
  AND user_id = $2
FOR KEY SHARE
`

type LockOwnedEpisodeForNoteParams struct {
	EpisodeID pgtype.UUID `json:"episode_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) LockOwnedEpisodeForNote(ctx context.Context, arg LockOwnedEpisodeForNoteParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockOwnedEpisodeForNote, arg.EpisodeID, arg.UserID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const moveEpisodeNotes = `-- name: MoveEpisodeNotes :exec
UPDATE notes
SET episode_id = $1,
    updated_at = now()
WHERE episode_id = $2
  AND user_id = $3
`

type MoveEpisodeNotesParams struct {
	TargetEpisodeID pgtype.UUID `json:"target_episode_id"`
	SourceEpisodeID pgtype.UUID `json:"source_episode_id"`
	UserID          pgtype.UUID `json:"user_id"`
}

func (q *Queries) MoveEpisodeNotes(ctx context.Context, arg MoveEpisodeNotesParams) error {
	_, err := q.db.Exec(ctx, moveEpisodeNotes, arg.TargetEpisodeID, arg.SourceEpisodeID, arg.UserID)
	return err
}

const resolvePendingEpisode = `-- name: ResolvePendingEpisode :one
UPDATE episodes
SET podcast_id = $1::uuid,
    title = $2,
    description = $3,
    published_at = $4::timestamptz,
    duration_ms = $5,
    cover_url = $6,
    resolve_status = 'completed',
    updated_at = now()
WHERE id = $7
  AND user_id = $8
  AND resolve_status = 'pending'
RETURNING id, user_id, podcast_id, title, description, published_at, duration_ms, cover_url, resolve_status, transcription_status, ai_status, created_at, updated_at
`

type ResolvePendingEpisodeParams struct {
	PodcastID   pgtype.UUID        `json:"podcast_id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	DurationMs  int64              `json:"duration_ms"`
	CoverUrl    string             `json:"cover_url"`
	EpisodeID   pgtype.UUID        `json:"episode_id"`
	UserID      pgtype.UUID        `json:"user_id"`
}

func (q *Queries) ResolvePendingEpisode(ctx context.Context, arg ResolvePendingEpisodeParams) (Episode, error) {
	row := q.db.QueryRow(ctx, resolvePendingEpisode,
		arg.PodcastID,
		arg.Title,
		arg.Description,
		arg.PublishedAt,
		arg.DurationMs,
		arg.CoverUrl,
		arg.EpisodeID,
		arg.UserID,
	)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PodcastID,
		&i.Title,
		&i.Description,
		&i.PublishedAt,
		&i.DurationMs,
		&i.CoverUrl,
		&i.ResolveStatus,
		&i.TranscriptionStatus,
		&i.AiStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNote = `-- name: UpdateNote :one
UPDATE notes
SET content = $1,
    updated_at = now()
WHERE id = $2
  AND user_id = $3
  AND deleted_at IS NULL
RETURNING id, user_id, episode_id, client_note_id, content, created_at, updated_at, deleted_at
`

type UpdateNoteParams struct {
	Content string      `json:"content"`
	NoteID  pgtype.UUID `json:"note_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, updateNote, arg.Content, arg.NoteID, arg.UserID)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EpisodeID,
		&i.ClientNoteID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
