// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: search.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelEpisodeSearchJobs = `-- name: CancelEpisodeSearchJobs :many
UPDATE jobs AS job
SET status = 'canceled',
    stage = 'canceled',
    locked_by = NULL,
    locked_at = NULL,
    error_code = NULL,
    error_message = NULL,
    updated_at = now(),
    completed_at = now()
WHERE job.user_id = $1
  AND job.status IN ('queued', 'running')
  AND (
      (job.type = 'build_keyword_index' AND job.entity_type = 'episode' AND job.entity_id = $2)
      OR
      (job.type = 'generate_embeddings' AND job.entity_type = 'search_document' AND job.entity_id IN (
          SELECT document.id
          FROM search_documents AS document
          WHERE document.user_id = $1
            AND document.episode_id = $2
      ))
  )
RETURNING job.id, job.user_id, job.type, job.entity_type, job.entity_id, job.payload, job.status, job.stage, job.priority, job.attempt, job.max_attempts, job.run_after, job.locked_by, job.locked_at, job.error_code, job.error_message, job.created_at, job.updated_at, job.completed_at
`

type CancelEpisodeSearchJobsParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	EpisodeID pgtype.UUID `json:"episode_id"`
}

func (q *Queries) CancelEpisodeSearchJobs(ctx context.Context, arg CancelEpisodeSearchJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, cancelEpisodeSearchJobs, arg.UserID, arg.EpisodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.EntityType,
			&i.EntityID,
			&i.Payload,
			&i.Status,
			&i.Stage,
			&i.Priority,
			&i.Attempt,
			&i.MaxAttempts,
			&i.RunAfter,
			&i.LockedBy,
			&i.LockedAt,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countPendingSearchEmbeddings = `-- name: CountPendingSearchEmbeddings :one
SELECT count(*)
FROM search_chunks AS chunk
JOIN search_documents AS document ON document.id = chunk.search_document_id
WHERE document.id = $1
  AND document.user_id = $2
  AND (chunk.embedding IS NULL OR chunk.embedding_model IS DISTINCT FROM $3)
`

type CountPendingSearchEmbeddingsParams struct {
	DocumentID     pgtype.UUID `json:"document_id"`
	UserID         pgtype.UUID `json:"user_id"`
	EmbeddingModel *string     `json:"embedding_model"`
}

func (q *Queries) CountPendingSearchEmbeddings(ctx context.Context, arg CountPendingSearchEmbeddingsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingSearchEmbeddings, arg.DocumentID, arg.UserID, arg.EmbeddingModel)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSearchChunk = `-- name: CreateSearchChunk :exec
INSERT INTO search_chunks (
    search_document_id,
    chunk_index,
    text,
    start_ms,
    end_ms,
    speaker_id
) VALUES (
    $1,
    $2,
    $3,
    $4::bigint,
    $5::bigint,
    $6::uuid
)
`

type CreateSearchChunkParams struct {
	DocumentID pgtype.UUID `json:"document_id"`
	ChunkIndex int32       `json:"chunk_index"`
	Text       string      `json:"text"`
	StartMs    *int64      `json:"start_ms"`
	EndMs      *int64      `json:"end_ms"`
	SpeakerID  pgtype.UUID `json:"speaker_id"`
}

func (q *Queries) CreateSearchChunk(ctx context.Context, arg CreateSearchChunkParams) error {
	_, err := q.db.Exec(ctx, createSearchChunk,
		arg.DocumentID,
		arg.ChunkIndex,
		arg.Text,
		arg.StartMs,
		arg.EndMs,
		arg.SpeakerID,
	)
	return err
}

const createSearchDocument = `-- name: CreateSearchDocument :one
INSERT INTO search_documents (
    user_id,
    episode_id,
    document_type,
    source_id,
    content,
    content_hash,
    metadata
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7::jsonb
)
RETURNING id, user_id, episode_id, document_type, source_id, content, content_hash, metadata, created_at, updated_at
`

type CreateSearchDocumentParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	EpisodeID    pgtype.UUID `json:"episode_id"`
	DocumentType string      `json:"document_type"`
	SourceID     pgtype.UUID `json:"source_id"`
	Content      string      `json:"content"`
	ContentHash  string      `json:"content_hash"`
	Metadata     []byte      `json:"metadata"`
}

func (q *Queries) CreateSearchDocument(ctx context.Context, arg CreateSearchDocumentParams) (SearchDocument, error) {
	row := q.db.QueryRow(ctx, createSearchDocument,
		arg.UserID,
		arg.EpisodeID,
		arg.DocumentType,
		arg.SourceID,
		arg.Content,
		arg.ContentHash,
		arg.Metadata,
	)
	var i SearchDocument
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EpisodeID,
		&i.DocumentType,
		&i.SourceID,
		&i.Content,
		&i.ContentHash,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSearchDocument = `-- name: DeleteSearchDocument :exec
DELETE FROM search_documents
WHERE id = $1
  AND user_id = $2
`

type DeleteSearchDocumentParams struct {
	DocumentID pgtype.UUID `json:"document_id"`
	UserID     pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteSearchDocument(ctx context.Context, arg DeleteSearchDocumentParams) error {
	_, err := q.db.Exec(ctx, deleteSearchDocument, arg.DocumentID, arg.UserID)
	return err
}

const deleteSearchDocumentChunks = `-- name: DeleteSearchDocumentChunks :exec
DELETE FROM search_chunks
WHERE search_document_id = $1
`

func (q *Queries) DeleteSearchDocumentChunks(ctx context.Context, documentID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSearchDocumentChunks, documentID)
	return err
}

const keywordSearch = `-- name: KeywordSearch :many
SELECT
    chunk.id AS chunk_id,
    document.document_type,
    document.source_id,
    document.episode_id,
    episode.title AS episode_title,
    COALESCE(podcast.title, '') AS podcast_title,
    chunk.speaker_id,
    COALESCE(speaker.display_name, '') AS speaker_name,
    chunk.start_ms,
    chunk.end_ms,
    chunk.text,
    CASE
        WHEN position(lower($1) IN lower(chunk.text)) > 0 THEN 1.0
        ELSE word_similarity(lower($1), lower(chunk.text))
    END::double precision AS rank_score
FROM search_chunks AS chunk
JOIN search_documents AS document ON document.id = chunk.search_document_id
JOIN episodes AS episode ON episode.id = document.episode_id AND episode.user_id = document.user_id
LEFT JOIN podcasts AS podcast ON podcast.id = episode.podcast_id AND podcast.user_id = episode.user_id
LEFT JOIN transcript_speakers AS speaker ON speaker.id = chunk.speaker_id
WHERE document.user_id = $2
  AND ($3::uuid IS NULL OR document.episode_id = $3::uuid)
  AND (
      position(lower($1) IN lower(chunk.text)) > 0
      OR word_similarity(lower($1), lower(chunk.text)) >= 0.2
  )
ORDER BY rank_score DESC, document.updated_at DESC, chunk.id
LIMIT $4::int
`

type KeywordSearchParams struct {
	Query          string      `json:"query"`
	UserID         pgtype.UUID `json:"user_id"`
	EpisodeID      pgtype.UUID `json:"episode_id"`
	CandidateLimit int32       `json:"candidate_limit"`
}

type KeywordSearchRow struct {
	ChunkID      pgtype.UUID `json:"chunk_id"`
	DocumentType string      `json:"document_type"`
	SourceID     pgtype.UUID `json:"source_id"`
	EpisodeID    pgtype.UUID `json:"episode_id"`
	EpisodeTitle string      `json:"episode_title"`
	PodcastTitle string      `json:"podcast_title"`
	SpeakerID    pgtype.UUID `json:"speaker_id"`
	SpeakerName  string      `json:"speaker_name"`
	StartMs      *int64      `json:"start_ms"`
	EndMs        *int64      `json:"end_ms"`
	Text         string      `json:"text"`
	RankScore    float64     `json:"rank_score"`
}

func (q *Queries) KeywordSearch(ctx context.Context, arg KeywordSearchParams) ([]KeywordSearchRow, error) {
	rows, err := q.db.Query(ctx, keywordSearch,
		arg.Query,
		arg.UserID,
		arg.EpisodeID,
		arg.CandidateLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KeywordSearchRow{}
	for rows.Next() {
		var i KeywordSearchRow
		if err := rows.Scan(
			&i.ChunkID,
			&i.DocumentType,
			&i.SourceID,
			&i.EpisodeID,
			&i.EpisodeTitle,
			&i.PodcastTitle,
			&i.SpeakerID,
			&i.SpeakerName,
			&i.StartMs,
			&i.EndMs,
			&i.Text,
			&i.RankScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnedEpisodeIDsForSearch = `-- name: ListOwnedEpisodeIDsForSearch :many
SELECT id
FROM episodes
WHERE user_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListOwnedEpisodeIDsForSearch(ctx context.Context, userID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listOwnedEpisodeIDsForSearch, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingSearchEmbeddings = `-- name: ListPendingSearchEmbeddings :many
SELECT chunk.id, chunk.text
FROM search_chunks AS chunk
JOIN search_documents AS document ON document.id = chunk.search_document_id
WHERE document.id = $1
  AND document.user_id = $2
  AND document.content_hash = $3
  AND (chunk.embedding IS NULL OR chunk.embedding_model IS DISTINCT FROM $4)
ORDER BY chunk.chunk_index
LIMIT $5::int
`

type ListPendingSearchEmbeddingsParams struct {
	DocumentID     pgtype.UUID `json:"document_id"`
	UserID         pgtype.UUID `json:"user_id"`
	ContentHash    string      `json:"content_hash"`
	EmbeddingModel *string     `json:"embedding_model"`
	BatchLimit     int32       `json:"batch_limit"`
}

type ListPendingSearchEmbeddingsRow struct {
	ID   pgtype.UUID `json:"id"`
	Text string      `json:"text"`
}

func (q *Queries) ListPendingSearchEmbeddings(ctx context.Context, arg ListPendingSearchEmbeddingsParams) ([]ListPendingSearchEmbeddingsRow, error) {
	rows, err := q.db.Query(ctx, listPendingSearchEmbeddings,
		arg.DocumentID,
		arg.UserID,
		arg.ContentHash,
		arg.EmbeddingModel,
		arg.BatchLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingSearchEmbeddingsRow{}
	for rows.Next() {
		var i ListPendingSearchEmbeddingsRow
		if err := rows.Scan(&i.ID, &i.Text); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSearchDocumentsForEpisode = `-- name: ListSearchDocumentsForEpisode :many
SELECT id, user_id, episode_id, document_type, source_id, content, content_hash, metadata, created_at, updated_at
FROM search_documents
WHERE user_id = $1
  AND episode_id = $2
  AND document_type IN ('note', 'transcript')
ORDER BY document_type, source_id
`

type ListSearchDocumentsForEpisodeParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	EpisodeID pgtype.UUID `json:"episode_id"`
}

func (q *Queries) ListSearchDocumentsForEpisode(ctx context.Context, arg ListSearchDocumentsForEpisodeParams) ([]SearchDocument, error) {
	rows, err := q.db.Query(ctx, listSearchDocumentsForEpisode, arg.UserID, arg.EpisodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchDocument{}
	for rows.Next() {
		var i SearchDocument
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EpisodeID,
			&i.DocumentType,
			&i.SourceID,
			&i.Content,
			&i.ContentHash,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTranscriptSegmentsForSearch = `-- name: ListTranscriptSegmentsForSearch :many
SELECT
    segment.id,
    segment.speaker_id,
    segment.sequence,
    segment.start_ms,
    segment.end_ms,
    segment.text
FROM transcript_segments AS segment
JOIN transcript_versions AS version ON version.id = segment.transcript_version_id
WHERE segment.transcript_version_id = $1
  AND version.user_id = $2
ORDER BY segment.sequence
`

type ListTranscriptSegmentsForSearchParams struct {
	TranscriptID pgtype.UUID `json:"transcript_id"`
	UserID       pgtype.UUID `json:"user_id"`
}

type ListTranscriptSegmentsForSearchRow struct {
	ID        pgtype.UUID `json:"id"`
	SpeakerID pgtype.UUID `json:"speaker_id"`
	Sequence  int32       `json:"sequence"`
	StartMs   int64       `json:"start_ms"`
	EndMs     int64       `json:"end_ms"`
	Text      string      `json:"text"`
}

func (q *Queries) ListTranscriptSegmentsForSearch(ctx context.Context, arg ListTranscriptSegmentsForSearchParams) ([]ListTranscriptSegmentsForSearchRow, error) {
	rows, err := q.db.Query(ctx, listTranscriptSegmentsForSearch, arg.TranscriptID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTranscriptSegmentsForSearchRow{}
	for rows.Next() {
		var i ListTranscriptSegmentsForSearchRow
		if err := rows.Scan(
			&i.ID,
			&i.SpeakerID,
			&i.Sequence,
			&i.StartMs,
			&i.EndMs,
			&i.Text,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOwnedEpisodeForSearch = `-- name: LockOwnedEpisodeForSearch :one
SELECT id
FROM episodes
WHERE id = $1
  AND user_id = $2
FOR UPDATE
`

type LockOwnedEpisodeForSearchParams struct {
	EpisodeID pgtype.UUID `json:"episode_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) LockOwnedEpisodeForSearch(ctx context.Context, arg LockOwnedEpisodeForSearchParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockOwnedEpisodeForSearch, arg.EpisodeID, arg.UserID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const semanticSearch = `-- name: SemanticSearch :many
SELECT
    chunk.id AS chunk_id,
    document.document_type,
    document.source_id,
    document.episode_id,
    episode.title AS episode_title,
    COALESCE(podcast.title, '') AS podcast_title,
    chunk.speaker_id,
    COALESCE(speaker.display_name, '') AS speaker_name,
    chunk.start_ms,
    chunk.end_ms,
    chunk.text,
    (1 - (chunk.embedding <=> $1::text::vector))::double precision AS rank_score
FROM search_chunks AS chunk
JOIN search_documents AS document ON document.id = chunk.search_document_id
JOIN episodes AS episode ON episode.id = document.episode_id AND episode.user_id = document.user_id
LEFT JOIN podcasts AS podcast ON podcast.id = episode.podcast_id AND podcast.user_id = episode.user_id
LEFT JOIN transcript_speakers AS speaker ON speaker.id = chunk.speaker_id
WHERE document.user_id = $2
  AND ($3::uuid IS NULL OR document.episode_id = $3::uuid)
  AND chunk.embedding IS NOT NULL
  AND chunk.embedding_model = $4
ORDER BY chunk.embedding <=> $1::text::vector, chunk.id
LIMIT $5::int
`

type SemanticSearchParams struct {
	QueryEmbedding string      `json:"query_embedding"`
	UserID         pgtype.UUID `json:"user_id"`
	EpisodeID      pgtype.UUID `json:"episode_id"`
	EmbeddingModel *string     `json:"embedding_model"`
	CandidateLimit int32       `json:"candidate_limit"`
}

type SemanticSearchRow struct {
	ChunkID      pgtype.UUID `json:"chunk_id"`
	DocumentType string      `json:"document_type"`
	SourceID     pgtype.UUID `json:"source_id"`
	EpisodeID    pgtype.UUID `json:"episode_id"`
	EpisodeTitle string      `json:"episode_title"`
	PodcastTitle string      `json:"podcast_title"`
	SpeakerID    pgtype.UUID `json:"speaker_id"`
	SpeakerName  string      `json:"speaker_name"`
	StartMs      *int64      `json:"start_ms"`
	EndMs        *int64      `json:"end_ms"`
	Text         string      `json:"text"`
	RankScore    float64     `json:"rank_score"`
}

func (q *Queries) SemanticSearch(ctx context.Context, arg SemanticSearchParams) ([]SemanticSearchRow, error) {
	rows, err := q.db.Query(ctx, semanticSearch,
		arg.QueryEmbedding,
		arg.UserID,
		arg.EpisodeID,
		arg.EmbeddingModel,
		arg.CandidateLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SemanticSearchRow{}
	for rows.Next() {
		var i SemanticSearchRow
		if err := rows.Scan(
			&i.ChunkID,
			&i.DocumentType,
			&i.SourceID,
			&i.EpisodeID,
			&i.EpisodeTitle,
			&i.PodcastTitle,
			&i.SpeakerID,
			&i.SpeakerName,
			&i.StartMs,
			&i.EndMs,
			&i.Text,
			&i.RankScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSearchChunkEmbedding = `-- name: SetSearchChunkEmbedding :execrows
UPDATE search_chunks AS chunk
SET embedding = $1::text::vector,
    embedding_model = $2,
    updated_at = now()
FROM search_documents AS document
WHERE chunk.id = $3
  AND document.id = chunk.search_document_id
  AND document.user_id = $4
  AND document.content_hash = $5
`

type SetSearchChunkEmbeddingParams struct {
	Embedding      string      `json:"embedding"`
	EmbeddingModel *string     `json:"embedding_model"`
	ChunkID        pgtype.UUID `json:"chunk_id"`
	UserID         pgtype.UUID `json:"user_id"`
	ContentHash    string      `json:"content_hash"`
}

func (q *Queries) SetSearchChunkEmbedding(ctx context.Context, arg SetSearchChunkEmbeddingParams) (int64, error) {
	result, err := q.db.Exec(ctx, setSearchChunkEmbedding,
		arg.Embedding,
		arg.EmbeddingModel,
		arg.ChunkID,
		arg.UserID,
		arg.ContentHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSearchDocument = `-- name: UpdateSearchDocument :one
UPDATE search_documents
SET episode_id = $1,
    content = $2,
    content_hash = $3,
    metadata = $4::jsonb,
    updated_at = now()
WHERE id = $5
  AND user_id = $6
RETURNING id, user_id, episode_id, document_type, source_id, content, content_hash, metadata, created_at, updated_at
`

type UpdateSearchDocumentParams struct {
	EpisodeID   pgtype.UUID `json:"episode_id"`
	Content     string      `json:"content"`
	ContentHash string      `json:"content_hash"`
	Metadata    []byte      `json:"metadata"`
	DocumentID  pgtype.UUID `json:"document_id"`
	UserID      pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateSearchDocument(ctx context.Context, arg UpdateSearchDocumentParams) (SearchDocument, error) {
	row := q.db.QueryRow(ctx, updateSearchDocument,
		arg.EpisodeID,
		arg.Content,
		arg.ContentHash,
		arg.Metadata,
		arg.DocumentID,
		arg.UserID,
	)
	var i SearchDocument
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EpisodeID,
		&i.DocumentType,
		&i.SourceID,
		&i.Content,
		&i.ContentHash,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
