// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transcription.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearChunkExternalTask = `-- name: ClearChunkExternalTask :exec
UPDATE transcription_chunks
SET external_task_id = NULL,
    result_url = NULL,
    updated_at = now()
WHERE id = $1
  AND status IN ('submitted', 'running')
`

func (q *Queries) ClearChunkExternalTask(ctx context.Context, chunkID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearChunkExternalTask, chunkID)
	return err
}

const completeTranscriptionRun = `-- name: CompleteTranscriptionRun :one
UPDATE transcription_runs
SET status = 'completed',
    stage = 'completed',
    error_code = NULL,
    error_message = NULL,
    updated_at = now(),
    completed_at = now()
WHERE id = $1
  AND status = 'merging'
RETURNING id, user_id, episode_id, profile, provider, model, status, stage, version, config, source_object_key, source_audio_hash, prepared_object_key, prepared_audio_hash, duration_ms, total_chunks, completed_chunks, started_at, completed_at, error_code, error_message, audio_cleaned_at, chunks_cleaned_at, created_at, updated_at
`

func (q *Queries) CompleteTranscriptionRun(ctx context.Context, runID pgtype.UUID) (TranscriptionRun, error) {
	row := q.db.QueryRow(ctx, completeTranscriptionRun, runID)
	var i TranscriptionRun
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EpisodeID,
		&i.Profile,
		&i.Provider,
		&i.Model,
		&i.Status,
		&i.Stage,
		&i.Version,
		&i.Config,
		&i.SourceObjectKey,
		&i.SourceAudioHash,
		&i.PreparedObjectKey,
		&i.PreparedAudioHash,
		&i.DurationMs,
		&i.TotalChunks,
		&i.CompletedChunks,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.AudioCleanedAt,
		&i.ChunksCleanedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countTranscriptSegments = `-- name: CountTranscriptSegments :one
SELECT count(*)
FROM transcript_segments AS segment
JOIN transcript_versions AS version ON version.id = segment.transcript_version_id
WHERE segment.transcript_version_id = $1
  AND version.user_id = $2
`

type CountTranscriptSegmentsParams struct {
	TranscriptID pgtype.UUID `json:"transcript_id"`
	UserID       pgtype.UUID `json:"user_id"`
}

func (q *Queries) CountTranscriptSegments(ctx context.Context, arg CountTranscriptSegmentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTranscriptSegments, arg.TranscriptID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTranscriptSegment = `-- name: CreateTranscriptSegment :one
INSERT INTO transcript_segments (
    transcript_version_id,
    speaker_id,
    sequence,
    start_ms,
    end_ms,
    text,
    words,
    source_chunk_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7::jsonb,
    $8
)
RETURNING id, transcript_version_id, speaker_id, sequence, start_ms, end_ms, text, words, source_chunk_id, created_at
`

type CreateTranscriptSegmentParams struct {
	TranscriptID  pgtype.UUID `json:"transcript_id"`
	SpeakerID     pgtype.UUID `json:"speaker_id"`
	Sequence      int32       `json:"sequence"`
	StartMs       int64       `json:"start_ms"`
	EndMs         int64       `json:"end_ms"`
	Text          string      `json:"text"`
	Words         []byte      `json:"words"`
	SourceChunkID pgtype.UUID `json:"source_chunk_id"`
}

func (q *Queries) CreateTranscriptSegment(ctx context.Context, arg CreateTranscriptSegmentParams) (TranscriptSegment, error) {
	row := q.db.QueryRow(ctx, createTranscriptSegment,
		arg.TranscriptID,
		arg.SpeakerID,
		arg.Sequence,
		arg.StartMs,
		arg.EndMs,
		arg.Text,
		arg.Words,
		arg.SourceChunkID,
	)
	var i TranscriptSegment
	err := row.Scan(
		&i.ID,
		&i.TranscriptVersionID,
		&i.SpeakerID,
		&i.Sequence,
		&i.StartMs,
		&i.EndMs,
		&i.Text,
		&i.Words,
		&i.SourceChunkID,
		&i.CreatedAt,
	)
	return i, err
}

const createTranscriptSpeaker = `-- name: CreateTranscriptSpeaker :one
INSERT INTO transcript_speakers (
    transcript_version_id,
    stable_key,
    display_name,
    role
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, transcript_version_id, stable_key, display_name, role, speaker_profile_id, created_at, updated_at
`

type CreateTranscriptSpeakerParams struct {
	TranscriptID pgtype.UUID `json:"transcript_id"`
	StableKey    string      `json:"stable_key"`
	DisplayName  string      `json:"display_name"`
	Role         string      `json:"role"`
}

func (q *Queries) CreateTranscriptSpeaker(ctx context.Context, arg CreateTranscriptSpeakerParams) (TranscriptSpeaker, error) {
	row := q.db.QueryRow(ctx, createTranscriptSpeaker,
		arg.TranscriptID,
		arg.StableKey,
		arg.DisplayName,
		arg.Role,
	)
	var i TranscriptSpeaker
	err := row.Scan(
		&i.ID,
		&i.TranscriptVersionID,
		&i.StableKey,
		&i.DisplayName,
		&i.Role,
		&i.SpeakerProfileID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTranscriptVersion = `-- name: CreateTranscriptVersion :one
INSERT INTO transcript_versions (
    user_id,
    episode_id,
    transcription_run_id,
    version,
    is_active
) VALUES (
    $1,
    $2,
    $3,
    $4,
    true
)
RETURNING id, user_id, episode_id, transcription_run_id, version, is_active, status, created_at
`

type CreateTranscriptVersionParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	EpisodeID pgtype.UUID `json:"episode_id"`
	RunID     pgtype.UUID `json:"run_id"`
	Version   int32       `json:"version"`
}

func (q *Queries) CreateTranscriptVersion(ctx context.Context, arg CreateTranscriptVersionParams) (TranscriptVersion, error) {
	row := q.db.QueryRow(ctx, createTranscriptVersion,
		arg.UserID,
		arg.EpisodeID,
		arg.RunID,
		arg.Version,
	)
	var i TranscriptVersion
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EpisodeID,
		&i.TranscriptionRunID,
		&i.Version,
		&i.IsActive,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createTranscriptionChunk = `-- name: CreateTranscriptionChunk :one
INSERT INTO transcription_chunks (
    transcription_run_id,
    sequence,
    core_start_ms,
    core_end_ms,
    render_start_ms,
    render_end_ms
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, transcription_run_id, sequence, core_start_ms, core_end_ms, render_start_ms, render_end_ms, status, object_key, audio_hash, fingerprint, external_task_id, result_url, raw_result_object_key, normalized_result, speaker_map, alignment_low_confidence, error_code, error_message, created_at, updated_at, completed_at
`

type CreateTranscriptionChunkParams struct {
	RunID         pgtype.UUID `json:"run_id"`
	Sequence      int32       `json:"sequence"`
	CoreStartMs   int64       `json:"core_start_ms"`
	CoreEndMs     int64       `json:"core_end_ms"`
	RenderStartMs int64       `json:"render_start_ms"`
	RenderEndMs   int64       `json:"render_end_ms"`
}

func (q *Queries) CreateTranscriptionChunk(ctx context.Context, arg CreateTranscriptionChunkParams) (TranscriptionChunk, error) {
	row := q.db.QueryRow(ctx, createTranscriptionChunk,
		arg.RunID,
		arg.Sequence,
		arg.CoreStartMs,
		arg.CoreEndMs,
		arg.RenderStartMs,
		arg.RenderEndMs,
	)
	var i TranscriptionChunk
	err := row.Scan(
		&i.ID,
		&i.TranscriptionRunID,
		&i.Sequence,
		&i.CoreStartMs,
		&i.CoreEndMs,
		&i.RenderStartMs,
		&i.RenderEndMs,
		&i.Status,
		&i.ObjectKey,
		&i.AudioHash,
		&i.Fingerprint,
		&i.ExternalTaskID,
		&i.ResultUrl,
		&i.RawResultObjectKey,
		&i.NormalizedResult,
		&i.SpeakerMap,
		&i.AlignmentLowConfidence,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createTranscriptionEvent = `-- name: CreateTranscriptionEvent :one
INSERT INTO transcription_events (transcription_run_id, event_type, data)
VALUES ($1, $2, $3::jsonb)
RETURNING id, transcription_run_id, event_type, data, created_at
`

type CreateTranscriptionEventParams struct {
	RunID     pgtype.UUID `json:"run_id"`
	EventType string      `json:"event_type"`
	Data      []byte      `json:"data"`
}

func (q *Queries) CreateTranscriptionEvent(ctx context.Context, arg CreateTranscriptionEventParams) (TranscriptionEvent, error) {
	row := q.db.QueryRow(ctx, createTranscriptionEvent, arg.RunID, arg.EventType, arg.Data)
	var i TranscriptionEvent
	err := row.Scan(
		&i.ID,
		&i.TranscriptionRunID,
		&i.EventType,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const createTranscriptionRun = `-- name: CreateTranscriptionRun :one
INSERT INTO transcription_runs (
    user_id,
    episode_id,
    profile,
    provider,
    model,
    config
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6::jsonb
)
RETURNING id, user_id, episode_id, profile, provider, model, status, stage, version, config, source_object_key, source_audio_hash, prepared_object_key, prepared_audio_hash, duration_ms, total_chunks, completed_chunks, started_at, completed_at, error_code, error_message, audio_cleaned_at, chunks_cleaned_at, created_at, updated_at
`

type CreateTranscriptionRunParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	EpisodeID pgtype.UUID `json:"episode_id"`
	Profile   string      `json:"profile"`
	Provider  string      `json:"provider"`
	Model     string      `json:"model"`
	Config    []byte      `json:"config"`
}

func (q *Queries) CreateTranscriptionRun(ctx context.Context, arg CreateTranscriptionRunParams) (TranscriptionRun, error) {
	row := q.db.QueryRow(ctx, createTranscriptionRun,
		arg.UserID,
		arg.EpisodeID,
		arg.Profile,
		arg.Provider,
		arg.Model,
		arg.Config,
	)
	var i TranscriptionRun
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EpisodeID,
		&i.Profile,
		&i.Provider,
		&i.Model,
		&i.Status,
		&i.Stage,
		&i.Version,
		&i.Config,
		&i.SourceObjectKey,
		&i.SourceAudioHash,
		&i.PreparedObjectKey,
		&i.PreparedAudioHash,
		&i.DurationMs,
		&i.TotalChunks,
		&i.CompletedChunks,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.AudioCleanedAt,
		&i.ChunksCleanedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateTranscriptVersions = `-- name: DeactivateTranscriptVersions :exec
UPDATE transcript_versions
SET is_active = false
WHERE episode_id = $1
  AND is_active
`

func (q *Queries) DeactivateTranscriptVersions(ctx context.Context, episodeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateTranscriptVersions, episodeID)
	return err
}

const failTranscriptionChunk = `-- name: FailTranscriptionChunk :exec
UPDATE transcription_chunks
SET status = 'failed',
    error_code = $1,
    error_message = $2,
    updated_at = now(),
    completed_at = NULL
WHERE id = $3
  AND status NOT IN ('completed', 'failed', 'canceled')
`

type FailTranscriptionChunkParams struct {
	ErrorCode    *string     `json:"error_code"`
	ErrorMessage *string     `json:"error_message"`
	ChunkID      pgtype.UUID `json:"chunk_id"`
}

func (q *Queries) FailTranscriptionChunk(ctx context.Context, arg FailTranscriptionChunkParams) error {
	_, err := q.db.Exec(ctx, failTranscriptionChunk, arg.ErrorCode, arg.ErrorMessage, arg.ChunkID)
	return err
}

const failTranscriptionRun = `-- name: FailTranscriptionRun :one
UPDATE transcription_runs
SET status = 'failed',
    stage = 'failed',
    error_code = $1,
    error_message = $2,
    updated_at = now(),
    completed_at = now()
WHERE id = $3
  AND status NOT IN ('completed', 'failed', 'canceled')
RETURNING id, user_id, episode_id, profile, provider, model, status, stage, version, config, source_object_key, source_audio_hash, prepared_object_key, prepared_audio_hash, duration_ms, total_chunks, completed_chunks, started_at, completed_at, error_code, error_message, audio_cleaned_at, chunks_cleaned_at, created_at, updated_at
`

type FailTranscriptionRunParams struct {
	ErrorCode    *string     `json:"error_code"`
	ErrorMessage *string     `json:"error_message"`
	RunID        pgtype.UUID `json:"run_id"`
}

func (q *Queries) FailTranscriptionRun(ctx context.Context, arg FailTranscriptionRunParams) (TranscriptionRun, error) {
	row := q.db.QueryRow(ctx, failTranscriptionRun, arg.ErrorCode, arg.ErrorMessage, arg.RunID)
	var i TranscriptionRun
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EpisodeID,
		&i.Profile,
		&i.Provider,
		&i.Model,
		&i.Status,
		&i.Stage,
		&i.Version,
		&i.Config,
		&i.SourceObjectKey,
		&i.SourceAudioHash,
		&i.PreparedObjectKey,
		&i.PreparedAudioHash,
		&i.DurationMs,
		&i.TotalChunks,
		&i.CompletedChunks,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.AudioCleanedAt,
		&i.ChunksCleanedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveTranscriptVersion = `-- name: GetActiveTranscriptVersion :one
SELECT version.id, version.user_id, version.episode_id, version.transcription_run_id, version.version, version.is_active, version.status, version.created_at
FROM transcript_versions AS version
WHERE version.episode_id = $1
  AND version.user_id = $2
  AND version.is_active
`

type GetActiveTranscriptVersionParams struct {
	EpisodeID pgtype.UUID `json:"episode_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetActiveTranscriptVersion(ctx context.Context, arg GetActiveTranscriptVersionParams) (TranscriptVersion, error) {
	row := q.db.QueryRow(ctx, getActiveTranscriptVersion, arg.EpisodeID, arg.UserID)
	var i TranscriptVersion
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EpisodeID,
		&i.TranscriptionRunID,
		&i.Version,
		&i.IsActive,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestTranscriptionRunForEpisode = `-- name: GetLatestTranscriptionRunForEpisode :one
SELECT id, user_id, episode_id, profile, provider, model, status, stage, version, config, source_object_key, source_audio_hash, prepared_object_key, prepared_audio_hash, duration_ms, total_chunks, completed_chunks, started_at, completed_at, error_code, error_message, audio_cleaned_at, chunks_cleaned_at, created_at, updated_at
FROM transcription_runs
WHERE episode_id = $1
  AND user_id = $2
ORDER BY created_at DESC, id DESC
LIMIT 1
`

type GetLatestTranscriptionRunForEpisodeParams struct {
	EpisodeID pgtype.UUID `json:"episode_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetLatestTranscriptionRunForEpisode(ctx context.Context, arg GetLatestTranscriptionRunForEpisodeParams) (TranscriptionRun, error) {
	row := q.db.QueryRow(ctx, getLatestTranscriptionRunForEpisode, arg.EpisodeID, arg.UserID)
	var i TranscriptionRun
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EpisodeID,
		&i.Profile,
		&i.Provider,
		&i.Model,
		&i.Status,
		&i.Stage,
		&i.Version,
		&i.Config,
		&i.SourceObjectKey,
		&i.SourceAudioHash,
		&i.PreparedObjectKey,
		&i.PreparedAudioHash,
		&i.DurationMs,
		&i.TotalChunks,
		&i.CompletedChunks,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.AudioCleanedAt,
		&i.ChunksCleanedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTranscriptVersion = `-- name: GetTranscriptVersion :one
SELECT id, user_id, episode_id, transcription_run_id, version, is_active, status, created_at
FROM transcript_versions
WHERE id = $1
  AND user_id = $2
`

type GetTranscriptVersionParams struct {
	TranscriptID pgtype.UUID `json:"transcript_id"`
	UserID       pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetTranscriptVersion(ctx context.Context, arg GetTranscriptVersionParams) (TranscriptVersion, error) {
	row := q.db.QueryRow(ctx, getTranscriptVersion, arg.TranscriptID, arg.UserID)
	var i TranscriptVersion
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EpisodeID,
		&i.TranscriptionRunID,
		&i.Version,
		&i.IsActive,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getTranscriptionChunkForJob = `-- name: GetTranscriptionChunkForJob :one
SELECT
    chunk.id, chunk.transcription_run_id, chunk.sequence, chunk.core_start_ms, chunk.core_end_ms, chunk.render_start_ms, chunk.render_end_ms, chunk.status, chunk.object_key, chunk.audio_hash, chunk.fingerprint, chunk.external_task_id, chunk.result_url, chunk.raw_result_object_key, chunk.normalized_result, chunk.speaker_map, chunk.alignment_low_confidence, chunk.error_code, chunk.error_message, chunk.created_at, chunk.updated_at, chunk.completed_at,
    run.user_id,
    run.episode_id,
    run.provider,
    run.model,
    run.config,
    run.status AS run_status,
    run.prepared_object_key,
    run.duration_ms
FROM transcription_chunks AS chunk
JOIN transcription_runs AS run ON run.id = chunk.transcription_run_id
WHERE chunk.id = $1
`

type GetTranscriptionChunkForJobRow struct {
	ID                     pgtype.UUID        `json:"id"`
	TranscriptionRunID     pgtype.UUID        `json:"transcription_run_id"`
	Sequence               int32              `json:"sequence"`
	CoreStartMs            int64              `json:"core_start_ms"`
	CoreEndMs              int64              `json:"core_end_ms"`
	RenderStartMs          int64              `json:"render_start_ms"`
	RenderEndMs            int64              `json:"render_end_ms"`
	Status                 string             `json:"status"`
	ObjectKey              *string            `json:"object_key"`
	AudioHash              *string            `json:"audio_hash"`
	Fingerprint            *string            `json:"fingerprint"`
	ExternalTaskID         *string            `json:"external_task_id"`
	ResultUrl              *string            `json:"result_url"`
	RawResultObjectKey     *string            `json:"raw_result_object_key"`
	NormalizedResult       []byte             `json:"normalized_result"`
	SpeakerMap             []byte             `json:"speaker_map"`
	AlignmentLowConfidence bool               `json:"alignment_low_confidence"`
	ErrorCode              *string            `json:"error_code"`
	ErrorMessage           *string            `json:"error_message"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	CompletedAt            pgtype.Timestamptz `json:"completed_at"`
	UserID                 pgtype.UUID        `json:"user_id"`
	EpisodeID              pgtype.UUID        `json:"episode_id"`
	Provider               string             `json:"provider"`
	Model                  string             `json:"model"`
	Config                 []byte             `json:"config"`
	RunStatus              string             `json:"run_status"`
	PreparedObjectKey      *string            `json:"prepared_object_key"`
	DurationMs             *int64             `json:"duration_ms"`
}

func (q *Queries) GetTranscriptionChunkForJob(ctx context.Context, chunkID pgtype.UUID) (GetTranscriptionChunkForJobRow, error) {
	row := q.db.QueryRow(ctx, getTranscriptionChunkForJob, chunkID)
	var i GetTranscriptionChunkForJobRow
	err := row.Scan(
		&i.ID,
		&i.TranscriptionRunID,
		&i.Sequence,
		&i.CoreStartMs,
		&i.CoreEndMs,
		&i.RenderStartMs,
		&i.RenderEndMs,
		&i.Status,
		&i.ObjectKey,
		&i.AudioHash,
		&i.Fingerprint,
		&i.ExternalTaskID,
		&i.ResultUrl,
		&i.RawResultObjectKey,
		&i.NormalizedResult,
		&i.SpeakerMap,
		&i.AlignmentLowConfidence,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.UserID,
		&i.EpisodeID,
		&i.Provider,
		&i.Model,
		&i.Config,
		&i.RunStatus,
		&i.PreparedObjectKey,
		&i.DurationMs,
	)
	return i, err
}

const getTranscriptionRun = `-- name: GetTranscriptionRun :one
SELECT id, user_id, episode_id, profile, provider, model, status, stage, version, config, source_object_key, source_audio_hash, prepared_object_key, prepared_audio_hash, duration_ms, total_chunks, completed_chunks, started_at, completed_at, error_code, error_message, audio_cleaned_at, chunks_cleaned_at, created_at, updated_at
FROM transcription_runs
WHERE id = $1
  AND user_id = $2
`

type GetTranscriptionRunParams struct {
	RunID  pgtype.UUID `json:"run_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetTranscriptionRun(ctx context.Context, arg GetTranscriptionRunParams) (TranscriptionRun, error) {
	row := q.db.QueryRow(ctx, getTranscriptionRun, arg.RunID, arg.UserID)
	var i TranscriptionRun
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EpisodeID,
		&i.Profile,
		&i.Provider,
		&i.Model,
		&i.Status,
		&i.Stage,
		&i.Version,
		&i.Config,
		&i.SourceObjectKey,
		&i.SourceAudioHash,
		&i.PreparedObjectKey,
		&i.PreparedAudioHash,
		&i.DurationMs,
		&i.TotalChunks,
		&i.CompletedChunks,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.AudioCleanedAt,
		&i.ChunksCleanedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTranscriptionRunForJob = `-- name: GetTranscriptionRunForJob :one
SELECT
    run.id, run.user_id, run.episode_id, run.profile, run.provider, run.model, run.status, run.stage, run.version, run.config, run.source_object_key, run.source_audio_hash, run.prepared_object_key, run.prepared_audio_hash, run.duration_ms, run.total_chunks, run.completed_chunks, run.started_at, run.completed_at, run.error_code, run.error_message, run.audio_cleaned_at, run.chunks_cleaned_at, run.created_at, run.updated_at,
    COALESCE((
        SELECT source.audio_url
        FROM episode_sources AS source
        WHERE source.episode_id = run.episode_id
          AND source.user_id = run.user_id
        ORDER BY source.created_at DESC, source.id DESC
        LIMIT 1
    ), '')::text AS audio_url
FROM transcription_runs AS run
WHERE run.id = $1
`

type GetTranscriptionRunForJobRow struct {
	ID                pgtype.UUID        `json:"id"`
	UserID            pgtype.UUID        `json:"user_id"`
	EpisodeID         pgtype.UUID        `json:"episode_id"`
	Profile           string             `json:"profile"`
	Provider          string             `json:"provider"`
	Model             string             `json:"model"`
	Status            string             `json:"status"`
	Stage             string             `json:"stage"`
	Version           int32              `json:"version"`
	Config            []byte             `json:"config"`
	SourceObjectKey   *string            `json:"source_object_key"`
	SourceAudioHash   *string            `json:"source_audio_hash"`
	PreparedObjectKey *string            `json:"prepared_object_key"`
	PreparedAudioHash *string            `json:"prepared_audio_hash"`
	DurationMs        *int64             `json:"duration_ms"`
	TotalChunks       int32              `json:"total_chunks"`
	CompletedChunks   int32              `json:"completed_chunks"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
	ErrorCode         *string            `json:"error_code"`
	ErrorMessage      *string            `json:"error_message"`
	AudioCleanedAt    pgtype.Timestamptz `json:"audio_cleaned_at"`
	ChunksCleanedAt   pgtype.Timestamptz `json:"chunks_cleaned_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	AudioUrl          string             `json:"audio_url"`
}

func (q *Queries) GetTranscriptionRunForJob(ctx context.Context, runID pgtype.UUID) (GetTranscriptionRunForJobRow, error) {
	row := q.db.QueryRow(ctx, getTranscriptionRunForJob, runID)
	var i GetTranscriptionRunForJobRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EpisodeID,
		&i.Profile,
		&i.Provider,
		&i.Model,
		&i.Status,
		&i.Stage,
		&i.Version,
		&i.Config,
		&i.SourceObjectKey,
		&i.SourceAudioHash,
		&i.PreparedObjectKey,
		&i.PreparedAudioHash,
		&i.DurationMs,
		&i.TotalChunks,
		&i.CompletedChunks,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.AudioCleanedAt,
		&i.ChunksCleanedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AudioUrl,
	)
	return i, err
}

const incrementRunCompletedChunks = `-- name: IncrementRunCompletedChunks :one
UPDATE transcription_runs
SET completed_chunks = completed_chunks + 1,
    stage = CASE WHEN completed_chunks + 1 = total_chunks THEN 'speaker_alignment_queued' ELSE 'transcribing_chunks' END,
    updated_at = now()
WHERE id = $1
  AND status = 'transcribing'
  AND completed_chunks < total_chunks
RETURNING id, user_id, episode_id, profile, provider, model, status, stage, version, config, source_object_key, source_audio_hash, prepared_object_key, prepared_audio_hash, duration_ms, total_chunks, completed_chunks, started_at, completed_at, error_code, error_message, audio_cleaned_at, chunks_cleaned_at, created_at, updated_at
`

func (q *Queries) IncrementRunCompletedChunks(ctx context.Context, runID pgtype.UUID) (TranscriptionRun, error) {
	row := q.db.QueryRow(ctx, incrementRunCompletedChunks, runID)
	var i TranscriptionRun
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EpisodeID,
		&i.Profile,
		&i.Provider,
		&i.Model,
		&i.Status,
		&i.Stage,
		&i.Version,
		&i.Config,
		&i.SourceObjectKey,
		&i.SourceAudioHash,
		&i.PreparedObjectKey,
		&i.PreparedAudioHash,
		&i.DurationMs,
		&i.TotalChunks,
		&i.CompletedChunks,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.AudioCleanedAt,
		&i.ChunksCleanedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRunChunkObjectKeys = `-- name: ListRunChunkObjectKeys :many
SELECT object_key
FROM transcription_chunks
WHERE transcription_run_id = $1
  AND object_key IS NOT NULL
ORDER BY sequence
`

func (q *Queries) ListRunChunkObjectKeys(ctx context.Context, runID pgtype.UUID) ([]*string, error) {
	rows, err := q.db.Query(ctx, listRunChunkObjectKeys, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*string{}
	for rows.Next() {
		var object_key *string
		if err := rows.Scan(&object_key); err != nil {
			return nil, err
		}
		items = append(items, object_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunChunks = `-- name: ListRunChunks :many
SELECT id, transcription_run_id, sequence, core_start_ms, core_end_ms, render_start_ms, render_end_ms, status, object_key, audio_hash, fingerprint, external_task_id, result_url, raw_result_object_key, normalized_result, speaker_map, alignment_low_confidence, error_code, error_message, created_at, updated_at, completed_at
FROM transcription_chunks
WHERE transcription_run_id = $1
ORDER BY sequence
`

func (q *Queries) ListRunChunks(ctx context.Context, runID pgtype.UUID) ([]TranscriptionChunk, error) {
	rows, err := q.db.Query(ctx, listRunChunks, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TranscriptionChunk{}
	for rows.Next() {
		var i TranscriptionChunk
		if err := rows.Scan(
			&i.ID,
			&i.TranscriptionRunID,
			&i.Sequence,
			&i.CoreStartMs,
			&i.CoreEndMs,
			&i.RenderStartMs,
			&i.RenderEndMs,
			&i.Status,
			&i.ObjectKey,
			&i.AudioHash,
			&i.Fingerprint,
			&i.ExternalTaskID,
			&i.ResultUrl,
			&i.RawResultObjectKey,
			&i.NormalizedResult,
			&i.SpeakerMap,
			&i.AlignmentLowConfidence,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTranscriptSegments = `-- name: ListTranscriptSegments :many
SELECT segment.id, segment.transcript_version_id, segment.speaker_id, segment.sequence, segment.start_ms, segment.end_ms, segment.text, segment.words, segment.source_chunk_id, segment.created_at
FROM transcript_segments AS segment
JOIN transcript_versions AS version ON version.id = segment.transcript_version_id
WHERE segment.transcript_version_id = $1
  AND version.user_id = $2
ORDER BY segment.sequence
LIMIT $4::int
OFFSET $3::int
`

type ListTranscriptSegmentsParams struct {
	TranscriptID pgtype.UUID `json:"transcript_id"`
	UserID       pgtype.UUID `json:"user_id"`
	PageOffset   int32       `json:"page_offset"`
	PageLimit    int32       `json:"page_limit"`
}

func (q *Queries) ListTranscriptSegments(ctx context.Context, arg ListTranscriptSegmentsParams) ([]TranscriptSegment, error) {
	rows, err := q.db.Query(ctx, listTranscriptSegments,
		arg.TranscriptID,
		arg.UserID,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TranscriptSegment{}
	for rows.Next() {
		var i TranscriptSegment
		if err := rows.Scan(
			&i.ID,
			&i.TranscriptVersionID,
			&i.SpeakerID,
			&i.Sequence,
			&i.StartMs,
			&i.EndMs,
			&i.Text,
			&i.Words,
			&i.SourceChunkID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTranscriptSpeakers = `-- name: ListTranscriptSpeakers :many
SELECT speaker.id, speaker.transcript_version_id, speaker.stable_key, speaker.display_name, speaker.role, speaker.speaker_profile_id, speaker.created_at, speaker.updated_at
FROM transcript_speakers AS speaker
JOIN transcript_versions AS version ON version.id = speaker.transcript_version_id
WHERE speaker.transcript_version_id = $1
  AND version.user_id = $2
ORDER BY speaker.stable_key
`

type ListTranscriptSpeakersParams struct {
	TranscriptID pgtype.UUID `json:"transcript_id"`
	UserID       pgtype.UUID `json:"user_id"`
}

func (q *Queries) ListTranscriptSpeakers(ctx context.Context, arg ListTranscriptSpeakersParams) ([]TranscriptSpeaker, error) {
	rows, err := q.db.Query(ctx, listTranscriptSpeakers, arg.TranscriptID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TranscriptSpeaker{}
	for rows.Next() {
		var i TranscriptSpeaker
		if err := rows.Scan(
			&i.ID,
			&i.TranscriptVersionID,
			&i.StableKey,
			&i.DisplayName,
			&i.Role,
			&i.SpeakerProfileID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEpisodeForTranscription = `-- name: LockEpisodeForTranscription :one
SELECT
    episode.id,
    episode.resolve_status,
    episode.transcription_status,
    COALESCE((
        SELECT source.audio_url
        FROM episode_sources AS source
        WHERE source.episode_id = episode.id
          AND source.user_id = episode.user_id
        ORDER BY source.created_at DESC, source.id DESC
        LIMIT 1
    ), '')::text AS audio_url
FROM episodes AS episode
WHERE episode.id = $1
  AND episode.user_id = $2
FOR UPDATE OF episode
`

type LockEpisodeForTranscriptionParams struct {
	EpisodeID pgtype.UUID `json:"episode_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

type LockEpisodeForTranscriptionRow struct {
	ID                  pgtype.UUID `json:"id"`
	ResolveStatus       string      `json:"resolve_status"`
	TranscriptionStatus string      `json:"transcription_status"`
	AudioUrl            string      `json:"audio_url"`
}

func (q *Queries) LockEpisodeForTranscription(ctx context.Context, arg LockEpisodeForTranscriptionParams) (LockEpisodeForTranscriptionRow, error) {
	row := q.db.QueryRow(ctx, lockEpisodeForTranscription, arg.EpisodeID, arg.UserID)
	var i LockEpisodeForTranscriptionRow
	err := row.Scan(
		&i.ID,
		&i.ResolveStatus,
		&i.TranscriptionStatus,
		&i.AudioUrl,
	)
	return i, err
}

const lockTranscriptionRun = `-- name: LockTranscriptionRun :one
SELECT id, user_id, episode_id, profile, provider, model, status, stage, version, config, source_object_key, source_audio_hash, prepared_object_key, prepared_audio_hash, duration_ms, total_chunks, completed_chunks, started_at, completed_at, error_code, error_message, audio_cleaned_at, chunks_cleaned_at, created_at, updated_at
FROM transcription_runs
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockTranscriptionRun(ctx context.Context, runID pgtype.UUID) (TranscriptionRun, error) {
	row := q.db.QueryRow(ctx, lockTranscriptionRun, runID)
	var i TranscriptionRun
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EpisodeID,
		&i.Profile,
		&i.Provider,
		&i.Model,
		&i.Status,
		&i.Stage,
		&i.Version,
		&i.Config,
		&i.SourceObjectKey,
		&i.SourceAudioHash,
		&i.PreparedObjectKey,
		&i.PreparedAudioHash,
		&i.DurationMs,
		&i.TotalChunks,
		&i.CompletedChunks,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.AudioCleanedAt,
		&i.ChunksCleanedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markRunAudioCleaned = `-- name: MarkRunAudioCleaned :exec
UPDATE transcription_runs
SET audio_cleaned_at = now(),
    updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkRunAudioCleaned(ctx context.Context, runID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markRunAudioCleaned, runID)
	return err
}

const markRunChunksCleaned = `-- name: MarkRunChunksCleaned :exec
UPDATE transcription_runs
SET chunks_cleaned_at = now(),
    updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkRunChunksCleaned(ctx context.Context, runID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markRunChunksCleaned, runID)
	return err
}

const nextTranscriptVersion = `-- name: NextTranscriptVersion :one
SELECT COALESCE(max(version), 0)::int + 1
FROM transcript_versions
WHERE episode_id = $1
`

func (q *Queries) NextTranscriptVersion(ctx context.Context, episodeID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextTranscriptVersion, episodeID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const resetChunkSubmit = `-- name: ResetChunkSubmit :exec
UPDATE transcription_chunks
SET status = 'ready',
    updated_at = now()
WHERE id = $1
  AND status = 'submitting'
  AND external_task_id IS NULL
`

func (q *Queries) ResetChunkSubmit(ctx context.Context, chunkID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, resetChunkSubmit, chunkID)
	return err
}

const setChunkIngested = `-- name: SetChunkIngested :one
UPDATE transcription_chunks
SET status = 'completed',
    raw_result_object_key = $1,
    normalized_result = $2::jsonb,
    error_code = NULL,
    error_message = NULL,
    updated_at = now(),
    completed_at = now()
WHERE id = $3
  AND status = 'running'
  AND result_url IS NOT NULL
RETURNING id, transcription_run_id, sequence, core_start_ms, core_end_ms, render_start_ms, render_end_ms, status, object_key, audio_hash, fingerprint, external_task_id, result_url, raw_result_object_key, normalized_result, speaker_map, alignment_low_confidence, error_code, error_message, created_at, updated_at, completed_at
`

type SetChunkIngestedParams struct {
	RawResultObjectKey *string     `json:"raw_result_object_key"`
	NormalizedResult   []byte      `json:"normalized_result"`
	ChunkID            pgtype.UUID `json:"chunk_id"`
}

func (q *Queries) SetChunkIngested(ctx context.Context, arg SetChunkIngestedParams) (TranscriptionChunk, error) {
	row := q.db.QueryRow(ctx, setChunkIngested, arg.RawResultObjectKey, arg.NormalizedResult, arg.ChunkID)
	var i TranscriptionChunk
	err := row.Scan(
		&i.ID,
		&i.TranscriptionRunID,
		&i.Sequence,
		&i.CoreStartMs,
		&i.CoreEndMs,
		&i.RenderStartMs,
		&i.RenderEndMs,
		&i.Status,
		&i.ObjectKey,
		&i.AudioHash,
		&i.Fingerprint,
		&i.ExternalTaskID,
		&i.ResultUrl,
		&i.RawResultObjectKey,
		&i.NormalizedResult,
		&i.SpeakerMap,
		&i.AlignmentLowConfidence,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const setChunkPolling = `-- name: SetChunkPolling :exec
UPDATE transcription_chunks
SET status = 'running',
    updated_at = now()
WHERE id = $1
  AND status IN ('submitted', 'running')
`

func (q *Queries) SetChunkPolling(ctx context.Context, chunkID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setChunkPolling, chunkID)
	return err
}

const setChunkRendered = `-- name: SetChunkRendered :one
UPDATE transcription_chunks
SET status = 'ready',
    object_key = $1,
    audio_hash = $2,
    fingerprint = $3,
    error_code = NULL,
    error_message = NULL,
    updated_at = now()
WHERE id = $4
  AND status = 'rendering'
RETURNING id, transcription_run_id, sequence, core_start_ms, core_end_ms, render_start_ms, render_end_ms, status, object_key, audio_hash, fingerprint, external_task_id, result_url, raw_result_object_key, normalized_result, speaker_map, alignment_low_confidence, error_code, error_message, created_at, updated_at, completed_at
`

type SetChunkRenderedParams struct {
	ObjectKey   *string     `json:"object_key"`
	AudioHash   *string     `json:"audio_hash"`
	Fingerprint *string     `json:"fingerprint"`
	ChunkID     pgtype.UUID `json:"chunk_id"`
}

func (q *Queries) SetChunkRendered(ctx context.Context, arg SetChunkRenderedParams) (TranscriptionChunk, error) {
	row := q.db.QueryRow(ctx, setChunkRendered,
		arg.ObjectKey,
		arg.AudioHash,
		arg.Fingerprint,
		arg.ChunkID,
	)
	var i TranscriptionChunk
	err := row.Scan(
		&i.ID,
		&i.TranscriptionRunID,
		&i.Sequence,
		&i.CoreStartMs,
		&i.CoreEndMs,
		&i.RenderStartMs,
		&i.RenderEndMs,
		&i.Status,
		&i.ObjectKey,
		&i.AudioHash,
		&i.Fingerprint,
		&i.ExternalTaskID,
		&i.ResultUrl,
		&i.RawResultObjectKey,
		&i.NormalizedResult,
		&i.SpeakerMap,
		&i.AlignmentLowConfidence,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const setChunkResultReady = `-- name: SetChunkResultReady :one
UPDATE transcription_chunks
SET status = 'running',
    result_url = $1,
    updated_at = now()
WHERE id = $2
  AND status IN ('submitted', 'running')
RETURNING id, transcription_run_id, sequence, core_start_ms, core_end_ms, render_start_ms, render_end_ms, status, object_key, audio_hash, fingerprint, external_task_id, result_url, raw_result_object_key, normalized_result, speaker_map, alignment_low_confidence, error_code, error_message, created_at, updated_at, completed_at
`

type SetChunkResultReadyParams struct {
	ResultUrl *string     `json:"result_url"`
	ChunkID   pgtype.UUID `json:"chunk_id"`
}

func (q *Queries) SetChunkResultReady(ctx context.Context, arg SetChunkResultReadyParams) (TranscriptionChunk, error) {
	row := q.db.QueryRow(ctx, setChunkResultReady, arg.ResultUrl, arg.ChunkID)
	var i TranscriptionChunk
	err := row.Scan(
		&i.ID,
		&i.TranscriptionRunID,
		&i.Sequence,
		&i.CoreStartMs,
		&i.CoreEndMs,
		&i.RenderStartMs,
		&i.RenderEndMs,
		&i.Status,
		&i.ObjectKey,
		&i.AudioHash,
		&i.Fingerprint,
		&i.ExternalTaskID,
		&i.ResultUrl,
		&i.RawResultObjectKey,
		&i.NormalizedResult,
		&i.SpeakerMap,
		&i.AlignmentLowConfidence,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const setChunkSpeakerMap = `-- name: SetChunkSpeakerMap :exec
UPDATE transcription_chunks
SET speaker_map = $1::jsonb,
    alignment_low_confidence = $2,
    updated_at = now()
WHERE id = $3
  AND status = 'completed'
`

type SetChunkSpeakerMapParams struct {
	SpeakerMap    []byte      `json:"speaker_map"`
	LowConfidence bool        `json:"low_confidence"`
	ChunkID       pgtype.UUID `json:"chunk_id"`
}

func (q *Queries) SetChunkSpeakerMap(ctx context.Context, arg SetChunkSpeakerMapParams) error {
	_, err := q.db.Exec(ctx, setChunkSpeakerMap, arg.SpeakerMap, arg.LowConfidence, arg.ChunkID)
	return err
}

const setChunkSubmitted = `-- name: SetChunkSubmitted :one
UPDATE transcription_chunks
SET status = 'submitted',
    external_task_id = $1,
    updated_at = now()
WHERE id = $2
  AND status = 'submitting'
  AND external_task_id IS NULL
RETURNING id, transcription_run_id, sequence, core_start_ms, core_end_ms, render_start_ms, render_end_ms, status, object_key, audio_hash, fingerprint, external_task_id, result_url, raw_result_object_key, normalized_result, speaker_map, alignment_low_confidence, error_code, error_message, created_at, updated_at, completed_at
`

type SetChunkSubmittedParams struct {
	ExternalTaskID *string     `json:"external_task_id"`
	ChunkID        pgtype.UUID `json:"chunk_id"`
}

func (q *Queries) SetChunkSubmitted(ctx context.Context, arg SetChunkSubmittedParams) (TranscriptionChunk, error) {
	row := q.db.QueryRow(ctx, setChunkSubmitted, arg.ExternalTaskID, arg.ChunkID)
	var i TranscriptionChunk
	err := row.Scan(
		&i.ID,
		&i.TranscriptionRunID,
		&i.Sequence,
		&i.CoreStartMs,
		&i.CoreEndMs,
		&i.RenderStartMs,
		&i.RenderEndMs,
		&i.Status,
		&i.ObjectKey,
		&i.AudioHash,
		&i.Fingerprint,
		&i.ExternalTaskID,
		&i.ResultUrl,
		&i.RawResultObjectKey,
		&i.NormalizedResult,
		&i.SpeakerMap,
		&i.AlignmentLowConfidence,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const setEpisodeTranscriptionStatus = `-- name: SetEpisodeTranscriptionStatus :exec
UPDATE episodes
SET transcription_status = $1,
    updated_at = now()
WHERE id = $2
  AND user_id = $3
`

type SetEpisodeTranscriptionStatusParams struct {
	Status    string      `json:"status"`
	EpisodeID pgtype.UUID `json:"episode_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) SetEpisodeTranscriptionStatus(ctx context.Context, arg SetEpisodeTranscriptionStatusParams) error {
	_, err := q.db.Exec(ctx, setEpisodeTranscriptionStatus, arg.Status, arg.EpisodeID, arg.UserID)
	return err
}

const setRunAligning = `-- name: SetRunAligning :one
UPDATE transcription_runs
SET status = 'aligning',
    stage = 'aligning_speakers',
    updated_at = now()
WHERE id = $1
  AND status IN ('transcribing', 'aligning')
  AND completed_chunks = total_chunks
  AND total_chunks > 0
RETURNING id, user_id, episode_id, profile, provider, model, status, stage, version, config, source_object_key, source_audio_hash, prepared_object_key, prepared_audio_hash, duration_ms, total_chunks, completed_chunks, started_at, completed_at, error_code, error_message, audio_cleaned_at, chunks_cleaned_at, created_at, updated_at
`

func (q *Queries) SetRunAligning(ctx context.Context, runID pgtype.UUID) (TranscriptionRun, error) {
	row := q.db.QueryRow(ctx, setRunAligning, runID)
	var i TranscriptionRun
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EpisodeID,
		&i.Profile,
		&i.Provider,
		&i.Model,
		&i.Status,
		&i.Stage,
		&i.Version,
		&i.Config,
		&i.SourceObjectKey,
		&i.SourceAudioHash,
		&i.PreparedObjectKey,
		&i.PreparedAudioHash,
		&i.DurationMs,
		&i.TotalChunks,
		&i.CompletedChunks,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.AudioCleanedAt,
		&i.ChunksCleanedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setRunDownloadStarted = `-- name: SetRunDownloadStarted :one
UPDATE transcription_runs
SET status = 'downloading',
    stage = 'downloading_audio',
    started_at = COALESCE(started_at, now()),
    updated_at = now()
WHERE id = $1
  AND status = 'queued'
RETURNING id, user_id, episode_id, profile, provider, model, status, stage, version, config, source_object_key, source_audio_hash, prepared_object_key, prepared_audio_hash, duration_ms, total_chunks, completed_chunks, started_at, completed_at, error_code, error_message, audio_cleaned_at, chunks_cleaned_at, created_at, updated_at
`

func (q *Queries) SetRunDownloadStarted(ctx context.Context, runID pgtype.UUID) (TranscriptionRun, error) {
	row := q.db.QueryRow(ctx, setRunDownloadStarted, runID)
	var i TranscriptionRun
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EpisodeID,
		&i.Profile,
		&i.Provider,
		&i.Model,
		&i.Status,
		&i.Stage,
		&i.Version,
		&i.Config,
		&i.SourceObjectKey,
		&i.SourceAudioHash,
		&i.PreparedObjectKey,
		&i.PreparedAudioHash,
		&i.DurationMs,
		&i.TotalChunks,
		&i.CompletedChunks,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.AudioCleanedAt,
		&i.ChunksCleanedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setRunDownloaded = `-- name: SetRunDownloaded :one
UPDATE transcription_runs
SET status = 'preparing',
    stage = 'preparing_audio',
    source_object_key = $1,
    source_audio_hash = $2,
    updated_at = now()
WHERE id = $3
  AND status = 'downloading'
RETURNING id, user_id, episode_id, profile, provider, model, status, stage, version, config, source_object_key, source_audio_hash, prepared_object_key, prepared_audio_hash, duration_ms, total_chunks, completed_chunks, started_at, completed_at, error_code, error_message, audio_cleaned_at, chunks_cleaned_at, created_at, updated_at
`

type SetRunDownloadedParams struct {
	SourceObjectKey *string     `json:"source_object_key"`
	SourceAudioHash *string     `json:"source_audio_hash"`
	RunID           pgtype.UUID `json:"run_id"`
}

func (q *Queries) SetRunDownloaded(ctx context.Context, arg SetRunDownloadedParams) (TranscriptionRun, error) {
	row := q.db.QueryRow(ctx, setRunDownloaded, arg.SourceObjectKey, arg.SourceAudioHash, arg.RunID)
	var i TranscriptionRun
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EpisodeID,
		&i.Profile,
		&i.Provider,
		&i.Model,
		&i.Status,
		&i.Stage,
		&i.Version,
		&i.Config,
		&i.SourceObjectKey,
		&i.SourceAudioHash,
		&i.PreparedObjectKey,
		&i.PreparedAudioHash,
		&i.DurationMs,
		&i.TotalChunks,
		&i.CompletedChunks,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.AudioCleanedAt,
		&i.ChunksCleanedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setRunMerging = `-- name: SetRunMerging :one
UPDATE transcription_runs
SET status = 'merging',
    stage = 'merging_transcript',
    updated_at = now()
WHERE id = $1
  AND status = 'aligning'
RETURNING id, user_id, episode_id, profile, provider, model, status, stage, version, config, source_object_key, source_audio_hash, prepared_object_key, prepared_audio_hash, duration_ms, total_chunks, completed_chunks, started_at, completed_at, error_code, error_message, audio_cleaned_at, chunks_cleaned_at, created_at, updated_at
`

func (q *Queries) SetRunMerging(ctx context.Context, runID pgtype.UUID) (TranscriptionRun, error) {
	row := q.db.QueryRow(ctx, setRunMerging, runID)
	var i TranscriptionRun
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EpisodeID,
		&i.Profile,
		&i.Provider,
		&i.Model,
		&i.Status,
		&i.Stage,
		&i.Version,
		&i.Config,
		&i.SourceObjectKey,
		&i.SourceAudioHash,
		&i.PreparedObjectKey,
		&i.PreparedAudioHash,
		&i.DurationMs,
		&i.TotalChunks,
		&i.CompletedChunks,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.AudioCleanedAt,
		&i.ChunksCleanedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setRunPrepared = `-- name: SetRunPrepared :one
UPDATE transcription_runs
SET stage = 'planning_chunks',
    prepared_object_key = $1,
    prepared_audio_hash = $2,
    duration_ms = $3,
    updated_at = now()
WHERE id = $4
  AND status = 'preparing'
RETURNING id, user_id, episode_id, profile, provider, model, status, stage, version, config, source_object_key, source_audio_hash, prepared_object_key, prepared_audio_hash, duration_ms, total_chunks, completed_chunks, started_at, completed_at, error_code, error_message, audio_cleaned_at, chunks_cleaned_at, created_at, updated_at
`

type SetRunPreparedParams struct {
	PreparedObjectKey *string     `json:"prepared_object_key"`
	PreparedAudioHash *string     `json:"prepared_audio_hash"`
	DurationMs        *int64      `json:"duration_ms"`
	RunID             pgtype.UUID `json:"run_id"`
}

func (q *Queries) SetRunPrepared(ctx context.Context, arg SetRunPreparedParams) (TranscriptionRun, error) {
	row := q.db.QueryRow(ctx, setRunPrepared,
		arg.PreparedObjectKey,
		arg.PreparedAudioHash,
		arg.DurationMs,
		arg.RunID,
	)
	var i TranscriptionRun
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EpisodeID,
		&i.Profile,
		&i.Provider,
		&i.Model,
		&i.Status,
		&i.Stage,
		&i.Version,
		&i.Config,
		&i.SourceObjectKey,
		&i.SourceAudioHash,
		&i.PreparedObjectKey,
		&i.PreparedAudioHash,
		&i.DurationMs,
		&i.TotalChunks,
		&i.CompletedChunks,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.AudioCleanedAt,
		&i.ChunksCleanedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setRunTranscribing = `-- name: SetRunTranscribing :one
UPDATE transcription_runs
SET status = 'transcribing',
    stage = 'rendering_chunks',
    total_chunks = $1,
    updated_at = now()
WHERE id = $2
  AND status = 'preparing'
  AND total_chunks = 0
RETURNING id, user_id, episode_id, profile, provider, model, status, stage, version, config, source_object_key, source_audio_hash, prepared_object_key, prepared_audio_hash, duration_ms, total_chunks, completed_chunks, started_at, completed_at, error_code, error_message, audio_cleaned_at, chunks_cleaned_at, created_at, updated_at
`

type SetRunTranscribingParams struct {
	TotalChunks int32       `json:"total_chunks"`
	RunID       pgtype.UUID `json:"run_id"`
}

func (q *Queries) SetRunTranscribing(ctx context.Context, arg SetRunTranscribingParams) (TranscriptionRun, error) {
	row := q.db.QueryRow(ctx, setRunTranscribing, arg.TotalChunks, arg.RunID)
	var i TranscriptionRun
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EpisodeID,
		&i.Profile,
		&i.Provider,
		&i.Model,
		&i.Status,
		&i.Stage,
		&i.Version,
		&i.Config,
		&i.SourceObjectKey,
		&i.SourceAudioHash,
		&i.PreparedObjectKey,
		&i.PreparedAudioHash,
		&i.DurationMs,
		&i.TotalChunks,
		&i.CompletedChunks,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.AudioCleanedAt,
		&i.ChunksCleanedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const startChunkRender = `-- name: StartChunkRender :one
UPDATE transcription_chunks
SET status = 'rendering',
    updated_at = now()
WHERE id = $1
  AND status = 'planned'
RETURNING id, transcription_run_id, sequence, core_start_ms, core_end_ms, render_start_ms, render_end_ms, status, object_key, audio_hash, fingerprint, external_task_id, result_url, raw_result_object_key, normalized_result, speaker_map, alignment_low_confidence, error_code, error_message, created_at, updated_at, completed_at
`

func (q *Queries) StartChunkRender(ctx context.Context, chunkID pgtype.UUID) (TranscriptionChunk, error) {
	row := q.db.QueryRow(ctx, startChunkRender, chunkID)
	var i TranscriptionChunk
	err := row.Scan(
		&i.ID,
		&i.TranscriptionRunID,
		&i.Sequence,
		&i.CoreStartMs,
		&i.CoreEndMs,
		&i.RenderStartMs,
		&i.RenderEndMs,
		&i.Status,
		&i.ObjectKey,
		&i.AudioHash,
		&i.Fingerprint,
		&i.ExternalTaskID,
		&i.ResultUrl,
		&i.RawResultObjectKey,
		&i.NormalizedResult,
		&i.SpeakerMap,
		&i.AlignmentLowConfidence,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const startChunkSubmit = `-- name: StartChunkSubmit :one
UPDATE transcription_chunks
SET status = 'submitting',
    updated_at = now()
WHERE id = $1
  AND status = 'ready'
RETURNING id, transcription_run_id, sequence, core_start_ms, core_end_ms, render_start_ms, render_end_ms, status, object_key, audio_hash, fingerprint, external_task_id, result_url, raw_result_object_key, normalized_result, speaker_map, alignment_low_confidence, error_code, error_message, created_at, updated_at, completed_at
`

func (q *Queries) StartChunkSubmit(ctx context.Context, chunkID pgtype.UUID) (TranscriptionChunk, error) {
	row := q.db.QueryRow(ctx, startChunkSubmit, chunkID)
	var i TranscriptionChunk
	err := row.Scan(
		&i.ID,
		&i.TranscriptionRunID,
		&i.Sequence,
		&i.CoreStartMs,
		&i.CoreEndMs,
		&i.RenderStartMs,
		&i.RenderEndMs,
		&i.Status,
		&i.ObjectKey,
		&i.AudioHash,
		&i.Fingerprint,
		&i.ExternalTaskID,
		&i.ResultUrl,
		&i.RawResultObjectKey,
		&i.NormalizedResult,
		&i.SpeakerMap,
		&i.AlignmentLowConfidence,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}
