// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bindUserIdentity = `-- name: BindUserIdentity :execrows
UPDATE users
SET auth_issuer = $1,
    auth_subject = $2,
    updated_at = now()
WHERE id = $3
  AND auth_issuer IS NULL
  AND auth_subject IS NULL
`

type BindUserIdentityParams struct {
	AuthIssuer  *string     `json:"auth_issuer"`
	AuthSubject *string     `json:"auth_subject"`
	UserID      pgtype.UUID `json:"user_id"`
}

func (q *Queries) BindUserIdentity(ctx context.Context, arg BindUserIdentityParams) (int64, error) {
	result, err := q.db.Exec(ctx, bindUserIdentity, arg.AuthIssuer, arg.AuthSubject, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resolveUser = `-- name: ResolveUser :one
INSERT INTO users (auth_issuer, auth_subject, email)
VALUES ($1, $2, $3::text)
ON CONFLICT (auth_issuer, auth_subject) WHERE auth_issuer IS NOT NULL AND auth_subject IS NOT NULL
DO UPDATE SET
    email = COALESCE(EXCLUDED.email, users.email),
    updated_at = now()
WHERE users.status = 'active'
RETURNING id
`

type ResolveUserParams struct {
	AuthIssuer  *string `json:"auth_issuer"`
	AuthSubject *string `json:"auth_subject"`
	Email       *string `json:"email"`
}

func (q *Queries) ResolveUser(ctx context.Context, arg ResolveUserParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, resolveUser, arg.AuthIssuer, arg.AuthSubject, arg.Email)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
